webpack/webpack-dev-server

client/style.css

The error output displays errors in a variable width font. Since this output is effectively the same as what's output by loaders to the CLI it can look strange when using loaders that output error information expecting fixed width fonts (in this example 6to5/6to5). Screenshot showing before and after this change.

use a monospace font for error output

---

package.json

fixes: #73 
This will not work in cases where (somehow, not through normal use of webpack-dev-server; perhaps you built --inline into a bundle?) you have a different client socket.io version.

update socket.io to 1.3.3

---

bin/webpack-dev-server.js

Issue #115 
When launching webpack-dev-server as a script using npm, using a specific IP and/or port requires hardcoding the values. With this change, a different route is offered. The host/port can be passed inside the devServer object contained in a projects webpack config. CLI flags will take precedence over these options.

Add option to set IP and port inside webpack config

---

lib/Server.js

When trying to set-up webpack-dev-server today via the API I ran into an issue that I was unable to ever load the bundle.
The issue was that the `filename` is only given a default when set via the CLI.  I [updated the wiki to note this requirement](https://github.com/webpack/docs/wiki/webpack-dev-server/_compare/58ce95651f311ad99ca6ef694258f2141abfc84c...14496dc39d893c41b1c4abd475da607bf0ccfc1f) however it'd be good to have it built into the code by default.

Add default filename when using through api

---

bin/webpack-dev-server.js
lib/Server.js

I think the purpose of this PR got missed with my last one. I'm reopening because this is a feature that either makes or breaks the server for me and I'm sure many others. I've implemented this many times and seen it implemented even more. I also changed the configurations to be more flexible.
This adds an option to proxy a *single path* to an arbitrary server. This is different than the contentBase setting, which can proxy all requests or none. Unless I'm missing a configuration, this is something that *is not possible* with the server as it stands.
Here are some use cases that make this feature worthwhile:
* Developing a front end that uses a server side API that runs in a different process or on a different computer.
* Debugging a problem in production using a local build with …

Add proxy to allow working with a back end on a different server/port

---

client/index.js
client/live.js
package.json

It's also possible to convert it to style or whatever the console uses. fixes #136

Get rid of ANSI escaping

---

lib/Server.js

Added extra error handling when using the proxy option. I notice that the deprecated contentBase option does include error handling when being used as a proxy that prevents the dev server from crashing if any proxied requests fail. The proxy option did not include this extra error handling, so I added it.

Failure to proxy a request no longer causes the dev server to crash

---

lib/Server.js

Both `contentBase: "http://url"` and `proxy` are incompatible with `historyApiFallback`. This PR fixes that.
Setup webpack with config
```
var server = new WebpackDevServer(webpack(config), {
historyApiFallback: true,
proxy: {
"/api/*": "http://localhost:3100/"
}
})
```
Then, open `/api/foo` in browser.
__Expected result:__ result from proxy is returned.
__Actual result:__ index.html is returned.

fix historyApiFallback+proxy combo

---

client/index.js

Errors were cleaned up recently: 6ea80ce82ef5020e112f9f7c69c37134329e19ca, but warnings were not.

Strip ANSI escaping from warnings

---

lib/Server.js
package.json

To make connect-history-api-fallback [options](https://github.com/bripkens/connect-history-api-fallback#options) configurable

Update connect-history-api-fallback dependency and allow passing params to it

---

lib/Server.js

Hi,
I want to use webpack-dev-server with backend Heroku.
But it returns 404. (No such app)
I found this article and made this change.
http://stackoverflow.com/questions/6444280/heroku-no-such-app-error-with-node-js-node-http-proxy-module
So, it works fine.
Please consider to merge this.

proxy doesn't work with Heroku

---

bin/webpack-dev-server.js
lib/Server.js

added support for regex path and rewrite in proxy options

---

lib/Server.js

Emitting "still-ok" and returning means that no "error" event is emitted , forcing the user to manually refresh the page to see compile errors.
This change causes compile errors to be shown with no manual refresh needed.
Before:
After:

Don't emit "still-ok" when there are errors

---

lib/Server.js

This removes the whole mutual-authentication aspect of the SSL handshake. For many people, a server requesting an SSL client cert means an OS X keychain pop up to unlock the System keychain -- :fearful: :hocho:
When we remove the `requestCert` option, `rejectUnauthorized` now becomes meaningless. 
Node docs for the options `requestCert` and `rejectUnauthorized`: https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener

Remove SSL mutual auth requirement from https option

---

client/index.js

Related #46, #220, (kind of) #239
This PR allows you to use `'webpack-dev-server/client?http://mydomain/mysocket.io/'` (domain is optional, just as path is). I.e. being able to change the `socket.io` path too and not just the domain. If there is no path you get the current behavior. `url.parse` parses `http://example.com` as having path `/` (so we must consider it no path), but that's not really a problem and preferable to avoid breaking existing configs.
If anyone wants to try it:
`"webpack-dev-server": "git://github.com/syranide/webpack-dev-server#socketiopath_npm"`
cc @sokra

Allow changing socket.io-path via query string

---

bin/webpack-dev-server.js

This adds a `--cert`, `--key` and `--cacert` option to the CLI. The option names are the same ones curl also uses, so I think that makes sense.
Fixes #235

Add --cert, --key and --cacert options to CLI.

---

client/index.js

'0.0.0.0' allows webpack-dev-server to bind to all addresses on the machine but cannot be navigated to so use window.location.hostname in this case

allow bind to all host (--host 0.0.0.0)

---

bin/webpack-dev-server.js

Tiny update to correct the console message when passing an `index` option to the historyApiFallback.
With the following config, the console message should say: *404s will fallback to /default.html*
```
// webpack.config.js
module.exports = {
devServer: {
historyApiFallback: {
index: '/default.html'
}
}
}
```

Correct console message for historyApiFallback

---

bin/webpack-dev-server.js
lib/Server.js
package.json

The --compress option uses the `compression` express middleware to gzip
compress responses from the dev server.
A development bundle for a babel + react project can easily be 1MB. I work on a remove development machine where I would take up to three seconds just to fetch the bundle. Gzip here makes a huge difference.

Add --compress option to enable gzip compression

---

lib/Server.js

Take two after #190, this time using the new fancy `features` object.
Example usage:
```js
devServer: {
//...
setup: function (app) {
app.use(function(req, res, next) {
res.cookie('my_fancy_cookie', {lorem: 'ipsum'}, {httpOnly: false})
})
},
},
```

Add setup option to prepend custom middlewares

---

lib/Server.js

The primary use-case behind this addition is to allow HTML5 history API support for proxied paths.
The example below uses the same pattern as the `historyApiFallback` URL rewriting code to avoid the extra behavior (proxying) when the request comes from a non-ajax browser request.
```
proxy: {
'/thepath*': {
target: 'https://otherserver.example.com',
bypass: function(req) {
if (req.headers.accept.indexOf('html') !== -1) {
console.log('Skipping proxy for browser request.');
return '/index.html';
}
},
},
},
```
I'm very option to suggestions for alternate implementations that make better reuse of the existing `historyApiFallback` code. I'm not very familiar with Express middleware yet.

Add option to bypass proxying requests based on a function call

---

lib/Server.js

Implements close as described in #249. I don't believe it's possible to support a callback since socket.io's close does not have a callback. Happy to add some tests though not sure how the are split up amongst the various webpack libraries.

add close() api

---

client/index.js

With my previous PR, #302, I broke the websocket connection for scripts that are not using the `--inline` option.
Fixes #326.

Fix websocket connection for non-inlined scripts

---

client/style.css

If the error text is too long, it now shows a scrollbar instead of overflowing out of the errors element, making the text unreadable (see issue #322).
Fixes #322

Show horizontal scrollbar in errors text

---

lib/Server.js

I am receiving the following error when trying to use the webpack-dev-server proxy:
cannot proxy to https://192.168.5.5/services/ (Hostname/IP doesn't match certificate's altnames:     "Host: localhost. is not in the cert's altnames: DNS:*.blah.com")
Chrome and Node.js both load the URL without error.
I think the core difference here is that [http-proxy defaults to rejecting unauthorized certificates](https://github.com/nodejitsu/node-http-proxy/blob/master/lib/http-proxy/common.js#L54), while Node.js allows [unauthorized certificates](https://nodejs.org/api/tls.htm) by default:
> rejectUnauthorized: If true the server will reject any connection which is not authorized with the list of supplied CAs. This option only has an effect if requestCert is true. Default: false.
Example usage, to …

Disable http-proxy certificate check

---

lib/Server.js
package.json

I've found that the configuration of the node-http-proxy (NHP) library doesn't allow for some basic use cases (including my own). For example, it doesn't seem possible (through configuration only) to proxy a request from `host1.com/api/user/1` to `host2.com/user/1`.
This PR changes the implementation to use the [http-proxy-middleware (HPM)](https://www.npmjs.com/package/http-proxy-middleware) library which is built on top of the original NHP, so all current configurations should work. The HPM library has a lot more configuration options available.
I have ported over `proxyOptions.bypass(...)`, but without a `proxy` object, there is no need for `proxyOptions.configure(...)` anymore.
Comments in the code can be removed on request, I wanted to make my intent clear. Cheers

Use http-proxy-middleware instead of http-proxy.

---

lib/Server.js

I ran into the same issue as in #348. When multiple sockets were added in 2dd3058746ea8ce9247726df616c8fd72c09c461, the `listeningApp` was no longer being closed by closing the server. The `close` method now explicitly closes the listening app when the server closes, thus closing the port and freeing the node process to exit gracefully (assuming it was shut down by something other than `Ctrl+C`).

Closing listeningApp when server closes

---

bin/webpack-dev-server.js

webpack has it via --watch-stdin, why this doesn't?

added --stdin flag to close on process exit

---

client/index.js

Fixes bug in socket url composing which produces incorrect url from `webpack-dev-server/client?<some_url>` entry if `some_url` has schema omitted or doesn't end with `/`.
For instance, for `webpack-dev-server/client?http://localhost:3000/` correct socket url is produced, but for both `webpack-dev-server/client?//localhost:3000/` and `webpack-dev-server/client?http://localhost:3000` produced urls are incorrect.
This PR fixes the issue, restores compatibility with v1.10.1 in which all the mentioned variants worked well and also restores conformity with the [docs](http://webpack.github.io/docs/webpack-dev-server.html#inline-mode).

fix socket pathname

---

bin/webpack-dev-server.js
package.json

This will open your default browser with the app url if you add the `--open` option to the CLI.
Fixes #311

Open default browser if --open option is given

---

bin/webpack-dev-server.js

I am currently using `webpack-dev-server` inside a docker container, this requires more control of the bind address and external public facing address to ensure it works.
To manage this I have added a flag which enables overriding of the ip address which is used in the `--inline` mode.
An example of this can be seen below, the server binds to `0.0.0.0` and the inline client uses `123.123.23.14`.
```
webpack-dev-server \
-d --hot --inline --display-reasons --display-error-details --history-api-fallback --progress \
--colors --port 8080 --host 0.0.0.0 --public 123.123.23.14
```
This provides a fix for #205

Added a flag for public ip to seed the inline frame.

---

lib/Server.js

Hello
This is a small but important PR that will allow us to have multiple sources as content base.
It opens a raft of development build features and solves masses of messy workarounds to achieve the same thing.
One typical example on how it would be used in a `webpack.config` is:
var WHITELABEL = 'visa';
config.devServer = {
contentBase: ['./public/common', './public/' + WHITELABEL]
}
In this example we are now able to separate `common` and `whitelabel` specific assets, externals and  sources cleanly in different folders - rather than having copies of all common files in each whitelabel folder.

Extend contentBase to support array with multiple sources.

---

client/index.js

Allow to use port from current page, the same way we allow to use hostname.
This is useful in setups where the webpack server is for instance in a docker container and doesn't know statically on which hostname and port it will be accessed from. It's already possible to use "0.0.0.0" as an address to use current page's hostname. I'm adding the same trick for the port.
The config should then look like this
"webpack-dev-server/client?http://0.0.0.0:0"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/webpack/webpack-dev-server/430)

Guess server's port from current page.

---

bin/webpack-dev-server.js

This pull request is associated with issue #417.
Webpack allows for a Promise instead of a config object, and this logic was missing from webpack-dev-server. This pull adds that same logic

Update webpack-dev-server to accept a promise

---

lib/Server.js

Proxy configuration was failing due to unknown variable 'target'. Should be 'context' instead, I assume.

correct proxy options

---

lib/Server.js

Issue #327 (Expose a way to pass params for `express.static`)

add `staticOptions` for expose express.static options pass in

---

client/style.css

Currently, my web application is getting rendered on top of the build errors/warnings, preventing me from seeing them. This CSS change seems to fix it.

Prevent application from covering up webpack errors

---

client/index.js

Previously the clientside application would reload whenever a proxy answered with an error response
or in other ways behaved badly. This change removes that reloading behavior, as reloading the clientside
application probably won't fix any issue the proxy has anyway.
/ping @SpaceK33z as he made these socket handlers in the first place
Refs https://github.com/webpack/webpack-dev-server/issues/446

Don't reload app upon proxy errors.

---

client/index.js

Forces use of https protocol when window.location.protocol is https
This is useful in cases when the server is behind https proxy, and shouldn't break anything since browsers block http access from https page anyway.
see https://community.c9.io/t/mixed-content-with-webpack-dev-server/3053/3

Allow running dev-server behind https proxy

---

bin/webpack-dev-server.js
lib/Server.js

I currently have to mess around with `entry` manually as I want `only-dev-server`. This allows me to just add the options, or cli flag.
current:
```js
entry: [
'webpack-dev-server/client?http://0.0.0.0:3030',
'webpack/hot/only-dev-server',
origConfig.entry
],
devServer: {
host: '0.0.0.0',
port: 3030,
hot: true,
},
```
wanted: 
```js
devServer: {
host: '0.0.0.0',
port: 3030,
hotOnly: true,
inline: true
},
```
Ideally I'd PR this into `webpack-dev-server@1` (as IE8 support is dropped, we'll probably never upgrade), but there doesn't seem like there's a branch for it.

Add hot-only option to allow setting `only-dev-server` from cli or config

---

lib/Server.js

Hey @sokra,
currently the headers are only set on GET responses. It would be great to also set them on at least OPTIONS as well to support e.g. CORS. My solution is to set headers on all methods supported by express.
Please also backport this to 1.x
cc: @mischi

set headers on all methods to support e.g. CORS

---

bin/webpack-dev-server.js

The `--cacert` CLI argument was being mapped to `options.cacert` which is never actually used in _Server.js_.
The correct property name is `options.ca`. In order to preserve documentation & backwards compatibility for any existing users currently passing the the `--cacert` flag, I've left the flag the same but mapped it to the `options.ca` property so that it gets passed to the `createServer` call.

Assign --cacert CLI argument to correct server options property

---

lib/Server.js

Return the `http.Server` instance from `listen` to [match the return value of the same function in express](https://github.com/expressjs/express/blob/31dd549f350accd7b4e3685c13f745e857557827/lib/application.js#L617).

Return http.Server instance from listen

---

lib/Server.js

The `bypass` feature was no longer working because the code added the bypass method as middleware AND `httpProxyMiddleware` as middleware. However, if a `bypass` method is given, it should only use that as middleware.
This was caused in #359, and effects `1.15.0` and the 2.x branch.
For now, this is based on `1.15.0`, because the people that reported issues with this are using that version. It should be merged to `master` too.

Fix bypass proxy middleware

---

client/index.js

Just as title says.
This is a cheery-pick from master branch.

Avoid accessing `document` if `__resourceQuery` is defined

---

client/index.js

`document.scripts` preserves script-addition order, so we can add scripts in the HEAD as well as BODY.
Currently using `getElementsByTagName` fails if the script is placed in the HEAD.
EDIT: This is nicely discussed [here](http://www.2ality.com/2014/05/current-script.html), where the author mentions (discussing the `getElementsByTagName` alternative):
> There are two situations where this snippet will fail, though. When a script is loaded asynchronously using `<script async>`, the order of script execution is uncertain. Therefore the `document.getElementsByTagName()` trick will not work, as it relies on the currently executed script being the last of that collection. __The same holds true for `<script>`s that are not appended to the end of the document__. In the future this might become …

Use 'document.scripts' instead of document.getElementsByTagName

---

bin/webpack-dev-server.js
client/index.js
lib/Server.js

Previously, when you used `quiet: true` or `noInfo: true` via the Node API or CLI, this only had effect on the output in the terminal (issue #109).
With this PR, these settings will be respected in the browser console as well.
Maybe it would be more flexible to add a separate option for this, but this would also mean more configuration. Looking for feedback on this.

Add option to control browser log level

---

bin/webpack-dev-server.js

#598 fixed a bug where the `contentBase` from the webpack config was ignored in the CLI. However, there were more issues.
The default value according to `--help` is the PWD. This is not true. If `contentBase` is set in the webpack config, this default value is ignored.
Yargs will not incorrectly display the default value of `--content-base` now.
Originally I intended to add an error message when `contentBase` was set from the config AND from the CLI, but this would be inconsistent with all other options. The config always gets preference.

Don't use PWD as a default for --content-base in yargs

---

lib/Server.js

I don't quite understand how the files are serving, specifically why files on top level served fine while nested are not.
For example, i had follow sctructure:
```
/public
/userpics/pic1.jpg
index.html
userpic.jpg
```
With config
```
devServer: {
contentBase: 'public',
}
```
`GET /userpic.jpg` => `/public/userpic.jpg`
`GET /userpics/pic1.jpg` => `/public/userpics/pic1.jpg`
After adding `historyApiFallback: true` to config
`GET /userpic.jpg` => `/public/userpic.jpg`
`GET /userpics/pic1.jpg` => `/public/index.html`
But swaping `defaultFeatures.push("contentBase");`  and `defaultFeatures.push("historyApiFallback", "middleware");` fixes it.

Fix historyApiFallback for nested paths

---

bin/webpack-dev-server.js

`webpack-dev-server --help | grep live` doesn't help me, and `webpack-dev-server --help | grep reload` doesn't help me.
Both `webpack-dev-server --help | grep live` and `webpack-dev-server --help | grep reload` help me

CLI: Describe that `--inline` toggles livereload

---

client/index.js

Backport fix in PR #594 to Webpack 1 branch.

backport fix for https and add null check

---

examples/proxy-hot-reload/README.md
examples/proxy-hot-reload/app.js
examples/proxy-hot-reload/index.html
examples/proxy-hot-reload/proxy-config.js
examples/proxy-hot-reload/webpack.config.js
lib/Server.js

Dev server is not supporting hot reloading for proxy config
Enables hot reloading for proxy config. If function is provided instead of
object, dev server calls it on each request to get proxy config and replaces proxy middleware if config was changed.

Proxy config hot reloading

---

.gitignore
client/sockjs.js
client/webpack.sockjs.config.js
lib/Server.js
package.json

Fixes #474 "Incompatibile SockJS" (appears when using iframe mode)

Serve sockjs.js from sockjs-client dependency, don't use default from CDN

---

lib/Server.js

Even with `clientLogLevel: 'none'`, I see `[WDS] Hot Module Replacement enabled.` in the console.
Client log level is respected for `[WDS] Hot Module Replacement enabled.`.
I would appreciate backporting this fix to 1.x.
Alternatively if you could give me commit access, I could backport it myself.

Emit 'log-level' event before 'hot' event

---

lib/Server.js

See #612 
If this PR contains a breaking change, please describe the following... 
* Github Issue(s) this is regarding: #612
added additional `middleware` feature to express' use-chain after proxy to enable proxy-bypass retrievals to in-memory resources. Fixes #612.

fix for #612

---

lib/Server.js
test/HistoryApiFallback.test.js

fixing broken historyApiFallback, with this one - tests are passed and we can use custom index or rewrites property of historyApiFallback

fix for #625 broken historyApiFallback

---

client/index.js

https://github.com/webpack/webpack-dev-server/issues/628
Use `self` instead of `window`.
Should be no difference in functionality, `window` and `self` is essentially the same thing in UI thread. https://developer.mozilla.org/en-US/docs/Web/API/Window/self.
I have setup a repo which replicates the error here https://github.com/oskarer/webpack-dev-server-webworker-test

Fix for web worker support

---

bin/webpack-dev-server.js
lib/Server.js

It is not possible to provide a pfx file as supported by [https.createSearver](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) 
It will be possible to provide a pfx file, either by passing a commandline argument --pfx and --pfx-passphrase that will pass it on to https.createServer.
This is for webpack 1 dev server.I'll add a seperate PR with similar functionality for webpack 2 web server.

Add support for pfx files as ssl connection options [webpack-1]

---

lib/Server.js

Low-impact bug fix that prevents an edge case where null is passed (and consequently aborts the server, which is the current behaviour) on a new connection if all handles are occupied.
I am able to reliably trigger this by rapidly refreshing on a page in development.

sanity check that conn exists on connection

---

package.json

(example already present in https://github.com/webpack/webpack-dev-server/blob/master/examples/history-api-fallback/webpack.config.js)
Currently, `webpack-dev-server` is requiring `connect-history-api-fallback@^1.2.0` which might resolve to `1.2.0` on existing installs. 
This version doesn't yet allow for the `disableDotRule` option enabled in https://github.com/bripkens/connect-history-api-fallback/commit/ee8611164c4a06ed87d7b98b16dedb89f60ff3a3.
Using the following in the Webpack Dev Server config works only when `connect-history-api-fallback@1.3.0` is installed:
```
historyApiFallback: {
disableDotRule: true, …
```

Update connect-history-api-fallback to enable disableDotRule use

---

bin/webpack-dev-server.js

- [ x ] Bugfix
If this PR contains a breaking change, please describe the following... 
* Impact:
* Migration path for existing applications: 
* Github Issue(s) this is regarding:
This supports ipv6 ip addresses.

Use url.format to generate URI

---

bin/webpack-dev-server.js
client/index.js
examples/watch-content-base/README.md
examples/watch-content-base/app.js
examples/watch-content-base/assets/index.html
examples/watch-content-base/css/styles.css
examples/watch-content-base/webpack.config.js
lib/Server.js
package.json

Currently, if a file changes under the content-base, nothing happens. #350 
With the `--watch-content-base` option, file changes in the content-base will trigger a full reload. 
Fixes #350. If/when this gets merged. We should update the official docs.

Add watch-content-base option

---

bin/webpack-dev-server.js
examples/listen-socket/README.md
examples/listen-socket/app.js
examples/listen-socket/check-socket.js
examples/listen-socket/webpack.config.js

**What is the current behavior?**
#659
It's possible to pass socket path as port param but it won't correctly handle access rights (chmod) to socket and `EADDRINUSE` errors.
New option `--socket` added. It overrides port if present and adds additional handling to listen:
- If connection is successful, then it works like before
- If connection is failing (with `EADDRINUSE` error) then socket file is already present. In this case, we're trying to connect to that socket file.
- If connection is successful, then socket is already used by some other server and current instance of webpack-dev-server stops
- If connection failed, then socket is not used by other …

Option for listening to unix socket

---

bin/webpack-dev-server.js
client/index.js
examples/host-port/README.md

#672 
#673 
works with ipv6 publicly!
and add doc to `host-port`.

Fixed ipv6 [::]

---

bin/webpack-dev-server.js
package.json

Addresses #683.
I'm not sure about a new example - is there an easy way to verify that two webpack dev servers are running simultaneously at expected ports? *ETA: I imagine this could be tested via a SharedWorker or the localStorage polyfill that does the same thing - allowing two browser tabs to talk to one another. But a system-level test maybe would be better?*
As for docs, if it's important to document the use of `portfinder` on the wiki I can do so as soon as the PR is merged.
Because `portfinder` is async, `startDevServer` had to be spun out into a new function.
Only in the sense that if two dev servers are run with no port config, one …

CLI finds and uses 1st available port when none specified.

---

client/index.js

The data passed to `sendMsg` contains ANSI escape code, which is probably never used by the browser users.
Those escape code are stripped.
If this PR contains a breaking change, please describe the following... 
* Impact:
* Migration path for existing applications: 
* Github Issue(s) this is regarding:
Previous context in #481 
I run the code with my demo and it worked. No further checking.

strip ANSI code before sending the message

---

lib/Server.js

Bugfix.
No.
**Summary**
When there is a proxy configuration object which includes the bypass property but does not include the target property, the response is never sent back to the browser.
This is a regression from version 1.16.2.
No.

(fix) proxy config with bypass and without target

---

bin/webpack-dev-server.js

Backports the fix in #419 to webpack-dev-server v1 since v1 of Webpack itself supports config as Promise. Change looks more complex than it really is, it's just because a lot of code is getting wrapped in a function.

Backport support for configuration as Promise in Webpack v1

---

bin/webpack-dev-server.js

This changes the behavior of the --open flag to open the browser to the --public url if it is specified. (the default will be the host like before).
The original issue is #739 , though it will also address #725 by letting you specify localhost as the --public url.
This is not a breaking change.
This is also addressed for version 1 with #748

have --open use the options.public path if it exists

---

lib/optionsSchema.json

Bugfix
N/A
**Summary**
Since the new config validation, only integers are accepted for the `port` option. See #761.
No
Fixes #761

Allow a string to be passed as the `port` config option

---

client/index.js
client/overlay.js
examples/overlay/README.md
examples/overlay/app.js
examples/overlay/index.html
examples/overlay/webpack.config.js
lib/Server.js
lib/optionsSchema.json
package.json
test/Validation.test.js

Feature
Yes
**Summary**
This adds an error overlay in the browser, like create-react-app has. It works very much like create-react-app's error overlay. In fact, I copied much code from it 😅 .
I asked on Twitter if people would [like this feature](https://twitter.com/keeskluskens/status/825008478536228865), and ~~everyone forgot Trump for a while~~ people were happy.
The error overlay is only enabled when you add the option `overlay: true` in your `devServer` config. It could be enabled by default, but that would kinda be a breaking change so *maybe* in v3.
Furthermore, it will only show errors, not warnings. I'm not sure yet if we should display warnings the same way. If we would do that, there also …

Implement error overlay

---

bin/webpack-dev-server.js

bugfix
No
**Summary**
The dev server uses `opn` to open the browser, which returns a promise. In headless environments, this call will fail and the promise will be rejected. Since node v6.6.0, a `UnhandledPromiseRejectionWarning` will be output when a rejected promise has no handler.
This PR adds a `.catch` handler and outputs a user friendly message that the browser could not be opened, and not to use the open flag in headless environments.
No
None

Handle `opn` promise rejection

---

client/index.js
client/overlay.js
examples/overlay-warnings/README.md
examples/overlay-warnings/app.js
examples/overlay-warnings/caseSensitive.js
examples/overlay-warnings/index.html
examples/overlay-warnings/webpack.config.js
lib/optionsSchema.json

Feature.
Yes.
**Summary**
Now you can use
```javascript
{
overlay: {
errors: true,
warnings: true
}
}
```
Closes #789.
No.

feat - Allow overlay to be enabled for warnings (#789)

---

bin/webpack-dev-server.js
lib/Server.js
lib/util/addDevServerEntrypoints.js
lib/util/createDomain.js

This is a refactoring and adds a new feature.
No
**Summary**
It adds a new static method `addDevServerEntrypoints()` to the exports. This method could be reused in alternative implementations like the grunt plugin instead of[ copying the code](https://github.com/webpack-contrib/grunt-webpack/blob/master/tasks/webpack-dev-server.js#L43-L60).
no

Export logic of adding entry points to webpack config

---

lib/Server.js
test/HistoryApiFallback.test.js

bugfix
No need I think?
**Summary**
I opened an issue and was asked for a pull request!
Nope.
Connected to issue #791

Setting contentBase to false with historyApiFallback on works properly #791

---

lib/util/addDevServerEntrypoints.js

devClient does not work with dynamic entry.

---

client/index.js

a bugfix
now,it can  work well without errors.
**Summary**
this bug happened because we use `iframe.postMessage` to communicate with other window.But unfortunately, in the `Worker` there is also a method called `postMessage`,they have diffrent function signature.
#745  #792 
it's a not easy journey

a bugfix for issue #745 ,webworker error

---

lib/Server.js
test/Proxy.test.js

a bugfix
No
**Summary**
Currently, `webpack-dev-server` mutates the proxy options, which is a cause of bug when the proxy options share a same option object.
For an instance, the following option creates different results after this PR.
* A proxy option
```js
const proxyTarget = {
target: "http://localhost:9000"
};
proxy: {
"/proxy1": proxyTarget,
"/proxy2": proxyTarget,
}
```
* Before this PR
```
[ { target: 'http://localhost:9000',
context: '/proxy2',
logLevel: 'warn' },
{ target: 'http://localhost:9000',
context: '/proxy2',
logLevel: 'warn' } ]
```
* After this PR
```
[ { target: 'http://localhost:9000',
context: '/proxy1',
logLevel: 'warn' },
{ target: 'http://localhost:9000',
context: …
```

Fix to share proxy option between proxy settings when the proxy option is a same object

---

lib/Server.js
package.json
test/Proxy.test.js

This change upgrades websocket proxies so that an inital http request doesn't have to be made.
https://github.com/chimurai/http-proxy-middleware#external-websocket-upgrade
It supports a proposed change in Create React App by handling the upgrade of any websocket proxy passed in. facebookincubator/create-react-app#1790
I added a test to confirm the upgrade

Handle external upgrade for all websocket proxies

---

client/index.js

Bugfix
No
**Summary**
This fixes #544. In Firefox on Linux and Mac, with a slow proxied server (> 1s), when the page is refreshed (or the server refreshes is for a code change), the web socket reconnection timeout triggers, which causes the webpage to reload (again), causing a loop. This code adds a `beforeunload` event check, so that the reload doesn't happen if the page is already refreshing.
I wouldn't not expect this to cause a BR break, but I'm not super familiar with webpack-dev-server's official API.
This is a naive implementation that just fixes the problem for my limited test case. For example, this would throw in browsers …

Added beforeunload check to index.js (#544)

---

lib/Server.js
test/Validation.test.js

2.4.3 introduced checking of the host header and options for setting the public host however when parsing the publicHost it was still using the index of `:` from the host header hostname. This corrects that.

Use correct index when parsing publicHost

---

lib/Server.js
lib/optionsSchema.json
test/Validation.test.js

feature/bugfix
no
**Summary**
Host checking was added by default in v2.4.3 for security reasons. Users now have to specify the host/URL being used to access the dev-server [more info here](https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a) 
This PR allows users to specify multiple hosts that that will pass the check. Recommended by @edmorley here: https://github.com/webpack/webpack-dev-server/issues/882#issuecomment-296799201
no
**Example usage in webpack config:**
```js
devServer: {
allowedHosts: [
'exampleHost.com',
'differentExampleHost.com',
...
]
}
```
**subdomain wildcard:**
mimicking django's `ALLOWED_HOSTS`, a …

Add 'allowedHosts' option

---

client/index.js

**What kind of change does this PR introduce?** bugfix
**Summary**
Fix #745 again.
For some reason I've defined `self.window` in WebWorker, so #813 still doesn't fixed for me.

Strongly check client isn't running on WebWorker for sendMsg

---

package.json

Now that webpack 3 is out, I am bumping some versions in here
so folks can update. I don't know if any other changes are required
but I figured I'd get the ball rolling.
Addresses #932 
Updating dependencies
No
**Summary**
I'd like to help unblock people who are using webpack-dev-server so they can update to webpack 3.
No
This may need additional work, but I figured I'd get the ball rolling.

Update to webpack 3

---

package.json

Updates sockjs-client to 1.1.4
n/a
**Summary**
There is a similar issue a few months ago to this (https://github.com/facebookincubator/create-react-app/pull/1274)
I can not use websockets and the clients mismatch. 
No

Updated sockjs-client to 1.1.4

---

client/index.js
package.json

Removes console calls with internal log function which respects clientLogLevel configuration values.
Moves warnings and errors to the warning and error logs, respectively. Also utilizes constants for fewer string comparisons.
Resolves issue #855

Browser console messages should respect clientLogLevel

---

bin/webpack-dev-server.js

This fully mutes all startup messages if quiet is set.
This follows #970 and fully mutes all startup messages if quiet is set instead of just half.
No
**Summary**
Fully mutes all messages following https://github.com/webpack/webpack/issues/1191 and #970.
This fixes issues on our build runners where stdout was outputted from the build even with `quiet` set.
No

Fully mute output info if quiet is set to true

---

lib/Server.js
package.json
test/Validation.test.js

enhancement
no.
**Summary**
This patch will allow any requests made using an IP-address to always pass the
checkHost-test.
IP-addresses are not susceptible to a dns-rebind like attack so it would make
sense to not block them to make local-network development possible without
needing to disable the host-checks entirely.
no
fixes #931

Always allow requests with IP-address as host in checkHost()

---

bin/webpack-dev-server.js

feature
no
**Summary**
adds the ability to set the [allowedHosts option](https://github.com/webpack/webpack-dev-server/pull/899) via the CLI
no
**Usage**
I'm not sure what the best practice is for passing a list as a command line option. I opted for a comma delimited string. E.G.
```
webpack-dev-server --entry /entry/file --output-path /output/path --allowed-hosts host1.com,.host2.com
```
creates the option
```
allowedHosts: [
'host1.com',
'.host2.com'
] 
```
Please let me know if there is a better way to do this.

add --allowed-hosts CLI option

---

lib/Server.js
test/Validation.test.js

bugfix
no
**Summary**
Add proper handling of IPv6-addresses to the checkHost()-method. Like
IPv4-addresses, IPv6 addresses are always allowed.
no
Addresses @trygveaa's comment: https://github.com/webpack/webpack-dev-server/pull/1007#discussion_r131589051

Handle IPv6-addresses correctly in checkHost()

---

lib/Server.js

Small startup time optimization
**Summary**
Skip the generation of a self signed SSL cert if an existing cert is already specified in the https options. The self signed SSL cert never gets used if you specify a cert in the options anyway, so theres not much point generating it in this case
No 

No longer generating ssl cert when one is already specified

---

bin/webpack-dev-server.js
lib/util/createDomain.js

Feature and Fix
No need
**Summary**
#998 requested the use of random ports and the ability to access the assigned random port. 
It introduces a corrective change. This PR also corrects the port reported by the CLI when a random port is assigned.
To access the port assigned [you may go off of this example](https://github.com/webpack/webpack-dev-server/blob/random-port-access/bin/webpack-dev-server.js#L436), or the following sample code:
```js
const Server = require("webpack-dev-server/lib/Server");
conast server = new Server(compiler, options);
server.listen(0, '127.0.0.1', () => {
const port = server.listeningApp.address().port;
}); …
```

Addresses #998 to properly assign a random port and access the port assigned

---

bin/webpack-dev-server.js
client/index.js
lib/Server.js

Bugfix
No need
**Summary**
#1059 exposed a situation in which the sockjs url for clients with custom/random ports would result in the client using an erroneous url that either omitted the port or used the wrong (default 8080) port. This resulted in socket communication breaking, which was noticed by way of the lack of an overlay being displayed.
This fix does the following:
1. in `Server.js` the socket server won't be initialized nor started until the `listeningApp` triggers the callback on `listen`. That's really the proper time for the socket server to be initialized anyhow. polyfills dep is also moved to the top to match `bin/webpack-dev-server.js`.
2. in `client/index.js` the port parsing is …

Fix Broken Socket on Client for Custom/Random Port Numbers

---

lib/Server.js
lib/optionsSchema.json
test/Validation.test.js

Add this configuration flag to request a client's certificate for 2-way PKI authentication.
Issue #1011
The motivation for this feature proposal is to allow create-react-app to enable the instance of webpack-dev-server to request the client certificate for 2-way PKI auth.
The issue actually doesn't lie in webpack-dev-server itself (configuration is much easier when using webpack-dev-server by itself), but rather that create-react-app only sends a boolean to webpack-dev-server. Here is the line I am referencing: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpackDevServer.config.js#L81
From what I can tell, this means that the configuration options for webpack-dev-server are limited to the key, cert, ca, and passphrase when using …

Add requestCert support to the server

---

client/index.js

bugfix
no
**Summary**
This solves issue #1064 
So far, the client JS of webpack-dev-server used the root logger and also changed the configuration of the root logger. This results in webpack overwriting the application's logging configuration.
The PR switches to a named logger, as suggested in the issue description.
I don't think it could break an app.
However, if an application uses loglevel and expects webpack-dev-server to configure the root logger, it might have an different log level than expected. 
The solution for the app would be to call [loglevel's `setLevel `or `setDefaultLevel`](https://github.com/pimterry/loglevel#documentation) (which is how …

Fixes issue #1064 by switching to a named logger

---

client/index.js

Feature
No, but you could use any sample and use the queryParam : `?disableAutoreload=true` to 
**Summary**
See corresponding issue : https://github.com/webpack/webpack-dev-server/issues/936
This option can be used if you want to use the same platform for developping and to run automated tests (the tests should not be impacted by a code change whenever they are running). 
No

Add feature to disable hotReloading with query string

---

lib/Server.js

fixes issue with reconnect on Chrome 58+
#941
#941

include `subjectAltName` field in self-signed cert

---

lib/Server.js

Quotes fix.
Not needed.
**Summary**
Double quotes in `Server.js` made eslint fail (strangely enough, only in node 4 and 6).
No.

Fix quotes

---

client/overlay.js

Error overlay translucence.
Not needed.
**Summary**
Being used to `webpack-hot-middleware`'s error overlay, which has an [alpha of 0.85](https://github.com/glenjamin/webpack-hot-middleware/blob/master/client-overlay.js#L6), it is a bit misleading when getting a completely opaque overlay. This change makes the error overlay's background the same as `webpack-hot-middleware`'s.
No.

Make error overlay translucent

---

client/index.js

Bugfix.
Not needed.
**Summary**
Some time ago I authored [PR #926](https://github.com/webpack/webpack-dev-server/pull/926). Which, strangely enough, caused [issue #1049](https://github.com/webpack/webpack-dev-server/issues/1049).
The original code was
```js
var hotCtx = require.context("webpack/hot", false, /^\.\/log$/);
if(hotCtx.keys().length > 0) {
hotCtx("./log").setLogLevel(level);
}
```
Somehow I was under the impression that `hotCtx.keys()` can only return `[]` or `["./log"]`, and with this assumption, the check `hotCtx.keys().length > 0` is correct. For some strange reason, as per issue #1049, it returned `["../package.json", "./console", "./formatters"]`, which doesn't match the regex at …

Fix check for webpack/hot/log when setting HMR log level

---

examples/node-api-middleware/server.js
lib/Server.js
lib/optionsSchema.json
test/Validation.test.js

feature
yes, `examples/node-api-middleware`
**Summary**
fixes #869
Not a breaking change, but a deprecation.
see #869

feat: deprecate setup in favor of before and after hooks

---

lib/optionsSchema.json
test/Routes.test.js

This PR removes property validation for header properties.
bugfix
No changes were necessary.
**Summary**
The validation that was being used before this PR was preventing multiple cookies from being set (Set-Cookie), or multiple domains being used (Access-Control-Allow-Origin). The 'http' server supports strings or arrays, so this validation was preventing this functionality from working.
https://github.com/webpack/webpack-dev-server/issues/964
No

Remove header property value validation

---

client/socket.js
examples/node-false/README.md
examples/node-false/app.js
examples/node-false/index.html
examples/node-false/webpack.config.js
test/fixtures/simple-config/webpack.config.js

Bugfix
Yes.
**Summary**
`webpack-dev-server` bundles `sockjs-client` from source. `sockjs-client` sources assume a node environment however, and will fail to run if `global` is not available.
By bundling `sockjs-client` from source, the node environment requirement from `sockjs-client` will also be required of the app being served and thus it is not possible to have `node.global = false` in the user app being bundled.
This fix uses the built `sockjs-client` instead of the sources.
No.
Fix https://github.com/webpack/webpack-dev-server/issues/1147

Use built version os `sockjs-client`

---

bin/webpack-dev-server.js
package-lock.json
package.json
test/cli.test.js

Properly calls `process.exit` only after `server.close` has completed. Probable fix for reported edge case whereby the server process doesn't actually exit when SIGINT is sent.
No need
**Summary**
See above
No
Added new test to confirm SIGINT detection works properly.

fixes #860: failure to exit on SIGINT race condition

---

package.json

Use `https` instead of `http` URL to Github.

Fix https in homepage url

---

lib/Server.js

There is a problem when watchOptions is set to undefined in the options object. this.watchOptions is then set to undefined. We want an empty object so we can check poll property later.
bugfix
No.
**Summary**
[Edge Case Issue](https://github.com/webpack/webpack-dev-server/issues/1217)
When Server(compiler, options) - options object looks like this:
```
{ 
...
watchOptions: undefined,
...
}
```
this.watchOptions will be set to undefined. 
```
this.watchOptions = options.watchOptions
```
These lines will give raise to the error specified in the issue request.
```
const usePolling = this.watchOptions.poll ? true : undefined; // eslint-disable-line no-undefined
const interval = typeof …
```

fixes #1217: edge case with default watchOptions value

---

cli.js
package-lock.json
package.json

I actually think this is sufficient, because any time you make a require call for webpack, it will redirect to the cli. This way, avoid extensive refactor/complicated nesting of dependencies. The only thing that needed change was the arg path

Rebase cli

---

lib/optionsSchema.json
test/Validation.test.js

feature
**Summary**
`webpack-dev-middleware` have option `reportTime`, but i can't setup this option using `webpack-dev-server`
No
No

feat: `reportTime` option

---

client/socket.js

bug fix on iOS Safari 10 (iOS 10)
No, not applicable, no API changes
**Summary**
Fixes iOS Safari 10 bug. At the root, this works around a bug where Safari's eval's scope was getting confused.  Something to do with [this issue](https://stackoverflow.com/questions/46036960/evaluated-expression-const-variable-scope-in-safari)
[bug reference](https://github.com/webpack/webpack-dev-server/issues/1090#issuecomment-352537184)
No
No

iOS Safari 10 bug where SockJS couldn't be found

---

package-lock.json
package.json

Follow up for https://github.com/webpack/webpack-dev-server/pull/1270#issuecomment-357514454
`strip-ansi` which is required by the clients, uses ES6 syntax. Pinning it to 3.x keeps ES5 compat. ([The only difference between 3.x and 4.0 is the syntax change](https://github.com/chalk/strip-ansi/commits/master))

fix: pin strip-ansi to 3.x for ES5 compat

---

lib/util/addDevServerEntrypoints.js
test/Entry.test.js

Yes
Fixes this issue https://github.com/webpack/webpack-dev-server/issues/1308
Allows for `webpack-dev-server` to run with no config or no configured entry point, keeping the behaviour consistent with the webpack compiler.
This should eventually be moved out of `webpack-dev-server` as we've currently got two places setting the default entry point (this and `WebpackOptionsDefaulter`).

Allow no publicPath or entry point

---

lib/util/addDevServerEntrypoints.js
test/Entry.test.js

Yes.  I have added tests for this change and I have added new tests for prior behavior to prove that this doesn't break anything.
The support for DynamicEntryPlugin added in #802 was incorrect.  This fixes `addDevServerEntrypoints.js` as it applies to dynamic endpoints (functions which return an entry object and functions which return a Promise)
none.
This pull request targets the `webpack-4` v3.x branch, but I would like to port this back to `2.x` as well if you plan to make any more releases under that major version.  The only conflict would be the default entry point added in #1310.  I could simply exclude that behavior from this change and open up a separate PR targeting the master branch.
Closes: #1318

Fix support for DynamicEntryPlugin

---

client-src/default/index.js

I did not.  I absolutely want to, but it appears that the `client-src/default/index.js` file has no tests at the moment.  Or if it does, I couldn't find them in the `test` directory.
I would really love some help and/or guidance on how best to test this code.
See #1316 for the bug this addresses.
There's a _possibility_ that this could cause unnecessary reloads in other situations.  I don't think it will, but I'm not 100% sure it won't, especially since this bit of code doesn't seem to have any tests right now.

Fix issue #1316

---

client-src/live/index.js

Nope, is typo.
The live client was [refactored](https://github.com/webpack/webpack-dev-server/commit/a02c0839fb50b59fee089f19d3e18e3c6e603695#diff-6b9850aa6ec84dd7b01865bf903ec26b) and migrated from the [pug-loader](https://github.com/pugjs/pug-loader) to the [html-loader](https://github.com/webpack-contrib/html-loader).  The `pug-loader`, I assume, returns a function, whereas the `html-loader` returns a string.  
You get this abstract error and the page completely fails to load:
```
jQuery.Deferred exception: n(...) is not a function TypeError: n(...) is not a function
at HTMLDocument.<anonymous> (http://0.0.0.0:3000/__webpack_dev_server__/live.bundle.js:1:163209)
at c (http://0.0.0.0:3000/__webpack_dev_server__/live.bundle.js:1:105849)
at l …
```

Live bundle not loading, typo during migration

---

bin/webpack-dev-server.js
lib/Server.js

no
`Tapable#apply` is deprecated so I removed the calls.
no
No more deprecation notice about `Tapable#apply`

Remove Tapable#apply calls

---

lib/Server.js

There's no need to add tests, as it is just a configuration change to toJSON
The stats.toJSON call is done every time an incremental build finishes. Given a sufficiently large codebase, this is very SLOW (my repo went from ~30s to ~10s just by getting rid of this)
None

speed up incremental builds by not doing excessive stats.toJSON work

---

package-lock.json
package.json

Spaces in the `outputPath` are not being handled correctly on Windows.
This change addresses the regression which introduced the bug and is being tracked in https://github.com/webpack/webpack-dev-server/issues/1375
The only change made is that the `package.json` has been updated to reference v3.1.3 of webpack-dev-middleware. 
The issue was corrected here:
https://github.com/webpack/webpack-dev-middleware/issues/297

update webpack-dev-middleware dependency to v3.1.3

---

lib/optionsSchema.json

No
I tried to use webpack-dev-server with {logLevel: 'silent'} option, but it fails with the following error
```
WebpackDevServerOptionsValidationError: Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
- configuration.logLevel should be one of these:
"trace" | "debug" | "info" | "warn" | "error" | "none"
```
That happens because the options schema defines an incorrect 'none' value, while webpack-log expects the 'silent' value.

Fix options schema inconsistency for `logLevel`

---

lib/util/addDevServerEntrypoints.js
test/Entry.test.js

This PR solves an issue in projects that use yarn workspaces, in which there are two different versions of `webpack` get installed:
```
yarn list webpack
├─ webpack@3.11.0
└─ package-A@1.0.0
└─ webpack@4.1.1
```
In that case when package-A starts a webpack-dev-server the webpack client scripts appended to the entry scripts are resolved against project root that gets resolved to webpack@3.11.0, which is a different version of webpack that is required by package-A

Fix path to webpack client hot reload scripts to be resolved relatively

---

package-lock.json
package.json

N/A - the bug is not in webpack-dev-server but a dependency.
If the response to `sockjs-client` times out, there is a bug in version 1.1.4 that will start an infinite reconnection. We are able to reproduce this timeout and infinite reconnect scenario in webpack-dev-server particularly when we have gzipping enabled and are bundling a really large JS file.
You can read more about the issue here: https://github.com/sockjs/sockjs-client/issues/334#issuecomment-280866701
And upgrading to v1.1.5 will fix it as per this PR: https://github.com/sockjs/sockjs-client/pull/358
N/A
N/A

Update sockjs-client to 1.1.5

---

client-src/default/index.js

One line change.
Context: we maintain a module that shows a webpack status bar on the browser page. It handles ok, error, status e.t.c messages but since progress isn't sent out we can't respond to that.
https://github.com/mixpanel/webpack-dev-server-status-bar
The goal is to make the bar respond to progress by showing a fixed bar on top that increases in width as progress increases. For this to happen webpack-dev-server needs to send the event via `postMessage`

sendMsg('Progress', data)

---

examples/cli/open-page/webpack.config.js

Otherwise is returning  an _Html Webpack Plugin_ error:
```
Error: Child compilation failed:
Entry module not found: Error: Can't resolve '/(...)/webpack/webpack-dev-server/examples/assets/layout.html
```
Trying to test the `--open` behaviour, first approach is to check the _example_
and seems broken finding a wrong `path`.

fix(examples/cli): correct template path in `open-page` example

---

bin/webpack-dev-server.js
lib/Server.js
lib/polyfills.js
package-lock.json
package.json

`Array.prototype.includes` should be native in all versions of `node` that `webpack-dev-server` currently supports.
Code coverage drops, but only because there are less lines of code.
I have no idea why `package-lock.json` changed so much.  Do you want me to uncommit it or something?

refactor(package): drop `array-includes` (`dependencies`)

---

bin/webpack-dev-server.js
test/cli.test.js

fix(bin): handle `process` signals correctly when the server isn't ready yet

---

bin/options.js
bin/utils.js
bin/webpack-dev-server.js

refactor(bin): move options and helpers into separate files

---

lib/utils/createLogger.js

Doesn't look like `logLevel` is currently tested, aside from validation. Also not sure how to test this~
Setting `noInfo` and `quiet` to `true` still reported errors (and warnings), despite the fact that `quiet` should silence everything.
N/A
Screenshot includes `wdm` error message. Also displaying the full `devServer` config above it.

fix(utils/createLogger): ensure `quiet` always takes precedence (`options.quiet`)

---

lib/options.json
test/Validation.test.js

According to https://github.com/webpack/webpack-dev-middleware#watchoptions
Yes
Closes https://github.com/webpack/webpack-dev-server/issues/1357
None

fix(options): add `writeToDisk` option to schema

---

package-lock.json
package.json

N/A - the bug is not in webpack-dev-server but a dependency.
Incorrect parsing in url-parse <1.4.3 returns wrong hostname which leads to multiple vulnerabilities such as SSRF, Open Redirect, Bypass Authentication Protocol.
Please refer https://nvd.nist.gov/vuln/detail/CVE-2018-3774 for further details.
NA
NA

fix(package): update `sockjs-client` v1.1.5...1.3.0 (`url-parse` vulnerability)

---

lib/Server.js

The default value of tls.DEFAULT_ECDH_CURVE is 'prime256v1',
it breaks the connection when certificate is not compatible
with the default curve since node^8.6.0.
To fix this issue, we need set it to 'auto', makes OpenSSL
select the curve automatically.

fix(Server): set `tls.DEFAULT_ECDH_CURVE` to `'auto'`

---

.github/PULL_REQUEST_TEMPLATE.md

chore(PULL_REQUEST_TEMPLATE): allow features

---

lib/Server.js
package-lock.json
package.json

In pull request https://github.com/webpack/webpack-dev-server/pull/1531 we add a workaround for ECDH curve choice from node@^8.6.0 to node@10. We use parsed number to compare the version but it won't work as expected when compare like 8.12 to 8.6.
To fix this use version compare library is the best choice, since `semver` has been introduced into dependency tree by `chokidar`, choose it will not add package size.

fix(Server): correct `node` version checks

---

bin/options.js

No, tests would require _not_ setting the option (allow default) and running in different environments (TTY vs. non-TTY). Moreover, supports-color has special behaviour for CIs.
Since [supports-color](https://github.com/chalk/supports-color) 5.0.0 (chalk/supports-color#64),
```javascript
return require("supports-color").supportsColor
```
returns a function instead of the test result. Because a function is truthy, colours are enabled by default irrespective of TTY or `FORCE_COLOR` settings.
```javascript
return require("supports-color").stdout
```
is the correct way to use supports-color.
None.

fix(bin/options): correct check for color support (`options.color`)

---

.travis.yml

No, this is about the tests.
Mac OS X (on Travis) has a unknown segfault running the tests. About a month ago the `node/stable` went from Node 10 to Node 11, and then the project started getting these segfaults on Proxy tests as far as I can see.
This is just a workaround, but the tests failing like now isn't very useful. I've added a bug with Node:
https://github.com/nodejs/node/issues/24835
This change should be reverted once it is fixed.

ci(travis): Node 11 (on OS X) crashes, use 10 for now

---

package-lock.json
package.json

No. Upstream issue.
- Fixes issue https://github.com/webpack/webpack-dev-server/issues/1491 (AssertionError in spdy-transport consistently causing failures while running in Chrome 69)
- Upstream bug: https://github.com/spdy-http2/spdy-transport/issues/47#issuecomment-436956755
No breaking change. Changelog for upstream:
- https://github.com/spdy-http2/node-spdy/compare/v3.4.7...v4.0.0
- (the ALPN changes are just their own tests)
- most other changes are sub-dependency updates
No.

fix(package): update `spdy` v3.4.1...4.0.0 (assertion error) (#1491)

---

package-lock.json
package.json

Didn't add tests, as this would require CI to run against webpack v5 to exhibit the problem.
Can reproduce the issue and confirm the fix by installing webpack v5 into this package and running the `prepare` script.
fixes #1598 
none

fix(package) Add url for compatibility with webpack@5 (#1598)

---

lib/Server.js
test/Validation.test.js

Yes
Fixed #1604 
`checkHost` add `//` to header value for parsing.
#1603 use `checkHost` to check `Origin` header.
However, `Origin` must start with scheme ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)), so paring result will be incorrect.
(e.g. `http://localhost:8080` -> `//http://localhost:8080`)

Fix checkHost for checking Origin header

---

lib/Server.js

No
fixes #1607
`Trailing commas in function syntax` is not supported in Node.js <= v7.x
Remove comma.

Delete a comma for Node.js <= v7.x

---

lib/Server.js

No
sockjs will remove `Origin` header, however Origin header is required for checking host (#1603).
See https://github.com/webpack/webpack-dev-server/issues/1604#issuecomment-449582097
This workaround overwrote `Session.prototype.decorateConnection`.
(See https://github.com/sockjs/sockjs-node/blob/v0.3.19/src/transport.coffee#L112-L140)
This workaround maybe broken at `sockjs@^0.4.x` because sockjs are refactoring now.
When sockjs/sockjs-node#247 is merged, this workaround is not necessary.

Add workaround for sockjs@~0.3.19

---

lib/utils/addEntries.js
test/Entry.test.js

Yep, tests added.
When setting the `hot` or `hotOnly` option, the entries are added automatically, but the HMR plugin needs to be added into config by the user.
This PR extends the existing `addEntries` module to also amend the plugins config. This does make the name a bit of a misnomer, but for now i've just done the minimal changes.
This is arguably a breaking change, as it's modifying config that it wasn't before. **But** if you were passing `hot` or `hotOnly` and missing the plugin, you were doing something wrong - and I've put in some logic to prevent duplicates of the HMR plugin.
I think it could be argued that this is safe to put into a point release.
This overlaps somewhat with functionality implemented in `webpack-cli/bin/convert-argv`, that adds the webpack HMR plugin if you …

Automatically add the HMR plugin when hot or hotOnly is enabled

---

README.md

docs(README): add index

---

.travis.yml
appveyor.yml

and add node_modules as a cache
https://github.com/webpack/webpack-dev-server/pull/1650#issuecomment-461023293
no

chore(ci): add v8 and v11 of Node version

---

lib/Server.js
package.json

refactor(Server): use class

---

lib/Server.js

In node v11+:
```
util.js:305
throw new ERR_INVALID_ARG_TYPE('superCtor.prototype',
^
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type Object. Received type undefined
```

Fix SPDY fails in node >= 11.1.0

---

test/Proxy.test.js
test/shouldSkipTestSuite.js

This test is unstable when running on Node v11 on MacOS.
N/A
see https://github.com/webpack/webpack-dev-server/pull/1633#issuecomment-463982581
no 
`HistoryApiFallback.test.js` seems to be good when we add skipping code to `Proxy.test.js`.

test(Proxy): skip Proxy.test.js

---

package-lock.json
package.json

_Short conclusion:_ This change makes webpack-dev-server available for AIX systems.
internal-ip got an upgrade, as well as its dependency default-gateway. Both of them now support aix systems. Since internal-ip got a new major release version (because it was upgraded to use node>=6 as well), we need to upgrade the required version of internal-ip here.
We have an AIX system we want to use Angular and/or React on. Since default-gateway was not available on AIX systems, we had to come up with a solution for this system.
The package maintainer of default-gateway politely made the pull request to update internal-ip. By doing this, they made a new major release. That's why the changes in default-gateway and internal-ip are not automatically used when installing webpack-dev-server. …

Use internal-ip@4.0.0

---

lib/Server.js
test/Proxy.test.js

Yes. 
* I added a new test to test the proxy config.
* I renamed a previous test since the name of the test was too generic after adding a new one.
Fix #1438.  Allow for a simple object proxy config as described in the [options schema](https://github.com/webpack/webpack-dev-server/blob/349e7332a18f46250554ccc5fb5272a3550aad53/lib/options.json#L224) and demonstrated in the [docs](https://webpack.js.org/configuration/dev-server/#devserver-proxy).
```js
module.exports = {
//...
devServer: {
index: '', // specify to enable root proxying
host: '...',
contentBase: '...',
proxy: {
context: () => true,
target: 'http://localhost:1234'
}
}
};
```
N/A
I'm not sure if just checking for a `target` prop is too naive on the proxy config.

fix: allow single object proxy config

---

lib/Server.js
test/Https.test.js

Yes
fixes #1674
No
It is regression, just not `pfx` can't be string due it is binary format

fix: allow `ca`, `key` and `cert` will be string (regression)

---

test/Util.test.js
test/Validation.test.js

no
resolve `ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.`
via #1673

test(Util, Validation): close server each time test ends

---

lib/Server.js

No need
We don't remove `setup` in `v3`, we should do this for `v4`
No
No

fix: deprecation message about `setup` now warning about `v4`

---

bin/webpack-dev-server.js
lib/Server.js
lib/utils/addEntries.js
lib/utils/colors.js
lib/utils/createCertificate.js
lib/utils/createConfig.js
lib/utils/createDomain.js
lib/utils/createLogger.js
lib/utils/defaultTo.js
lib/utils/getVersions.js
lib/utils/runBonjour.js
lib/utils/status.js

Move utils to lib for better testing ans solve future problem when `open`/`bonjure` doesn't work without CLI
No
No

refactor: utils

---

lib/utils/createConfig.js
test/CreateConfig.test.js
test/__snapshots__/CreateConfig.test.js.snap

Yes
fixes #1675 fixes #1686
No
Regresson

fix(regression): handle `key`, `cert`, `cacert` and `pfx` in CLI

---

client-src/default/index.js
package-lock.json
package.json
test/Client.test.js
test/fixtures/client-config/foo.js
test/fixtures/client-config/index.html
test/fixtures/client-config/webpack.config.js
test/helper.js
test/helpers/run-browser.js

On a externally exposed dev server (using host 0.0.0.0), HMR client code builds the socket URL using `location.hostname` but uses the port set in server's configuration. In a more complex and layered architecture, since the browser is at the very end of it, the proper way to infer socket's URL (as exposed and proxied by dev server in `.../sockjs-node/info?t=XX`) is to also use `location.port` along with the `location.hostname`.
More and more we see the scenario where the dev server is used in a cloud-based development environment or an architecture with some sort of proxy in front of it.
- With a dev server externally exposed, host `0.0.0.0` and port `9000` and a proxy exposing it in `http://dev.mydomain.com` (default port 80).
- Expected HMR socket generated URL: …

Use location.port when location.hostname is used to infer HMR socket URL

---

package-lock.json
package.json

no
Currently, jest-util occurs errors when we don't use its the latest version if we use Node11.11.0.
jest's issue: https://github.com/facebook/jest/issues/8069
node's pr: https://github.com/nodejs/node/pull/26488
no

chore(deps): update jest to v24.3.1

---

README.md
lib/Server.js
test/Proxy.test.js

Yes
Based on the [explanation in the docs](https://webpack.js.org/configuration/dev-server/#devserverproxy)
> It must return either `false` or a path that will be served instead of continuing to proxy the request.
It was expected that `return false` skip the proxy with a 404
None
Closes https://github.com/webpack/webpack-dev-server/issues/1677
/CC @evilebottnawi 
@jsmith-sapient @jshado1 @evilebottnawi could you please test this manually and confirm that this have the intended behaviour?

Fix proxy bypass return false

---

lib/Server.js
lib/utils/createConfig.js
test/CreateConfig.test.js
test/Server.test.js
test/__snapshots__/CreateConfig.test.js.snap
test/fixtures/schema/webpack.config.no-dev-stats.js

Will work on it if really needed.
We get flooded by warnings in the console.
Fixes #1557

fix(Server): cascade stats options

---

lib/Server.js
test/Validation.test.js

No
This is a port of https://github.com/webpack/webpack-dev-server/pull/1603 fix but for v2 branch.
Basically, it addresses CVE vulnerability https://www.npmjs.com/advisories/725
I know that v2 is deprecated but it is not an easy task to upgrade this lib to v3 in rails apps, because some dependencies are still in release candidate state or even in beta.
Websocket is now checked for origin

Check origin header for websocket connection

---

test/Routes.test.js
test/helper.js

No, but the bug is in a test.
Solves this issue: https://github.com/webpack/webpack-dev-server/issues/1734.
I ran into this issue while creating a fix for this: https://github.com/webpack/webpack-dev-server/issues/1703. The fix I made for that problem extends the initial compilation time and makes the Routes test fail, so I thought it would be good to solve this before going further.
None

Fix Routes test and add new server creation helpers

---

.gitignore
.travis.yml
appveyor.yml
lib/Server.js

run v2 on Travis and Appveyor

---

examples/api/middleware/webpack.config.js
examples/api/simple/webpack.config.js
lib/utils/createDomain.js
package-lock.json
test/Client.test.js
test/Util.test.js

Yes, added a new test for `createDomain`.
Fixes https://github.com/webpack/webpack-dev-server/issues/1743
- Removed one of the entry scripts from the api examples because that is now added automatically
- `createDomain` should default to `localhost` when the `options.host` is not provided, that is what was resulting in `'http:/sockjs-node'` without the hostname in the middle.
None

Fix: Default to localhost when no host option, remove entries that are now added automatically

---

lib/Server.js
test/BeforeAndAfter.test.js
test/helper.js

Yes
Allow to get information from webpack in `before` and `after`
No
No

feat: add webpack as argument to before and after options

---

lib/Server.js
test/Server.test.js

fixes: #1724
Yes.
A test which Checks `application/wasm` already exists.
https://github.com/webpack/webpack-dev-server/blob/master/test/ContentBase.test.js#L301
Validate express object.
no
no

fix(Server): validate express.static.mime.types

---

test/Compress.test.js
test/fixtures/simple-config-other/foo.js
test/fixtures/simple-config-other/webpack.config.js

yep
Avoid skip test
No
/cc @hiroppy I think we should enable `compress` by default in next major for better DX, 99% developers set it to true

test: compress option

---

lib/Server.js
test/Server.test.js
test/__snapshots__/Server.test.js.snap

yes
fixes #1776 
No because previously behavior was wrong
No

fix(regression): always get necessary stats for hmr

---

bin/webpack-dev-server.js
test/Server.test.js
test/__snapshots__/Server.test.js.snap

No...
Currently `addEntries` is called twice when using the `cli`. First it is called [here](https://github.com/webpack/webpack-dev-server/blob/master/bin/webpack-dev-server.js#L143) in the cli bin, and then always called again when we create the dev server instance [by calling updateCompiler](https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L98) then [here](https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/updateCompiler.js#L47).
This extra call is not needed, and actually causes an issue with my specific setup. In my Webpack config the `entry` is set dynamically via a plugin once the plugin has initialized. Since the first call to `addEntries` is ran on the raw config before any plugins run it is inaccurate and thinks that I have no entries, …

Only add entries after compilers have been created

---

lib/options.json
lib/utils/addEntries.js
test/Entry.test.js
test/UniversalCompiler.test.js
test/fixtures/universal-compiler-config/client.js
test/fixtures/universal-compiler-config/server.js
test/fixtures/universal-compiler-config/webpack.config.js

Yes
When using an universal/isomorphic multicompiler setup and using the default setting of `inline:true`, the client runtime gets injected into the entries for each compilation.  However, as far as I can tell, the client runtime is only designed to work in the browser (`target:"web"` or `target:"webworker"`).  
With `target:"node"`, the following error is thrown:
```
urlParts.port = self.location.port;
^
ReferenceError: self is not defined
```
From
https://github.com/webpack/webpack-dev-server/blob/99e8db0f8cc441bb8f6acc60d786e33c38b8fc1d/client-src/default/index.js#L46
This PR updates `addEntries` to check the compilation target for each compiler.  Since the client runtime is only designed for web targets, it is only prepended to those compilations.  The HMR runtimes are still prepended …

fix(addEntries): only add client entry to web targets

---

examples/.eslintrc
examples/general/universal-config/README.md
examples/general/universal-config/client.js
examples/general/universal-config/server.js
examples/general/universal-config/webpack.config.js

This example demonstrates using a `webpack` config containing a `target: web` config and `target:node` config.
no
I want to add an example.
https://github.com/webpack/webpack-dev-server/pull/1775#issuecomment-483809174
no

chore(examples): add universal-config example

---

bin/options.js
client-src/default/index.js
lib/options.json
test/options/__snapshots__/options.test.js.snap
test/options/clientLogLevel.test.js

Yes
The `clientLogLevel` implementation was incorrect with the documentation.
https://webpack.js.org/configuration/dev-server/#devserverclientloglevel
This PR brings it up to date.
Currently if you use `trace`, `debug`, `warn`, or `silent` or will receive a cli incorrect param error.
This  will cause a cli error for users using `"clientLogLevel": "warning | none"`.
The correct property should be `"warn"` or `"silent"`.

fix: update clientLogLevel to match docs and error

---

lib/Server.js

Not required
Refactor code (part 1 of 3)
No
No

refactor: server

---

lib/Server.js
lib/utils/createCertificate.js
lib/utils/getCertificate.js

refactor: server (part 2)

---

client-src/default/index.js
test/Client.test.js

ISSUE: https://github.com/webpack/webpack-dev-server/issues/1777
REF: https://github.com/webpack/webpack-dev-server/pull/1792
REF: https://github.com/webpack/webpack-dev-server/pull/1664
Revert from #1664.
this pr is just a revert, but it is WIP status.(to validate)
nope
fixes #1777

fix(client-src): don't use self.location.port

---

client-src/default/index.js
lib/options.json
lib/utils/addEntries.js
lib/utils/createConfig.js
test/Client.test.js
test/options.test.js

Yes
As mentioned here: https://github.com/webpack/webpack-dev-server/issues/1777, there could potentially be a need for a `sockHost` which is different from the `host` option.
I also realized that when `sockPort` was added, a problem could occur if `sockPort` was included but `sockPath` was not. Specifically, they both check `urlParts.path === '/'` to see if the query string should be parsed or not, but that method of checking only works if a single option is passed in through `urlParts.path`. I can make a minimum reproducible test repo for this problem if needed. This is the reasoning behind partially changing how the sock url is built.
None

Added sockHost, changed how sock URL is built

---

bin/webpack-dev-server.js
examples/api/simple/server.js
lib/Server.js
lib/utils/status.js
test/Server.test.js

Yep
fixes: #1510 
closes: #1657
closes: #1627
webpack-dev-server can be opened via Node api now.
`Server.listen` process was unified to `Server` class.
Nope but be careful

migrate Server.listen from bin

---

bin/webpack-dev-server.js
lib/Server.js
test/cli.test.js

yep
related #1863
Currently, `--socket` is broken so I fix.
nope

fix listen-socket

---

lib/Server.js

refactor: setupFeatures method

---

lib/options.json
test/options.test.js

Add the new errors-warnings preset shipped in v4.31.0. Keeping
webpack-dev-server presets supported consistent with Webpack will make
both tools easier to use.
https://github.com/webpack/webpack/releases/tag/v4.31.0
https://github.com/webpack/webpack/pull/8919/files#diff-baf371f5446dc9bc4b41022587e05b48

fix(stats): add errors-warnings preset

---

test/Client.test.js
test/__snapshots__/Client.test.js.snap

yes
Just testing `console.log` of the client's code.
no
Maybe liveReload has a bug... see the snapshot.

test(client): check console.log

---

lib/Server.js
lib/options.json
test/CreateConfig.test.js
test/__snapshots__/CreateConfig.test.js.snap
test/onListening.test.js
test/options.test.js

yes
fixes #1569 
No
- Also added deprecation for next major release
- This option allow to developers run own scripts after run webpack-dev-server

feat: `onListening` option

---

lib/utils/addEntries.js
test/Entry.test.js

yes
Regression
No
https://github.com/peter23/NW.js-svelte-boilerplate

fix: add client code for `node-webkit` target

---

lib/utils/processOptions.js
test/cli.test.js
test/fixtures/promise-config/foo.js
test/fixtures/promise-config/webpack.config.js
test/helpers/test-bin.js

fix(options): allow passing promise function of webpack.config.js

---

lib/Server.js
lib/utils/runOpen.js
lib/utils/status.js

no need
move `opn` login to own util like `bonjour`
We should move `opn` logic from `status` util because it is misleading status should only output logs (based on name of util), so let's do it in next pr
No
No

refactor: utils and server

---

client-src/default/index.js
client-src/default/utils/createSocketUrl.js
test/client/default/utils/__snapshots__/createSocketUrl.test.js.snap
test/client/default/utils/createSocketUrl.test.js

refactoring, yep
refactoring client code
no
Perhaps existing code seems to have bugs in some patterns. (or my sample URLs are bad😉) See the result of snapshots. Let's fix it with other PR.

refactor(client): create createSocketUrl module into utils

---

test/SockJSServer.test.js

New test.
Tests the recently added `SockJSServer`
None

test(server): add SockJSServer test

---

.gitignore
test/SockJSServer.test.js
test/e2e/Client.test.js
test/fixtures/reload-config/foo.js
test/temp/README.md

modify only
Currently, main.css doesn't delete after running tests and it causes the errors of prettier.
In addition, we don't need `temp` directory. If you want it, you can use `fs.mkdtemp`.
no

test: delete temp directory

---

setupTest.js
test/ContentBase.test.js
test/LiveReload.test.js
test/e2e/Client.test.js
test/e2e/ClientOptions.test.js
test/e2e/ProvidePlugin.test.js

update only
migrate setTimeout to setupTest.js
no

test: change jest.setTimeout from 20000 to 30000

---

lib/utils/createConfig.js
test/CreateConfig.test.js
test/__snapshots__/CreateConfig.test.js.snap

yes
Currently, `--overlay` is not working at master branch. Please try to run `examples/cli/overlay`.
no

fix(config): enable `--overlay`

---

azure-pipelines.yml
package.json

no
Next major version doesn't support Node6.
yes

chore: don't support Node6

---

.eslintrc
client-src/.eslintrc
client-src/default/index.js
client-src/default/overlay.js
client-src/default/socket.js
client-src/default/utils/createSocketUrl.js
client-src/default/utils/getCurrentScriptSource.js
client-src/default/utils/log.js
client-src/default/utils/reloadApp.js
client-src/default/utils/sendMessage.js
client-src/default/webpack.config.js
client-src/live/index.js
client-src/live/webpack.config.js
client-src/sockjs/index.js
client-src/sockjs/webpack.config.js
test/client/default/utils/createSocketUrl.test.js
test/client/default/utils/getCurrentScriptSource.test.js
test/client/default/utils/reloadApp.test.js
test/client/default/utils/sendMessage.test.js

refactor(client): make use of ESM instead of CJS

---

lib/utils/findPort.js
package-lock.json
package.json
test/server/utils/__snapshots__/findPort.test.js.snap
test/server/utils/findPort.test.js

yes
Restore previously behavior (it is regression) 
No
fixes #1991

fix: retry finding port when port is null and get ports in sequence

---

test/options.test.js

modify only
We changed the time from 30000 to 60000, but options.test.js has many execution times.
So, I specified 20000 as jest.setTime to options.tests.js.
in next branch, this file is refactored and the execution is quite fast.
https://github.com/webpack/webpack-dev-server/blob/feature/refactor-tests/test/options.test.js
no

test(options): set jest.setTimeout

---

test/e2e/ProvidePlugin.test.js
test/fixtures/provide-plugin-config/foo.js

Updated `ProvidePlugin.test.js`
We need to provide the compiled version of the client in order for `injectedClient === expectedClient` to be true.
None

fix(test): fix ProvidePlugin.test.js

---

lib/utils/runOpen.js
test/server/open-option.test.js
test/server/utils/runOpen.test.js

fixes: https://github.com/webpack/webpack-dev-server/issues/1990
yes
see https://github.com/webpack/webpack-dev-server/issues/1990
commit: https://github.com/sindresorhus/open/commit/da2d663d163ad29bffea95540b1b9ea302e17871#diff-168726dbe96b3ce427e7fedce31bb0bcR23
Our open(opn)'s version is old, and `wait` seems to be `true` by default in this version.
no

fix(open): set `wait: false` to run server.close successfully

---

client-src/default/utils/log.js
lib/options.json
test/client/utils/__snapshots__/log.test.js.snap
test/client/utils/log.test.js
test/options.test.js

ISSUE: https://github.com/webpack/webpack-dev-server/pull/1901
yes
See the title.
yes

 feat(client): delete `none` and `warning` from clientLogLevel

---

lib/options.json

The error message of `clientLogLevel` is not correct, so fixed it.
ref. https://webpack.js.org/configuration/dev-server/#devserverclientloglevel
not breaking change

fix: error message of clientLogLevel

---

test/e2e/Client.test.js
test/e2e/ClientOptions.test.js
test/e2e/ProvidePlugin.test.js

Jest seems to have problems with the browser taking a while to close after a test has failed. Running tests after the browser has closed seems to be a workaround. I believe this will fix hanging on Windows CI.
None

test(e2e): make browser close before tests run

---

CHANGELOG.md

Don't need.
#1937 is 3.6.0, not 3.7.0.
The link to compare also seems to be wrong.
No.
No.

docs: Fix CHANGELOG.

---

CONTRIBUTING.md

Current [contribution guide](https://github.com/webpack/webpack-dev-server/blob/27eb99c81c74c164997c7d0b102381a71573b07c/CONTRIBUTING.md) does not exist about CLA. IMHO It is better to have CLA for a contributor.
I wrote it referencing [webpack-cli](https://github.com/webpack/webpack-cli/blob/6ee3c0b11638997613d22c186d21e0736108d295/.github/CONTRIBUTING.md).

docs(contribution): add CLA section

---

.versionrc

no
we always delete test's section from CHANGELOG.md manually, but it bothers and this change can prevent to rebase to fix CHANGELOG.md.

chore(standard-version): add .versionrc to hide test's section

---

client-src/clients/WebsocketClient.js
package.json
test/client/clients/WebsocketClient.test.js
test/client/clients/__snapshots__/WebsocketClient.test.js.snap
test/ports-map.js

Yes
Adds `WebsocketClient` implementation which should eventually become default client option. This cannot be tested with e2e until `clientMode` is merged, and this must work with `WebsocketServer`, or some other WebSocket server implementation.
None

feat(client): WebsocketClient implementation and tests

---

test/client/clients/SockJSClient.test.js
test/client/clients/__snapshots__/SockJSClient.test.js.snap
test/server/servers/SockJSServer.test.js
test/server/servers/__snapshots__/SockJSServer.test.js.snap

Yes
Simple switch to using snapshots on `SockJSServer` and `SockJSClient` tests.
None

test(server/client): make sockjs implementation tests use snapshots

---

lib/Server.js
lib/options.json
lib/utils/getSocketClientPath.js
lib/utils/updateCompiler.js
test/GetSocketClientPath.test.js
test/e2e/ClientMode.test.js
test/e2e/__snapshots__/ClientMode.test.js.snap
test/fixtures/custom-client/CustomSockJSClient.js
test/options.test.js
test/ports-map.js
test/server/utils/getSocketClientPath.test.js

Yes
This option makes it possible to provide a custom client socket implementation.
This mimics the `serverMode` implementation with one exception: `clientMode` does not accept a function (specifically, a class, as `serverMode` does). The reason for this is that it is not possible (or just pointlessly complex and impractical) to make a class within an executing server-side script, then pass it along to the client. There must be a path to the file that `module.exports` the client implementation.
Since the only thing we really need to pass to the client is the path to the implementation, I made the helper `getSocketClientPath`. There is no reason for a helper to be returning the whole `ClientImplementation` class, since it is not actually used server-side.
None
One consideration:
Should …

feat(client): add clientMode option

---

test/ports-map.js
test/server/clientMode-option.test.js

Yes
I should have added this earlier, but this simply confirms that the server is passing stuff into the `clientMode` helper correctly, and is throwing with bad `clientMode`.
None
I will add this mocking method to check `serverMode` helper usage if it looks fine.

test(client): added clientMode option test

---

lib/Server.js
lib/servers/SockJSServer.js
lib/servers/WebsocketServer.js
test/server/__snapshots__/serverMode-option.test.js.snap
test/server/serverMode-option.test.js

Yes
Headers security check for connecting clients should not allow a connection without headers: https://github.com/webpack/webpack-dev-server/pull/2077
Changes the socket server implementation requirements such that headers must be passed to `onConnection` callback.

fix(server): stricter headers security check

---

lib/utils/getSocketServerImplementation.js
test/server/__snapshots__/serverMode-option.test.js.snap
test/server/serverMode-option.test.js
test/server/utils/getSocketServerImplementation.test.js

Yes
Adds the option `serverMode: 'ws'`. Please review and merge https://github.com/webpack/webpack-dev-server/pull/2077 before this. 
I still want to work on `serverMode-option.test.js` further such that it tests to see that `Server.js` interacts with a socket server implementation correctly. Currently, it only checks that `Server.js` calls the constructor of the server implementation. I will work on this later.
None

feat(server): serverMode 'ws' option

---

examples/run-example.js
package-lock.json
package.json

No
As described here: https://github.com/webpack/webpack-dev-server/pull/2100#discussion_r300542619, `$INIT_CWD` does not work on Windows. I tried solving with `cross-env` but it did not work, so here is an alternative.
None

fix(examples): make examples webpack-dev-server npm script work on Windows

---

lib/utils/getSocketClientPath.js
test/e2e/Client.test.js
test/e2e/ClientMode.test.js
test/e2e/ProvidePlugin.test.js
test/e2e/__snapshots__/ClientMode.test.js.snap
test/fixtures/provide-plugin-ws-config/foo.js
test/fixtures/provide-plugin-ws-config/webpack.config.js

Yes
Adds `clientMode: 'ws'` with tests to confirm that it works, including full e2e tests.
None

feat(client): 'ws' clientMode

---

test/ports-map.js
test/server/__snapshots__/Server.test.js.snap
test/server/open-option.test.js
test/server/servers/__snapshots__/SockJSServer.test.js.snap
test/server/servers/__snapshots__/WebsocketServer.test.js.snap

N/A
As mentioned in https://github.com/webpack/webpack-dev-server/pull/2143, if we need to test CLI default port selection, which will use ports 8080, 8081, 8082... we should make sure the hard port mapping does not use these ports near port 8080. We just need to provide enough room for this default port assignment so that there will never be collisions.
None

test(server): increase port mapping base number

---

lib/utils/addEntries.js
test/server/utils/addEntries.test.js

Yes
Fixes #87, a long-standing subtle bug which seems to have tripped up a lot of people historically.
See my comment on the issue: https://github.com/webpack/webpack-dev-server/issues/87#issuecomment-514381082. The only way I can see this solution being a problem is if we're worried about configs that are using `--hot` and also have a plugin that *isn't* `HotModuleReplacementPlugin` but has the same name. In that case, we'd no longer inject the real HMR plugin. I'm not sure how likely this is and I seem to remember seeing other webpack plugins that check the name string rather than relying on the constructor reference (probably for this same reason).
However, if we are concerned and if there's a property we can additionally check on the instances of the plugin, that …

fix: check for name of HotModuleReplacementPlugin to avoid RangeError

---

package-lock.json
package.json

webpack@4.39.1 cannot exit when a platform is Linux. Currently, all PRs are down so I add `--forceExit` flag to jest as temporary.
diff: https://github.com/webpack/webpack/compare/v4.39.0...v4.39.1
closes: #2173

chore(deps): update webpack

---

lib/Server.js

no
https://github.com/webpack/webpack-dev-server/projects/1#card-22549444
yes
no

refactor(server): remove some variables of options

---

bin/webpack-dev-server.js
lib/utils/setupExitSignals.js
test/server/utils/setupExitSignals.test.js

No, should I add tests for `setupExitSignals`?
Fixes problem with `setupExitSignals` mentioned in: https://github.com/webpack/webpack-dev-server/issues/1479
An alternative to this approach is simply to get rid of `setupExitSignals`, but I think it's better to keep the helper and just change the function a bit.
Altered `setupExitSignals` function API.

fix(server): fix setupExitSignals usage

---

lib/Server.js
lib/options.json
lib/utils/createConfig.js
lib/utils/handleStdin.js
test/cli/cli.test.js
test/helpers/test-bin.js
test/options.test.js
test/ports-map.js
test/server/stdin-option.test.js
test/server/utils/handleStdin.test.js

Yes
This makes stdin an option for both CLI and API, and helps in moving configuration changes out of the CLI for CLI refactor.
Same PR as https://github.com/webpack/webpack-dev-server/pull/2106, but moved to `next`. It was faster to do this than an ugly rebase.
None, `stdin` will work the same as it did before on CLI.

feat(server): add stdin option to API

---

bin/webpack-dev-server.js
lib/Server.js
lib/utils/startUnixSocket.js
test/cli/cli.test.js
test/helpers/test-server.js
test/helpers/test-unix-socket.js
test/server/onListening-option.test.js
test/server/socket-option.test.js
test/server/utils/startUnixSocket.test.js

Yes
This is the `socket` option handling portion of: https://github.com/webpack/webpack-dev-server/pull/2028. The goal is to move socket handling out of the CLI and into the API `listen` method. 
API users will now get different behavior when they put a socket path in place of `port` in the `server.listen(port, hostname, fn)` method.
This should be merged before I start work on the `findPort` portion of https://github.com/webpack/webpack-dev-server/pull/2028

feat/refactor(server): move socket handling into server.listen

---

client-src/default/utils/createSocketUrl.js
test/client/utils/__snapshots__/createSocketUrl.test.js.snap
test/client/utils/createSocketUrl.test.js

Yes
Pulled in changes from here and updated the test snapshot to fix CI: https://github.com/webpack/webpack-dev-server/pull/2229
N/A

scriptHost fix

---

test/cli/cli.test.js

N/A
Use ports map instead of hard-coded port 8080. Note that the `cli` ports-map value already existed, just wasn't being used.
N/A

test(cli): use ports map for quiet logging test

---

package-lock.json
package.json

N/A
Same changes as here https://github.com/webpack/webpack-dev-server/pull/2238 except that `http-proxy-middleware` does not support Node 6 for latest version, so not updating on master.
None
closes: #2238

chore(deps): update minor dependencies without http proxy middleware

---

bin/webpack-dev-server.js
lib/Server.js
test/server/Server.test.js
test/server/__snapshots__/Server.test.js.snap

Not yet
@evilebottnawi Is this what you meant by async `userCallback`?
Making the callback from `server.listen` async, along with the internally used `userCallback`. Also, removed a redundant piece of code that I left in the CLI.
None

feat(server): async user callback for server.listen

---

lib/Server.js
lib/options.json
lib/utils/addEntries.js
lib/utils/createConfig.js
test/e2e/ClientOptions.test.js
test/options.test.js
test/server/sockPath-option.test.js
test/server/transportMode-option.test.js
test/server/utils/__snapshots__/createConfig.test.js.snap

Used existing tests
It's in the To Do list
Using sockHost, sockPath and sockPort options will be invalid. they must be used in the new clientSocketOptions option.

Union sock options

---

bin/cli-flags.js

N/A
Flags for `webpack-cli serve` need to be present on `webpack-dev-server` to be maintained. It is better if they are on `master` so that they can be part of a release, then `webpack-cli next` can access them easily.
The flags here may not be perfectly up-to-date, I will bring them up to date before merge.
None

Put webpack-cli serve flags in dev server

---

lib/utils/runBonjour.js
test/server/utils/__snapshots__/runBonjour.test.js.snap
test/server/utils/runBonjour.test.js

Yes
It was impossible to run mutliple instances of webpack-dev-server if they all had `bonjour` because of 'name already in use' error.
No

fix: add hostname and port to bonjour name to prevent name collisions

---

test/cli/cli.test.js
test/e2e/ClientOptions.test.js

For better test output.
follow up from https://github.com/webpack/webpack-dev-server/pull/2303

fix(test): replace include.toBeTruthy with toContain

---

client-src/default/utils/createSocketUrl.js
test/client/utils/__snapshots__/createSocketUrl.test.js.snap
test/client/utils/createSocketUrl.test.js

follow up of https://github.com/webpack/webpack-dev-server/pull/2303 
1) the tests are incorrect because they did not prepend the `?` to the url. The parameter format should be like `?http://0.0.0.0:8096&sockPort=8097&sockHost=localhost`
2) replacing two `//` with one `/` looks wrong an unused as mentioned in https://github.com/webpack/webpack-dev-server/pull/2303

fix(client): fix tests for createSocketUrl

---

client-src/default/utils/createSocketUrl.js
test/client/utils/__snapshots__/createSocketUrl.test.js.snap
test/client/utils/createSocketUrl.test.js

Chrome and Firefox accept `http://`/`ws://` mixed-content connection to
`127.0.0.1` even when the actual website is loaded via `https://`.
Fixes #2302 
I'm not sure if the [current tests](https://github.com/webpack/webpack-dev-server/blob/master/test/client/utils/__snapshots__/createSocketUrl.test.js.snap) actually contain correct assertions.
described in https://github.com/webpack/webpack-dev-server/issues/2302
nope

fix(client): don't override protocol for socket connection to 127.0.0.1

---

lib/Server.js
lib/options.json
lib/utils/normalizeOptions.js
test/server/contentBasePublicPath-option.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap
test/server/utils/normalizeOptions.test.js

Tell the server at what URL to serve `devServer.contentBase`. If there was a file `assets/manifest.json`, it would be served at `/serve-content-base-at-this-url/manifest.json`
__webpack.config.js__
```javascript
module.exports = {
//...
devServer: {
contentBase: path.join(__dirname, 'assets'),
contentBasePublicPath: '/serve-content-base-at-this-url'
}
};
```
Now `webpack-dev-server` serves static files (`contentBase`) from root ignoring `publicPath`
Using added option we can serve static files from `publicPath`
This use case is needed in create-react-app, when want to serve all files from `publicPath`
doesn't matter in development or production
~~https://github.com/iamandrewluca/plsdelete-wds-use-case~~
Above repo will be deleted because does not reflect current changes after review.
From …

feat(server): add `contentBasePublicPath` option

---

client-src/default/utils/createSocketUrl.js
test/client/utils/createSocketUrl.test.js

Add the ability to set `sockPort: 'location'` to make the sock port dynamic.
This change would allow the port to be specified by an individual proxy, e.g. if different team members have their environments configured differently.
I added the scenario to an existing test.
Related to #1664 which was semi-addressed by #1792 and then reverted by #1838.
This change provides a way for the sock port to use the browser location's port which may or may not be known at build time. For example,
* one team member hits webpack-dev-server directly at http://localhost:3000
* another uses a Docker container that proxies it via http://localhost.example.com
* a third uses Nginx to proxy through SSL with https://dev.example.com
For all three to be able to use it the way they want they would have to modify …

feat(client): allow sock port to use browser location's port

---

package-lock.json

no
```
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Cross-Site Scripting                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ serialize-javascript                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ copy-webpack-plugin [dev]                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ copy-webpack-plugin > serialize-javascript                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ …
```

chore(deps): update lock file

---

client-src/default/utils/createSocketUrl.js

we need test generated code on ES5 compatibility, feel free to do it
fixes #2361
No
No

fix: ie11 compatibility

---

lib/Server.js
test/server/after-option.test.js
test/server/contentBasePublicPath-option.test.js

Yes
Before #2150, non-GET request where forwarded to any middleware defined in the after option, since #2150, they are handled by `serve-index` instead that always reply with a 405 error.
This fix issue #2370.
No
Closes #2370

fix(server): fallthrough non `GET` and `HEAD` request to routes defined in after option

---

package.json

Can publish a package with this PR and see if it actually works but these kind of fixes have been done multiple times to make Yarn 2 happy. Considering `webpack-dev-server` throws at runtime anyway if `webpack-cli` is missing this shouldn't bother anyone
Yarn 2 currently throws when using `webpack-dev-server` due to it trying to require `webpack-cli` without declaring it anywhere in its dependencies:
```
Error: A package is trying to access another package without the second one being listed as a dependency of the first one
Required package: webpack-cli (via "webpack-cli/bin/config-yargs")
Required by: webpack-dev-server@virtual:836be30d0802b4899b9a78ca9d744f43f038cccf96d6b8307cbd938d17151f1ac108d2e64290515733c51d0949e0c6d87f9a7c9e245dfe628e5c4ef98f22d752#npm:3.8.0 
```
There is no …

Adds an optional peer dependency on webpack-cli

---

lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap
test/validate-options.test.js

BREAKING CHANGE: the `features` option was remove without alternatives
existing
Remove unnecessary option
Yes
No

refactor: remove the `features` option

---

test/server/utils/addEntries.test.js

N/A
- Rephrased test names.
- Minor code refactoring.
> Follow up of #2409
None
N/A

Rephrase test metadata

---

lib/Server.js
lib/options.json
lib/utils/createConfig.js
test/server/contentBase-option.test.js
test/validate-options.test.js

Change existing
Drop support number and absolute urls for `contentBase`
Yes
We need improve schema-utils, to catch problems with invalid paths before run, I put it in todo and will send a PR in future

refactor: the `contentBase` option now accepts only paths

---

lib/Server.js
lib/options.json
lib/utils/createConfig.js
test/__snapshots__/validate-options.test.js.snap
test/fixtures/schema/webpack.config.no-dev-stats.js
test/server/utils/__snapshots__/createConfig.test.js.snap
test/validate-options.test.js

Existing tests
We already support `https: { ca: 'value', key: 'value' ...otherHttpsValues }` so the ability to configure in two options can be misleading, so let's remove it
Yes
No

Refactor https options

---

lib/Server.js
test/server/proxy-option.test.js

Fixes https://github.com/webpack/webpack-dev-server/issues/2380
Yes
See https://github.com/webpack/webpack-dev-server/issues/2380 and https://github.com/webpack/webpack-dev-server/issues/2380#issuecomment-581378628.

Also forward error requests to the proxy

---

lib/utils/addEntries.js
test/fixtures/entry-as-descriptor/foo.js
test/fixtures/entry-as-descriptor/webpack.config.js
test/server/utils/addEntries.test.js

feat: support entry descriptor (closes #2453)

---

lib/Server.js
lib/servers/WebsocketServer.js
test/server/progress-option.test.js

closes: #1666
yes
Emit `progress-update` event.
no

feat(progess): emit progress-update

---

lib/utils/setupExitSignals.js
test/server/utils/setupExitSignals.test.js

Yes.
Someone observed this line crash:
https://github.com/webpack/webpack-dev-server/issues/1479#issuecomment-549824098
This is the fix suggested by @evilebottnawi — please review.
none.
I don't see how that crash was possible, all callers (1 real + few tests) pass an object (and weren't touched since #2181 introduced `serverData`.  But I also can't argue with a stacktrace :-)
Feel free to reject.

fix(server): don't crash on setupExitSignals(undefined)

---

lib/Server.js
test/server/Server.test.js

Yes
add tests & fix: https://github.com/webpack/webpack-dev-server/pull/1698
No

Feat: support http server reporting

---

lint-staged.config.js

From `lint-staged v10` modified files are added automatically to the git commit index.
Nothing
N/A

chore: update lint-staged config

---

azure-pipelines.yml
lib/Server.js
package-lock.json
package.json

Not yet
upgrade chokidar to v3.3
chokidar doesn't support node v6
close should work the same
Edit: didn't see https://github.com/webpack/webpack-dev-server/pull/2533 when I did this, I just applied the patch suggested there

chore(deps): upgrade chokidar

---

lib/utils/runOpen.js
package-lock.json
package.json
test/server/open-option.test.js
test/server/utils/runOpen.test.js

modified
opn is deprecated.
yes because open doesn't support Node6.

fix(run-open): introduce open instead of opn

---

test/helpers/isWebpack5.js
test/server/Server.test.js
test/server/utils/updateCompiler.test.js

Updated.
Fixed some tests to support webpack5.
Need to merge this pr asap.

test: support webpack5

---

lib/Server.js
package-lock.json
package.json
test/server/http2-option.test.js

Updated.
Drop conditions of Node version.
Yes

BREAKING CHANGE(server): get rid of conditions of Node version

---

client-src/default/socket.js
client-src/default/webpack.config.js
client-src/sockjs/webpack.config.js
lib/utils/addEntries.js
lib/utils/routes.js
package.json
test/client/socket-helper.test.js
test/server/__snapshots__/Server.test.js.snap
test/server/utils/addEntries.test.js

N/A
Reorganized client build output to match structure of `client-src`
Thoughts on if we should reorganize it more, or just do this and avoid major breaking changes?
Yes, reorganized client output dir

BREAKING CHANGE: reorganize client directory

---

package-lock.json
package.json

No.
It fixes #2559
Running `npm audit -production` for webpack-dev-server complains about `mkdirp` as well, this should be looked into by the Webpack team.

fix(deps): security vulnerability in yargs-parser

---

lib/utils/routes.js
test/server/utils/routes.test.js

Yes
as @sokra suggested : https://github.com/webpack/webpack-dev-server/pull/2493#pullrequestreview-405542308
a change in the endpoint from `/invalidate` to `/webpack-dev-server/invalidate`.

fix: add prefix for invalidate endpoint

---

package-lock.json
package.json

No.
It fixes #2559
v4 version of #2566
---
Running these steps
```bash
git checkout v4
npm ci
npm test
```
Failed on `Unable to resolve path to module 'open'  import/no-unresolved` lint errors.
```
npm run test:only
```
Failed on the `contentBasePublicPath option › to directory › Request to index` and `contentBasePublicPath option › to directory › Request to other file` tests. 
Is there some setup step that I'm missing?

chore(deps): security vulnerability in yargs-parser

---

lib/utils/routes.js
test/server/utils/routes.test.js

Update existing tests
Backport from v4, because `invalidate` is not release yet, let's fix it before release `3.11.0`
No, because `invalidate` doesn't exists in `3.10` version
No

fix: invalidate route

---

client-src/clients/SockJSClient.js
client-src/clients/WebsocketClient.js
test/client/clients/SockJSClient.test.js
test/client/clients/WebsocketClient.test.js

Yes
I missed a TODO where I meant to add error logging for ws and sockjs after fixing client dir structure
None

feat(client): add ws error logging

---

lib/Server.js
lib/servers/WebsocketServer.js
lib/utils/normalizeOptions.js
test/server/servers/WebsocketServer.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap

yes
Use `this.options.xxx` instead of `this.xxx`.
yes

BREAKING CHANGE: use this.options.xxx 

---

bin/options.js
lib/utils/createConfig.js
test/cli/cli.test.js
test/server/utils/__snapshots__/createConfig.test.js.snap
test/server/utils/createConfig.test.js

Fix prefer hot from cli

---

lib/Server.js
lib/utils/normalizeOptions.js
test/server/liveReload-option.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap
test/server/utils/normalizeOptions.test.js

Yes
Resolve TODO
Potential if you use `this.options.liveReload` before start a server
No

refactor: resolve todo

---

client-src/default/index.js
lib/Server.js
test/client/__snapshots__/index.test.js.snap
test/client/index.test.js
test/e2e/ClientOptions.test.js
test/e2e/Socket-injection.test.js
test/e2e/__snapshots__/ClientOptions.test.js.snap
test/server/__snapshots__/transportMode-option.test.js.snap

Yes
fix : #1831
Alternative to : https://github.com/webpack/webpack-dev-server/pull/2133
The socket server will be disabled when `hot` and `liveReload` are disabled.
I updated the values of `liveReload: false` tests since `hot` became enabled by default.
I added tests for `ws` and moved `socket-injection.test.js` to `e2e` folder since e2e testing is the only way to test `ws` as it became the default websocket.
Also I've updated `console.log` test in `test/e2e/ClientOptions.test.js` to check for all WebSocket options.
Not sure if logging tests in `test/e2e/ClientOptions.test.js` are enough so I don't know whether I should delete `test/e2e/socket-injection.test.js` or not.

fix: disable socket injection when hot & liveReload are disabled (V4)

---

azure-pipelines.yml
package-lock.json
package.json

no
I hope the audit has been fixed on v4.
no

ci: uncomment audit

---

bin/cli-flags.js
bin/options.js
bin/webpack-dev-server.js
lib/options.json
lib/utils/createConfig.js
lib/utils/createDomain.js
lib/utils/processOptions.js
test/__snapshots__/Validation.test.js.snap
test/cli/cli.test.js
test/fixtures/schema/webpack.config.no-dev-stats.js
test/options.test.js
test/server/utils/__snapshots__/createConfig.test.js.snap
test/server/utils/createConfig.test.js

N/A
Remove socket option
`socket` option removed

BREAKING CHANGE: remove socket option

---

lib/Server.js
lib/options.json
test/__snapshots__/Validation.test.js.snap
test/options.test.js
test/server/https-option.test.js

Yes
Avoid unnecessary option
Yes
No

Remove request cert in favor https options

---

lib/Server.js
test/server/proxy-option.test.js

Yes
Currently result of bypass function is used immediately and there is no way to make it asynchronous. This update allows returning Promise from bypass function in proxy.
It can be useful for downloading content from original source and "patching" it, instead of storing the whole response.
No

feat(server): allow async bypass function for proxying

---

lib/Server.js
test/server/proxy-option.test.js

yep
closes: https://github.com/webpack/webpack-dev-server/pull/2369
no

feat(proxy): add arguments to proxyconfig

---

bin/cli-flags.js

N/A
Some adjustments are needed for certain flags to work as expected with `webpack-cli serve`.
This PR will rely on some fixes to how the webpack-cli arg parser works in here: https://github.com/webpack/webpack-cli/pull/1649
N/A

fix(cli): fix certain flags for webpack-cli serve

---

bin/cli-flags.js
bin/options.js
examples/cli/public-protocol/webpack.config.js
lib/Server.js
lib/options.json
lib/utils/createConfig.js
lib/utils/normalizeOptions.js
test/Validation.test.js
test/__snapshots__/Validation.test.js.snap
test/e2e/ClientOptions.test.js
test/fixtures/schema/webpack.config.no-dev-stats.js
test/options.test.js
test/server/utils/__snapshots__/createConfig.test.js.snap
test/server/utils/__snapshots__/normalizeOptions.test.js.snap
test/server/utils/createConfig.test.js
test/server/utils/normalizeOptions.test.js

Yes
disableHostCheck and allowedHosts options should be merged into a single firewall option
- `disableHostCheck` and `allowedHosts` removed in favor of `firewall`

BREAKING CHANGES: change disableHostCheck and allowedHosts to firewall option

---

client-src/default/index.js
client-src/default/utils/log.js
client-src/transpiled-modules/log.js
client-src/transpiled-modules/strip-ansi.js
client-src/transpiled-modules/webpack.config.js
package-lock.json
package.json
test/client/bundle.test.js
test/ports-map.js

Yes
We need to make the client work with ES5 for webpack@4. This PR does some case-specific patches, rather than trying to fully solve the problem, since webpack@5 always has ES6 syntax in its bundles, unless the user uses babel-loader.
The `webpack/lib/logging/runtime` and `strip-ansi` modules use ES6, so they are placed in the `transpiled-modules` directory and have files that act as a proxy entry to them. Then, these entry files are turned into a bundle with babel-loader, so that the result is a module that works with ES5 and behaves the same way.
Explanation for the ES5 check test: Since webpack takes all the JavaScript and puts it into a string in an `eval` function, a bundle that will not work with ES5 can still pass a basic ES5 check, since all this bad ES6 syntax is inside of a …

Fix: ES5 client

---

test/fixtures/cli/webpack.config.js

updated
when we use webpack@5.0.0-beta.30, our CI will be broken.
output logs are the difference between beta.29 and beta.30. 
webpack@5.0.0-beta.29
```
<i> [webpack-dev-server] Project is running at http://localhost:8080/
<i> [webpack-dev-server] webpack output is served from undefined
<i> [webpack-dev-middleware] Hash: 44cb6417926dcafb24fe
<i> Version: webpack 5.0.0-beta.29
<i> Time: 267 ms
<i> Built at: 2020-09-12 13:25:14
<i> asset main.js 231 KiB [emitted] (name: main)
<i> Entrypoint main = main.js
<i> ./foo.js 41 bytes [built]
<i> ../../../client/default/index.js?http://localhost:8080 4.4 KiB [built]
<i> ../../../node_modules/webpack/hot/dev-server.js 1.59 KiB [built]
<i> ../../../client/transpiled-modules/strip-ansi.js 1.4 KiB [built]
<i> ../../../client/default/socket.js 1.27 KiB …
```

test: add stats:verbose to cli's webpack config

---

CONTRIBUTING.md

Correcting it to the original url rather then using the redirect one

chore(readme): update 'create-react-app' url

---

.github/workflows/nodejs.yml
lib/Server.js
lib/utils/routes.js
package-lock.json
package.json
test/e2e/ClientOptions.test.js

N/A (Covered by existing tests)
* Update `webpack-dev-middleware` to 4.0.2 and `selfsigned` to 1.10.8: closes #2763, closes #2740, closes #2752, and closes #2795.
* Fix failing `ClientOptions` tests: use the Chrome DevTools protocol directly to detect WebSocket and fix `startAwaitingCompilation` usage
* Update CI to use `4` and `latest` instead of `latest` and `next`, respectively, since webpack 5 has been released.
* Attempt to fix directory listing for webpack 5
N/A
[Ignoring whitespace changes in diff](https://github.com/webpack/webpack-dev-server/pull/2828/files?diff=split&w=1) would help review changes in https://github.com/webpack/webpack-dev-server/pull/2828/commits/0f0e9e9f14d1c0ac9da2fe1a726d69113e3161c1.

fix: support webpack@5

---

lib/utils/status.js

N/A (covered by existing tests)
`contentBase` has been removed in favor of `static` in #2670.
N/A

fix: contentBase (static) logging

---

jest.config.js
package-lock.json
package.json
setupTest.js
test/e2e/ClientOptions.test.js
test/options.test.js
test/server/https-option.test.js
test/server/utils/runBonjour.test.js

N/A
- Update `jest` to 26.6.3
- Use `jest-circus` runner
- Fix jest usages
- Retry test three times for flaky tests, e.g., `puppeteer`
N/A

test: fix jest usage and add retry

---

client-src/default/overlay.js

Not yet
Fixes #2786, fixes #2760
No

fix: show detailed error in overlay for webpack 5

---

lib/utils/DevServerEntryPlugin.js
lib/utils/addEntries.js
lib/utils/updateCompiler.js
package-lock.json
package.json
test/fixtures/module-federation-config/entry1.js
test/fixtures/module-federation-config/entry2.js
test/fixtures/module-federation-config/webpack.config.js
test/fixtures/module-federation-config/webpack.multi.config.js
test/fixtures/module-federation-config/webpack.object-entry.config.js
test/integration/ModuleFederation.test.js
test/ports-map.js
test/server/Server.test.js
test/server/utils/addEntries.test.js
test/server/utils/updateCompiler.test.js

Yes, added module federation test cherry-picked from #2723.
**TODO:** Add an unit test for `DevServerEntryPlugin`
Fixes #2484 and fixes #2692. Closes #2723.
Instead of modifying compiler configuration and calling `hooks.entryOption` after it has instantiated, this calls `compilation.addEntry` to add dev server entries into `globalEntry`, as suggested in https://github.com/webpack/webpack-dev-server/issues/2692#issuecomment-682439552.
As discussed in https://github.com/webpack/webpack-dev-server/pull/2723#pullrequestreview-483187667, the issue is with reusing the compiler instance with multiple dev servers, so I've decided to use a plugin, whose entries can be modified later.
I've considered using existing plugins:
* `EntryPlugin`: adds a single entry, so changing the number of entries is …

fix(utils): use plugin to add entries for webpack@5

---

test/server/utils/DevServerEntryPlugin.test.js
test/server/utils/__snapshots__/DevServerEntryPlugin.test.js.snap

Yes
An unit test for `DevServerEntryPlugin` added in #2839.
N/A

test: add unit test for DevServerEntryPlugin

---

test/helpers/test-server.js
test/server/proxy-option.test.js
test/server/static-directory-option.test.js
test/server/static-publicPath-option.test.js

N/A
* Some tests were using the default port `8080`, causing `EADDRINUSE` on collision. Also, added a warning to prevent future mistakes.
* https://github.com/webpack/webpack-dev-server/runs/1413577706
* Some `proxy-option` tests were ended before all servers were closed (not sure this would cause failures)
N/A

test: fix flaky tests

---

lib/utils/status.js

N/A
- `socket` option was removed in #2669.
- `publicPath` option was moved to `dev` in #2660 and now respects webpack output path (#2671), so only log it when it is overridden via `options.dev.publicPath`. Fixes #2745.
N/A

fix(utils): remove `socket` status and log `options.dev.publicPath` only if specified

---

lib/utils/DevServerPlugin.js
test/e2e/ClientOptions.test.js
test/server/__snapshots__/Server.test.js.snap

Modified existing tests.
https://github.com/webpack/webpack-dev-server/pull/2845#discussion_r527680818
Yes, the client uses the port of the current location (`location.port`, equivalent to `sockPort: 'location'`), by default. To get existing behavior, set the `client.port` with the port you'd like to set to, e.g.:
```js
const server = new Server(compiler, {
client: {
port,
}
});
server.listen(port, hostname);
```

fix: use location.port as the client port by default

---

lib/utils/createDomain.js
test/cli/__snapshots__/cli.test.js.snap
test/cli/cli.test.js
test/server/__snapshots__/Server.test.js.snap
test/server/open-option.test.js
test/server/utils/createDomain.test.js

Covered by existing tests.
`createDomain` is used in two places:
- `createSocketUrl`: by setting to `0.0.0.0`, it uses the `location.hostname` by default, like the port (https://github.com/webpack/webpack-dev-server/pull/2845#discussion_r527680818, https://github.com/webpack/webpack-dev-server/pull/2850, https://github.com/webpack/webpack-dev-server/pull/2859)
- `showStatus`: this allows setting `options.host = undefined` and let `listen()` handle the address binding.
This is required for https://github.com/webpack/webpack-cli/pull/2141.
Yes, the client uses the hostname of the current location (`location.hostname`), by default. To get existing behavior, set the `client.host` with the hostname you'd like to set to, e.g.:
```js
const server = new Server(compiler, {
client: {
host: …
```

feat: use server address and fallback to 0.0.0.0 (location.hostname) in createDomain

---

client-src/default/utils/createSocketUrl.js
test/client/utils/createSocketUrl.test.js

Yes.
The location protocol was used on the ipv4 `INADDR_ANY` (0.0.0.0) host but not on the ipv6 one (::).
N/A

fix(client): use location protocol on ipv6 any (::) host

---

lib/Server.js
test/server/liveReload-option.test.js
test/server/static-directory-option.test.js

Existing
use better name
In theory yes, if somebody try to touch `contentBaseWatchers` (edge cases and I think nobody use it)
No

refactor: small

---

lib/Server.js
lib/options.json
test/Validation.test.js
test/__snapshots__/Validation.test.js.snap
test/options.test.js

Move overlay option into client.
Yes

feat(client): move overlay option into client

---

lib/Server.js
test/server/proxy-option.test.js

Yes
fixes #2891
No
it is dirtly fix, because developer can have two configs with the `devServer` option, but in v3 and v4 we have limitation - only one configuration can have `devServer`, otherwise we use `0` index for configurations, we will fix it after refactor it to plugin (I think v5 or v4 after stable release)

fix: multi compiler mode with proxy

---

bin/cli-flags.js
test/cli/cli.test.js
test/fixtures/dev-public-path/foo.js
test/fixtures/dev-public-path/webpack.config.js

test: publicPath logs

---

client-src/default/webpack.config.js
client-src/sockjs/webpack.config.js
client-src/transpiled-modules/webpack.config.js
test/cli/__snapshots__/cli.test.js.snap
test/cli/cli.test.js
test/fixtures/static/foo.js
test/fixtures/static/static/index.html
test/fixtures/static/webpack.config.js
test/helpers/test-bin.js

tests for `static` output
fixes #2745
No
No

test: static output

---

bin/cli-flags.js

No, but tests will be added on webpack-cli side
fixes https://github.com/webpack/webpack-cli/issues/2001
No
No

fix: open option for CLI without arguments

---

client-src/clients/SockJSClient.js
client-src/clients/WebsocketClient.js
test/client/clients/SockJSClient.test.js
test/client/clients/WebsocketClient.test.js

Yes, I added tests to check if the protocol was changed, it is poking at variables inside of WebSocket and SockJS though, this is probably not the most stable way to do this, but I am not sure how to mock those or if that is even necessary.
When using node-webkit, or electron, the protocol can be `file:` or `chrome-extension:`, causing the websocket or sockjs to try to connect to an incorrect url, for example: `file://localhost:8080/ws` or `chrome-extension://localhost:8080/ws`.
This PR changes it to the correct behaviour.
This PR should not be a breaking change.
I just noticed I also replace `https` with `ws`, this should probably be an extra case where it is replaced with `wss`.
**EDIT: I removed the https case**

fix: support file: and chrome-extension: protocols in client

---

bin/cli-flags.js

no
need use `description` instead of `describe` because `webpack` and `webpack-cli` both uses `description` property for options.
This is helpful in the `webpack --help` output. 
https://github.com/webpack/webpack-cli/blob/4dc1a05046aeaf5a17de878a9e595697852bcd32/packages/webpack-cli/lib/webpack-cli.js#L139-L141
no
no

refactor: rename describe property to description for cli-flags

---

package.json

No need
Use caret to avoid unnecessary releases, we still need bundle client, but now it will be avoid problems with server
No
No

chore: use `caret` for some deps

---

.github/workflows/nodejs.yml
lib/Server.js
test/server/Server.test.js

yes.
Replaced by `WEBPACK_SERVE` in `webpack-cli`.
replace `WEBPACK_DEV_SERVER` with `WEBPACK_SERVE`.
no

feat: add WEBPACK_SERVE env variable

---

bin/cli-flags.js

N/A
The existing output of `webpack serve --help` lists descriptions beginning in a capital letter. The description for `stdin` does _not_ begin with a capital letter.
N/A
N/A

docs: fixed casing

---

lib/utils/normalizeOptions.js
test/cli/__snapshots__/cli.test.js.snap
test/server/utils/normalizeOptions.test.js

use 'public' directory as default value for 'static' 
the default directory for `static` was changed from `static` to `public`.
No

refactor: use 'public' directory as default value for 'static'

---

package-lock.json
package.json
test/cli/cli.test.js

Yes, updated tests.
update `webpack` and `webpack-cli` to lates version.
None
No

chore: update webpack and webpack-cli

---

bin/cli-flags.js

No
improve descriptions
None
None

fix: improve descriptions for CLI options

---

README.md
bin/cli-flags.js

fix: improve descriptions for negative flags

---

README.md
bin/cli-flags.js

Yet to add some.
Allow `webpack serve --firewall` and `webpack serve --no-firewall`.
None
I will add some tests if this feature is accepted.

feat: allow `Boolean` type for --firewall

---

test/cli/cli.test.js
test/server/utils/findPort.test.js

yes
add test case for `--history-api-fallback`
None
No

test: add case for --history-api-fallback

---

bin/cli-flags.js
test/cli/cli.test.js

Yes
Add some more negative flags
None
No

feat: add more negative flags

---

bin/cli-flags.js
test/cli/cli.test.js

No, need a new webpack-cli release to enable tests
Remove `--hot-only` as now cli allows `--hot=only` - https://github.com/webpack/webpack-cli/pull/2444
`--hot-only` option was removed.
None

refactor: remove `--hot-only` in favor of `--hot=only`

---

test/e2e/DevServer.test.js
test/fixtures/cli/webpack.config.js
test/fixtures/dev-server/client-custom-path-config.js
test/fixtures/dev-server/client-default-path-config.js
test/fixtures/dev-server/default-config.js
test/fixtures/dev-server/empty-entry.js
test/fixtures/dev-server/multi-entry.js
test/fixtures/dev-server/target-config.js
test/fixtures/entry-as-descriptor/webpack.config.js
test/helpers/ExitOnDonePlugin.js

N/A
`testBin` sets the config path if the second argument is not provided: https://github.com/webpack/webpack-dev-server/blob/1dde6622bf21007b5b2af44790d14481a064027d/test/helpers/test-bin.js#L15-L20
If the config path is set via the first argument (`testArgs`), it'll result in multiple config paths, leading to flaky tests and invalid results, e.g.:
```
● DevServer › should supports entry as descriptor
expect(received).toContain(expected) // indexOf
Expected substring: "foo.js"
Received string:    ""
52 |       .then((output) => {
53 |         expect(output.exitCode).toEqual(0);
> 54 |         expect(output.stdout).toContain('foo.js');
|                               ^
55 |         done();
56 |       })
57 |       .catch(done);
at test/e2e/DevServer.test.js:54:31
at runMicrotasks …
```

test(e2e): fix DevServer test

---

lib/Server.js
test/cli/__snapshots__/cli.test.js.snap
test/server/open-option.test.js

fix: use `localhost` for output and open

---

lib/utils/normalizeOptions.js
test/e2e/__snapshots__/TransportMode.test.js.snap
test/server/clientOptions-option.test.js
test/server/transportMode-option.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap

feat: enable overlay by default

---

lib/options.json
test/__snapshots__/Validation.test.js.snap
test/options.test.js

wip
Moved injectClient and injectHot properties under client as suggested by @alexander-akait 
Yes
wip on fixes

fix: move injectClient and injectHot under client property

---

test/Validation.test.js
test/__snapshots__/Validation.test.js.snap

Yes
Update tests, `injectHot` was moved to `client.needClientEntry`
No
No

test: update validation tests

---

lib/Server.js
test/cli/__snapshots__/cli.test.js.snap
test/cli/cli.test.js
test/helpers/test-bin.js
test/server/open-option.test.js

fix: prefer to open the `host` option

---

README.md
bin/cli-flags.js
lib/Server.js
lib/options.json
lib/utils/createDomain.js
test/__snapshots__/Validation.test.js.snap
test/cli/__snapshots__/cli.test.js.snap
test/cli/cli.test.js
test/options.test.js
test/server/utils/createDomain.test.js

Yes
Improve `host` option by merging with `use-local-ip`. 
Now `host` option can accept - `local-ip`, `local-ipv4`, `local-ipv6`.
`useLocalIp` option was removed.

feat: improve `host` option

---

.gitignore
bin/cli-flags.js
lib/Server.js
lib/options.json
test/__snapshots__/Validation.test.js.snap
test/options.test.js
test/ports-map.js
test/server/watchFiles-option.test.js

wip on tests
Add watchFiles option to listen to user-defined file changes
Nope
Fix https://github.com/webpack/webpack-dev-server/issues/3121

feat: add watchFiles option

---

README.md
bin/cli-flags.js
test/cli/cli.test.js

Yes
improve descriptions add more test cases.
None
No

fix: improve descriptions for `--no-open` and `--no-open-target`

---

README.md
bin/cli-flags.js
test/cli/__snapshots__/cli.test.js.snap.webpack4
test/cli/__snapshots__/cli.test.js.snap.webpack5

No
We have some additional flags currently present only with webpack-cli v4.6.0 -
`--no-bonjour`
`--no-client-progress`
`--no-open`
`--no-open-target`
None
No

fix: syncronize cli-flags for `webpack-cli < v4.6.0`

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/validate-options.test.js

NA
Error messages are unused.
No

chore: migrate error messages on descriptions

---

test/cli/__snapshots__/cli.test.js.snap.webpack4
test/cli/__snapshots__/cli.test.js.snap.webpack5
test/cli/cli.test.js
test/helpers/test-bin.js

yes added snapshots
use snapshots for tests.
No
No

test: migrate to snapshots

---

test/fixtures/client-config/webpack.config.js
test/fixtures/contentbase-config/webpack.config.js
test/fixtures/historyapifallback-2-config/webpack.config.js
test/fixtures/historyapifallback-3-config/webpack.config.js
test/fixtures/historyapifallback-config/webpack.config.js
test/fixtures/mime-types-config/webpack.config.js
test/fixtures/module-federation-config/webpack.config.js
test/fixtures/module-federation-config/webpack.multi.config.js
test/fixtures/module-federation-config/webpack.object-entry.config.js
test/fixtures/module-federation-config/webpack.plugin.js
test/fixtures/multi-compiler-config/webpack.config.js
test/fixtures/multi-public-path-config/webpack.config.js
test/fixtures/provide-plugin-sockjs-config/webpack.config.js
test/fixtures/provide-plugin-ws-config/webpack.config.js
test/fixtures/proxy-config/webpack.config.js
test/fixtures/reload-config-2/webpack.config.js
test/fixtures/reload-config/webpack.config.js
test/fixtures/simple-config-other/webpack.config.js
test/fixtures/simple-config/webpack.config.js
test/fixtures/universal-compiler-config/webpack.config.js
test/server/stats-option.test.js

NA
Disables unnecessary logs form middleware.
No
No

fix: disable middleware logs in CI

---

lib/utils/DevServerPlugin.js
test/server/clientOptions-option.test.js

Yes
In version `4.0.0-beta.2` it still uses old option `injectHot` and `injectClient` to determine whether to inject dev server client, this PR corrects that by respecting new option `client.needHotEntry` and `client.needClientEntry`. 
No
N/A

fix: respect client.needHotEntry and client.needClientEntry

---

lib/utils/runOpen.js
test/server/open-option.test.js

fix: improve waring message for `open`

---

lib/options.json
lib/utils/runBonjour.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/server/bonjour-option.test.js
test/validate-options.test.js

wip
Allows options from bonjour for more configuration - https://github.com/watson/bonjour#initializing
no

feat: bonjour options

---

lib/Server.js
test/cli/cli.test.js

updated existing tests.
Move this log to webpack-dev-middleware.

refactor: remove publicPath log

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/validate-options.test.js

Yes
Output more useful information.
None
No

fix: output description for static options

---

lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/server/https-option.test.js
test/validate-options.test.js

Updated existing tests.
Refers https://github.com/webpack/webpack-dev-server/issues/2996
BREAKING CHANGE: `https.ca` was removed
After this, I will finish https://github.com/webpack/webpack-dev-server/pull/3241

feat: add `https.cacert`

---

README.md
bin/cli-flags.js
test/cli/__snapshots__/cli.test.js.snap.webpack4
test/cli/__snapshots__/cli.test.js.snap.webpack5
test/cli/cli.test.js

Yep WIP
Fixes https://github.com/webpack/webpack-dev-server/issues/2996
Allow following flags - 
-  `--https-passphrase <value>` 
-  `--https-key <value>`           
-  `--https-pfx <value>`          
-  `--https-cert <value>` 
-  `--https-cacert <value>`        
-  `--https-request-cert`      
-  `--no-https-request-cert`        
None
No

feat: add more `https` option related cli flags

---

client-src/index.js
client-src/overlay.js
client-src/socket.js
client-src/utils/sendMessage.js
lib/Server.js
test/client/__snapshots__/index.test.js.snap.webpack4
test/client/__snapshots__/index.test.js.snap.webpack5

bug, existing
When we set `overlay: true` we mean `overlay: { warnings: true, errors: true }`, but current logic is not show warnings in overlay by defualt, also we have bug when we show warning and invalidate code warnings just hide
In theory no, because `overlay: true` should show warnings and errors
No

fix: overlay with warnings

---

lib/Server.js
test/cli/__snapshots__/cli.test.js.snap.webpack4
test/server/proxy-option.test.js

fixes #3234
respect `logLevel` and `logProvider` option for proxy
No
No

fix: respect `logLevel` and `logProvider` option for proxy

---

lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/server/headers-option.test.js
test/validate-options.test.js

yes
allow headers function for customizability
no

feat: support fn in headers option

---

lib/Server.js
lib/options.json
lib/utils/findPort.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/server/port-option.test.js
test/validate-options.test.js

updated
add port "auto" because we resolve port on own when it's not supplied

feat: add port auto

---

lib/Server.js

No, Already present.
Reduce import at startup. 
None
No

refactor: imports

---

.github/ISSUE_TEMPLATE.md

Ask for `webpack-cli` version.
None
No

chore: ask for webpack-cli version in issue template

---

test/server/Server.test.js
test/server/utils/createDomain.test.js

N/A
This is cherry-picked from #3039. As the dev-server will become a plugin (#3251), it'd imply one instance per one compiler, so #3039 wouldn't be necessary.
This PR only fixes the relevant test cases, reusing the compiler across multiple server instances.
N/A
Closes #3033 and closes #3039.

test(server): recreate compiler before each test

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5

No need
for https://github.com/webpack/webpack-dev-server/pull/3300#issuecomment-843406739
No
No

refactor: fix schema

---

lib/utils/DevServerPlugin.js
test/e2e/TransportMode.test.js
test/e2e/__snapshots__/TransportMode.test.js.snap.webpack4
test/e2e/__snapshots__/TransportMode.test.js.snap.webpack5

YES
When the port was not specified in config -
None
No

fix: web socket url generation

---

README.md
bin/cli-flags.js
test/cli/__snapshots__/cli.test.js.snap.webpack4
test/cli/__snapshots__/cli.test.js.snap.webpack5
test/cli/cli.test.js

fix: imporove processing of CLI flags

---

client-src/index.js
lib/Server.js
test/client/__snapshots__/index.test.js.snap.webpack4
test/client/__snapshots__/index.test.js.snap.webpack5
test/client/index.test.js

Yes
Fix https://github.com/webpack/webpack-dev-server/issues/3217
None
No

fix: show plugin name in progress log

---

client-src/index.js
lib/Server.js
test/client/__snapshots__/index.test.js.snap.webpack4
test/client/__snapshots__/index.test.js.snap.webpack5
test/client/index.test.js

fix: improve message for static content changes

---

lib/Server.js
lib/utils/normalizeOptions.js

Existing 
We have an option normalizer which deals with option normalization and hence is a better candidate for this computation
nope

refactor: move https normalization

---

README.md
examples/cli/web-socket-url/README.md
test/e2e/web-socket-server-and-url.test.js

NA
docs update
no
After https://github.com/webpack/webpack-dev-server/pull/3309

docs: remove public

---

lib/options.json
lib/utils/DevServerPlugin.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/server/host-option.test.js
test/validate-options.test.js

No need
If you want to use `0.0.0.0` (i.e. default) just don't set the `host` option or set it to `0.0.0.0` (same for IPv6)
Yes
No

fix: host can't be null or empty string

---

bin/cli-flags.js
examples/cli/web-socket-url/webpack.config.js
lib/Server.js
lib/options.json
lib/utils/normalizeOptions.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/cli.test.js.snap.webpack4
test/cli/__snapshots__/cli.test.js.snap.webpack5
test/cli/cli.test.js
test/e2e/web-socket-server-and-url.test.js
test/server/Server.test.js
test/server/allowedHosts-option.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack4
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack5
test/server/utils/normalizeOptions.test.js
test/validate-options.test.js

existing 
add more verbose option, firewall was misleading
yep

fix: migrate firewall to allowedHosts option

---

lib/options.json
lib/utils/normalizeOptions.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/e2e/web-socket-server-and-url.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack4
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack5
test/server/utils/normalizeOptions.test.js
test/validate-options.test.js

Allow string for `client.webSocketURL.port`
None
No

feat: allow string value for `port`

---

lib/Server.js
lib/servers/WebsocketServer.js
test/server/servers/WebsocketServer.test.js

existing 
consistent
no
More after https://github.com/webpack/webpack-dev-server/pull/3291

refactor: ws var

---

lib/Server.js
test/server/__snapshots__/watchFiles-option.test.js.snap.webpack4
test/server/__snapshots__/watchFiles-option.test.js.snap.webpack5
test/server/watchFiles-option.test.js

yet to
Fix https://github.com/webpack/webpack-dev-server/issues/3365
no

fix: polling usage in watchFiles option

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/validate-options.test.js

Yes
Don't allow empty strings for the `port` option.
None
No

fix: do not allow empty string for `port`

---

bin/cli-flags.js
test/cli/__snapshots__/cli.test.js.snap.webpack4
test/cli/__snapshots__/cli.test.js.snap.webpack5
test/cli/cli.test.js

No
allow string values to be accepted by `--port`.
None
No

fix: `--port` flag parsing

---

client-src/utils/createSocketURL.js
lib/options.json
lib/utils/DevServerPlugin.js
lib/utils/normalizeOptions.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/e2e/web-socket-server-and-url.test.js

WIP on tests
When you proxy webpack dev server and proxy uses https you can't change protocol of web socket client URL without this feature
No
No

feat: allow to set `client.webSocketURL.protocol`

---

lib/Server.js
test/server/Server.test.js
test/server/allowedHosts-option.test.js

fix: rename methods

---

lib/Server.js
test/server/historyApiFallback-option.test.js

wip on tests
when user enables logs we use inbuilt logger to log the stats
no

fix: pass own logger in historyApiFallback

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5

Updated snapshots.
Add link for `hostoryApiFallback` options.
None
No

fix: add link for `historyApiFallback` options

---

examples/cli/host-and-port/README.md

docs: update `port` example

---

.github/workflows/nodejs.yml
test/helpers/test-bin.js

no
run tests on more node versions
no

fix: add node 16 on ci

---

examples/cli/web-server-socket/README.md
examples/cli/web-server-socket/app.js
examples/cli/web-server-socket/webpack.config.js

yes
Add `--web-socket-server`.
None
No

docs: add `--web-socket-server`

---

lib/Server.js
lib/utils/DevServerPlugin.js

no need, existing
Do not use webpack directly, because on the top can exists webpack v4 and it will break logic
No
No

refactor: do not use webpack directly

---

lib/utils/DevServerPlugin.js

refactor: code

---

test/e2e/web-socket-server-and-url.test.js

more test cases -
- test port on `auto`
- test port on `80`
- client.webSocketURL.port on `0` option
- `host` on ipv4 
None
No

test: more cases for webSocketURL

---

lib/Server.js
lib/servers/SockJSServer.js
test/server/webSocketServer-option.test.js

refactor name of properties
Better naming
In theory yes, if you use properties
We still need refactor our `servers`, I will do it late

refactor: rename properties

---

test/cli/basic.test.js
test/integration/MultiCompiler.test.js
test/integration/UniversalCompiler.test.js
test/server/client-option.test.js
test/server/compress-option.test.js
test/server/headers-option.test.js
test/server/historyApiFallback-option.test.js
test/server/host-option.test.js
test/server/hot-option.test.js
test/server/http2-option.test.js
test/server/https-option.test.js
test/server/mimeTypes-option.test.js
test/server/port-option.test.js
test/server/proxy-option.test.js
test/server/static-directory-option.test.js
test/server/static-publicPath-option.test.js
test/server/webSocketServer-option.test.js

it is tests
migrated on async await to avoid sync problems
no

refactor: tests

---

README.md
bin/cli-flags.js
lib/options.json
lib/utils/DevServerPlugin.js
lib/utils/normalizeOptions.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
test/cli/client-option.test.js
test/e2e/__snapshots__/web-socket-server-url.test.js.snap.webpack4
test/e2e/__snapshots__/web-socket-server-url.test.js.snap.webpack5
test/e2e/web-socket-server-url.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack4
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack5
test/server/utils/normalizeOptions.test.js
test/validate-options.test.js

existing 
stick to URL spec
shouldn't

fix: webSocketURL path option

---

bin/cli-flags.js
package-lock.json
package.json
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

existing 
upgrade deps
no
https://github.com/webpack/webpack-dev-server/pull/3470

chore: upgrade webpack

---

examples/api/simple/server.js
examples/util.js
lib/utils/normalizeOptions.js
test/e2e/hot-and-live-reload.test.js
test/e2e/logging.test.js
test/e2e/overlay.test.js
test/e2e/stats.test.js
test/e2e/web-socket-communication.test.js
test/server/Server.test.js
test/server/utils/DevServerPlugin.test.js
test/server/utils/normalizeOptions.test.js

refactor: prevent object mutation and use spread

---

test/e2e/__snapshots__/entry.test.js.snap.webpack4
test/e2e/__snapshots__/entry.test.js.snap.webpack5
test/e2e/entry.test.js
test/fixtures/client-config/bar.js
test/fixtures/client-config/foo.js
test/fixtures/client-config/webpack.config.js
test/ports-map.js
test/server/utils/DevServerPlugin.test.js

tests
entry tests
No
also remove old bad tests

test: entry

---

examples/cli/compression/README.md
examples/cli/default/README.md
examples/cli/history-api-fallback/README.md
examples/cli/hmr/README.md
examples/cli/host-and-port/README.md
examples/cli/https/README.md
examples/cli/multi-compiler/README.md
examples/cli/node-false/README.md
examples/cli/overlay/README.md
examples/cli/progress/README.md
examples/cli/watch-static/README.md
examples/cli/web-server-socket/README.md
examples/cli/web-socket-url-cli/README.md
examples/general/config-array/README.md
examples/general/config-promise/README.md
examples/general/proxy-advanced/README.md
examples/general/proxy-hot-reload/README.md
examples/general/proxy-simple/README.md
examples/general/universal-config/README.md

NA
`--open` is simpler. https://github.com/webpack/webpack-dev-server/pull/3505#pullrequestreview-698402513
None
No

docs: use `--open`

---

README.md
bin/cli-flags.js
lib/options.json
lib/utils/DevServerPlugin.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
test/cli/client-option.test.js
test/e2e/__snapshots__/web-socket-server-and-transport.test.js.snap.webpack4
test/e2e/__snapshots__/web-socket-server-and-transport.test.js.snap.webpack5
test/e2e/web-socket-server-and-transport.test.js
test/server/client-option.test.js
test/server/utils/DevServerPlugin.test.js
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack4
test/server/utils/__snapshots__/normalizeOptions.test.js.snap.webpack5
test/server/utils/normalizeOptions.test.js
test/server/webSocketServer-option.test.js
test/validate-options.test.js

Yes
remove `client.transport` in favor of `client.webSocketTransPort`
yes, `client.transport` was removed in favor of `client.webSocketTransPort`
None

refactor: remove `client.transport` in favor of `client.webSocketTransport`

---

README.md
bin/cli-flags.js
lib/options.json
package-lock.json
package.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

feat: display documentation links on errors

---

README.md
bin/cli-flags.js
lib/Server.js
lib/options.json
lib/utils/DevServerPlugin.js
lib/utils/normalizeOptions.js
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack4
test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack5
test/e2e/__snapshots__/web-socket-server-and-transport.test.js.snap.webpack4
test/e2e/__snapshots__/web-socket-server-and-transport.test.js.snap.webpack5
test/e2e/hot-and-live-reload.test.js
test/e2e/web-socket-server-and-transport.test.js
test/validate-options.test.js

WIP on more tests
Allow to disable web socket server, i.e. developer can implement own full featured web socket server
Yes, hot/liveReload do not enable/disable web socket server, no magic here more
No

Feat allow to disable web socket server

---

client-src/modules/logger/index.js
client-src/webpack.config.js

Tested manually
Avoid Symbol use when they are not supported
No
fixed #3502

fix: get rid of Symbol core-js polyfill

---

bin/cli-flags.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5

Existing
fix schema
No
Also update options for CLI

fix: schema for the `host` option

---

client-src/overlay.js
package-lock.json
package.json
test/e2e/__snapshots__/overlay.test.js.snap.webpack4
test/e2e/__snapshots__/overlay.test.js.snap.webpack5
test/e2e/overlay.test.js

Yes
Fix https://github.com/webpack/webpack-dev-server/issues/3552
No
No

fix: overlay content

---

lib/Server.js
test/server/Server.test.js
test/server/__snapshots__/Server.test.js.snap.webpack4
test/server/__snapshots__/Server.test.js.snap.webpack5

WIP ON TESTS
SHOW DEPRECATION WARNING
NO
NO

fix: show deprecation warning for incorrect usage of Node.js API

---

.github/workflows/nodejs.yml

yet to
use inbuilt node cache
no
https://github.com/actions/setup-node#caching-packages-dependencies

chore: use default node cache for deps

---

client-src/overlay.js
package-lock.json
package.json
test/e2e/__snapshots__/overlay.test.js.snap.webpack4
test/e2e/__snapshots__/overlay.test.js.snap.webpack5
test/e2e/overlay.test.js

yes, added a test to replicate the issue / cover ansi formatting
Fixes the ansi formatting in the overlay - want to use the overlay in the CRA project see #3575 for more info an ways to replicate
none
fixed #3575

fix(overlay): render ansi formattet error messages correctly

---

lib/Server.js
package-lock.json
package.json

Avoid using dep for few lines of code.
None
No

refactor: remove `is-absolute-url` in favor of method

---

lib/Server.js

Already present
avoid unnecessary or redundant arguments to methods
No
No

refactor: avoid unnecessary arguments to methods

---

package.json

No, this is a metadata update.
When webpack-dev-server is run on any webpack version < 4.37, this error appears.
[webpack-cli] TypeError: compiler.getInfrastructureLogger is not a function
This is because `compiler.getInfrastructureLogger` is introduced in webpack v4.37, therefore webpack-dev-server is not compatible with any version of webpack below it.
None.
We hit this error when using `webpack-dev-server@4.0.0-rc.0` with `webpack@4.33.0`.

fix: update webpack peer dependency to ^4.37.0

---

lib/Server.js
test/fixtures/client-config/webpack.config.js
test/fixtures/multi-compiler-config/webpack.config.js
test/fixtures/overlay-config/foo.js
test/fixtures/overlay-config/webpack.config.js
test/fixtures/provide-plugin-custom/webpack.config.js
test/fixtures/provide-plugin-default/webpack.config.js
test/fixtures/provide-plugin-sockjs-config/webpack.config.js
test/fixtures/provide-plugin-ws-config/webpack.config.js
test/fixtures/reload-config-2/webpack.config.js
test/fixtures/reload-config/webpack.config.js
test/fixtures/simple-config/webpack.config.js
test/server/Server.test.js
test/server/__snapshots__/Server.test.js.snap.webpack4
test/server/__snapshots__/Server.test.js.snap.webpack5

yes
Fix https://github.com/webpack/webpack-dev-server/pull/2889
None
No

fix: respect infastructureLogging.level for client.logging

---

lib/Server.js
test/server/proxy-option.test.js

fixes #3486 fixes #3647
fixes
No
TODO for the next major release

fix: proxy logging and allow to pass options without the `target` option

---

test/e2e/__snapshots__/web-socket-communication.test.js.snap.webpack4
test/e2e/__snapshots__/web-socket-communication.test.js.snap.webpack5
test/e2e/web-socket-communication.test.js

test: fix todo

---

lib/Server.js
lib/servers/BaseServer.js
lib/servers/SockJSServer.js
lib/servers/WebsocketServer.js
package-lock.json
package.json
test/e2e/web-socket-communication.test.js
test/server/setupExitSignals-option.test.js

refactor: remove `killable`

---

test/e2e/web-socket-server-url.test.js

it is test
stability test
No
No

test: fix stability

---

lib/Server.js
test/e2e/__snapshots__/api.test.js.snap.webpack4
test/e2e/__snapshots__/api.test.js.snap.webpack5
test/e2e/api.test.js

fix: legacy API

---

test/e2e/ipc.test.js

no
remove redundant console statements
No
No

chore: remove redundant console statements

---

lib/Server.js
test/cli/__snapshots__/bonjour-option.test.js.snap.webpack4
test/cli/__snapshots__/bonjour-option.test.js.snap.webpack5
test/cli/__snapshots__/http2-option.test.js.snap.webpack4
test/cli/__snapshots__/http2-option.test.js.snap.webpack5
test/cli/__snapshots__/https-option.test.js.snap.webpack4
test/cli/__snapshots__/https-option.test.js.snap.webpack5
test/cli/bonjour-option.test.js
test/cli/http2-option.test.js
test/cli/https-option.test.js
test/helpers/test-bin.js

yep
Allow to easy import `pem` for localhost
No
No

fix: improve https CLI output

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5

Improve error output by adding more links.
None
No

fix: output documentation link on errors

---

migration-v4.md

n/a
Turns out, `webpack-cli@<=4.4.0` crashes on `webpack serve` command when used with `webpack-dev-server@4.0.0`. 
To prevent users from getting stuck or raising unnecessary bug reports, minimum compatible `webpack-cli` shall be mentioned in migration docs.
n/a
Crash on webpack-cli 4.2.0:
```
/node_modules/webpack-cli/lib/utils/arg-parser.js:59
options.reduce((parserInstance, option) => {
^
TypeError: Cannot read property 'reduce' of undefined
at argParser (/node_modules/webpack-cli/lib/utils/arg-parser.js:59:13)
at WebpackCLI.argParser (/node_modules/webpack-cli/lib/webpack-cli.js:63:16)
at Object.parseArgs [as default] (/node_modules/@webpack-cli/serve/lib/parseArgs.js:26:37)
at serve (/node_modules/@webpack-cli/serve/lib/index.js:46:63)
at run …
```

docs: mention webpack-cli in migration docs

---

migration-v4.md

no need
https://github.com/webpack/webpack-dev-server/issues/3674
No
No

docs: improve migration guide

---

test/e2e/multi-compiler.test.js
test/e2e/universal-compiler.test.js
test/server/Server.test.js

use latest API methods
None
No

test: use latest API methods

---

test/e2e/lazy-compilation.test.js
test/fixtures/lazy-compilation-multiple-entries/one.js
test/fixtures/lazy-compilation-multiple-entries/two.js
test/fixtures/lazy-compilation-multiple-entries/webpack.config.js
test/fixtures/lazy-compilation-single-entry/entry.js
test/fixtures/lazy-compilation-single-entry/webpack.config.js

fixes #3204
test for lazy multi entries
No
webpack has bug with closing, so jest is freeze, tests are fine and work, but jest freeze, we should uncomment them when webpack fix the bug (already reported)

test: issue 3204

---

test/e2e/built-in-routes.test.js

No
use the corresponding port for `built-in-routes.test.js`
No
No

test: use the corresponding port for built-in-routes test

---

test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/validate-options.test.js

Yes
add validation test for `liveReload` option.
None
No

test: add validation tests for `liveReload` option

---

migration-v4.md

NA
It seems some problems with webpack-cli v4.6.0 so marking 4.7.0 as minimum supported version https://github.com/webpack/webpack-dev-server/pull/3682#issuecomment-903468936
no

docs: mark webpack-cli 4.7.0 as min version for dev server v4

---

lib/Server.js
test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack4
test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack5
test/e2e/allowed-hosts.test.js
test/server/__snapshots__/Server.test.js.snap.webpack4
test/server/__snapshots__/Server.test.js.snap.webpack5

not yet, will add once this fix is validated
Fix https://github.com/webpack/webpack-cli/issues/2909
no

fix: normalize for allowedHosts

---

lib/Server.js

refactor: use async API

---

lib/Server.js
test/server/hot-option.test.js

WIP on tests.
show users a warning when `hot` is enabled with the HMR plugin in the configuration
None
No

fix: show warning when `hot` is enabled with the HMR plugin in config

---

test/e2e/__snapshots__/built-in-routes.test.js.snap.webpack4
test/e2e/__snapshots__/built-in-routes.test.js.snap.webpack5
test/e2e/built-in-routes.test.js
test/e2e/universal-compiler.test.js

No
refactor e2e test to use `response.text()` for consistency with other tests + avoid extra code.
None
No

test: refactor e2e test to use `response.text()`

---

lib/Server.js

N/A
This PR refactors `Server.js`, removing redundant inner functions introduced in #3714.
No

refactor(Server): remove redundant inner functions

---

README.md
bin/cli-flags.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

No
improve the description of `magicHtml` option
None
No

fix: improve description of `magicHtml` option

---

test/e2e/module-federation.test.js

No
refactor e2e test to use `response.text()` for consistency with other tests + avoid extra code.
Follow up https://github.com/webpack/webpack-dev-server/pull/3761
None
No

test: refactor to use `response.text()`

---

client-src/overlay.js
package-lock.json
package.json

This fixes the ReDoS vulnerability CVE-2021-23424
I only replaced a dependency which has tests on its own.
Fixes #3576
Replaces #3798
None

fix: replace ansi-html with ansi-html-community

---

examples/headers/function/README.md
examples/headers/function/app.js
examples/headers/function/webpack.config.js
examples/headers/object/README.md
examples/headers/object/app.js
examples/headers/object/webpack.config.js

add `headers` option example.
None
None

docs: add `headers` option example

---

client-src/index.js
test/e2e/__snapshots__/overlay.test.js.snap.webpack4
test/e2e/__snapshots__/overlay.test.js.snap.webpack5
test/e2e/overlay.test.js

Yes
close overlay when connection is disconnected 
No
Also it fixed duplicate errors/warnings after stop and run again server

fix: close overlay on disconnection

---

test/e2e/__snapshots__/magic-html.test.js.snap.webpack4
test/e2e/__snapshots__/magic-html.test.js.snap.webpack5
test/e2e/magic-html.test.js

Added more assertions.
Add snapshots for page errors like the rest of the tests.
None
No

test: add snapshots for page errors

---

examples/headers/array/README.md
examples/headers/array/app.js
examples/headers/array/webpack.config.js
lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/e2e/__snapshots__/headers.test.js.snap.webpack4
test/e2e/__snapshots__/headers.test.js.snap.webpack5
test/e2e/headers.test.js
test/validate-options.test.js

Yes
allow array for `headers` option :- 
```js
headers: [
{
key: "X-Foo",
value: "value1",
},
{
key: "X-Bar",
value: "value2",
},
],
```
None
No

feat: allow array for `headers` option

---

test/server/client-option.test.js
test/server/hot-option.test.js

No
Move`hot: false` test to `hot-option.test.js` from `client-option.test.js`
None
No

test: move test case to appropriate place

---

examples/api/stop-callback/README.md
examples/api/stop-callback/app.js
examples/api/stop-callback/server.js
examples/api/stop-callback/webpack.config.js

No
add `stopCallback` method example.
None
No

docs: add `stopCallback` method example

---

client-src/overlay.js

since there is no test for overlayer yet, so I did not add test for it
we are not display filename in webpack5 for error now
compare to error ovelay in webpack-dev-server V3
no
add filename for error

fix: display file name in overlay

---

client-src/index.js
client-src/overlay.js
test/client/__snapshots__/index.test.js.snap.webpack4
test/client/__snapshots__/index.test.js.snap.webpack5
test/client/index.test.js
test/e2e/__snapshots__/logging.test.js.snap.webpack4
test/e2e/__snapshots__/logging.test.js.snap.webpack5
test/e2e/__snapshots__/overlay.test.js.snap.webpack4
test/e2e/__snapshots__/overlay.test.js.snap.webpack5

Yes
Better output for errors/warnings
No
No

fix: formatting errors/warnings

---

lib/Server.js
test/server/setupExitSignals-option.test.js

feat: gracefully and force shutdown

---

client-src/socket.js
lib/Server.js
test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack4
test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack5
test/e2e/__snapshots__/web-socket-server.test.js.snap.webpack4
test/e2e/__snapshots__/web-socket-server.test.js.snap.webpack5
test/e2e/progress.test.js
test/e2e/web-socket-server.test.js
test/ports-map.js

fix: avoid connection when web socket server is not running

---

examples/README.md

No
Update README. `cli` directory is no longer present.

docs: udpate examples README

---

test/e2e/__snapshots__/client.test.js.snap.webpack4
test/e2e/__snapshots__/client.test.js.snap.webpack5
test/e2e/client.test.js

Yes
add e2e tests for `client` option.
None
No

test: add e2e tests for `client` option

---

bin/cli-flags.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/validate-options.test.js

Yes
`false` is allowed only on for whole option, not for type
No, because it was broken before
No

fix: schema for web socket server type

---

test/e2e/__snapshots__/server.test.js.snap.webpack4
test/e2e/__snapshots__/server.test.js.snap.webpack5
test/e2e/server.test.js
test/helpers/custom-http.js

Yes
`server` can not be any string because we use it to require a node module. https://github.com/webpack/webpack-dev-server/blob/6d060ed68992875d82a0a77a2a5bf9d67d46817e/lib/Server.js#L1591
No
No

fix: schema for `server` option

---

lib/Server.js
test/e2e/http2.test.js
test/e2e/https.test.js

yes
show deprecation warning for `https`/`http2` option.
None
No

feat: show deprecation warning for `https`/`http2` option

---

README.md
bin/cli-flags.js
lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
test/cli/webSocketServer-option.test.js

add `--web-socket-server-type` option for CLI. Add todo to remove `--web-spcket-server`.
None
No

feat: add `--web-socket-server-type` option for CLI

---

client-src/default/overlay.js
package-lock.json
package.json

This fixes the ReDoS vulnerability CVE-2021-23424 & #3929
No, since this is swapping out a library so the existing tests should cover the change.
Resolves a security vulnerability.
None
Closes #3813

fix: replace `ansi-html` with `ansi-html-community`

---

lib/Server.js
test/e2e/bonjour.test.js

No
fix memory leak warnings in e2e tests.
None
No

fix: remove process listeners after stopping the server

---

examples/client/reconnect/false/README.md
examples/client/reconnect/number/README.md
examples/client/reconnect/true/README.md
examples/compression/false/README.md

chore: fix typo

---

lib/Server.js
test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack4
test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack5
test/e2e/allowed-hosts.test.js

Added a new test that successfully fails with `client.terminate`
See #3997. When host/origin headers do not match, `client.terminate` was being called. However, when HTTPS is enabled, this message is encrypted asynchronously by NodeJS before it gets written to the socket. Therefore, when `client.terminate` destroys the underlying socket the previous `sendMessage` had not yet been written to the socket.
Only applies when HTTPS is enabled.
Using `client.close` ensures that the socket is closed after all data is sent.
None
Granted, with a bad client, this could leak forever as there is no timeout. However, I do not see timeouts elsewhere so they could be added as part of adding them elsewhere. It's also a development tool that is unlikely to be very long lived, and will be extremely easy to …

fix: invalid host message is missing on clientwith https (#3997)

---

lib/Server.js

No
remove redundant `eslint-disable` comments
None
No

chore: remove redundant `eslint-disable` comments

---

client-src/index.js
client-src/socket.js
lib/Server.js
package-lock.json
test/client/__snapshots__/socket-helper.test.js.snap.webpack4
test/client/__snapshots__/socket-helper.test.js.snap.webpack5
test/client/socket-helper.test.js
test/e2e/hot-and-live-reload.test.js

fix: reload on warnings

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/validate-options.test.js

Yes
Add description for `watchFiles` options.
None
No

fix: add description for `watchFiles` options

---

lib/Server.js
test/e2e/http2.test.js

Yes
show deprecation warning for both `https` and `http2` when used together.
None
No

fix: show deprecation warning for both `https` and `http2`

---

test/e2e/logging.test.js
test/e2e/overlay.test.js
test/e2e/progress.test.js

No
use `graceful-fs` instead of `fs` module.
None
No

chore: use `graceful-fs`

---

bin/cli-flags.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

Yes, updated snapshots.
Fix typo in schema.
None
No

fix: correct schema for `ClientLogging`

---

README.md
bin/cli-flags.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

-  update descriptions of `https` options to be shorter.
- Add deprecated info in `server.options.cacert` option.
None
No

fix: update descriptions of `https` and `server` options

---

test/e2e/__snapshots__/api.test.js.snap.webpack4
test/e2e/__snapshots__/api.test.js.snap.webpack5
test/e2e/api.test.js

It is test.
add assertion for deprecation warning message.
None
No

test: add assertion for deprecation warning message

---

README.md
bin/cli-flags.js
lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

mark `--open-app` deprecated in favor of `--open-app-name` because they are duplicate flags.
Also, add TODO to remove `--open-app`.
No
No

fix: mark `--open-app` deprecated in favor of `--open-app-name`

---

lib/Server.js
test/e2e/__snapshots__/api.test.js.snap.webpack4
test/e2e/__snapshots__/api.test.js.snap.webpack5
test/e2e/api.test.js

Yes
update `listen` and `close` deprecation warning message.
None
No

fix: update `listen` and `close` deprecation warning message

---

README.md
bin/cli-flags.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

No
update `--web-socket-server` description.
None
No

fix: update `--web-socket-server` description

---

lib/options.json
test/e2e/__snapshots__/server.test.js.snap.webpack4
test/e2e/__snapshots__/server.test.js.snap.webpack5
test/e2e/server.test.js
test/validate-options.test.js

Yes
We already allow `server: "own-server-package"`, so update schema to allow` server: { type: "own-server-package" }`
None
No

fix: allow to pass options for custom server

---

test/e2e/__snapshots__/api.test.js.snap.webpack4
test/e2e/__snapshots__/api.test.js.snap.webpack5
test/e2e/api.test.js
test/server/Server.test.js

refactor
- refactor `api.test.js`
- add e2e tests for `invalidate` api method.
- remove duplicate tests from `test/server/Server.test.js`
None
No

test: add e2e tests for `invalidate` api method

---

lib/Server.js
test/e2e/https.test.js
test/e2e/server.test.js

Yes
show deprecation warning for `cacert` option
None
No

fix: show deprecation warning for `cacert` option

---

test/e2e/__snapshots__/api.test.js.snap.webpack4
test/e2e/__snapshots__/api.test.js.snap.webpack5
test/e2e/api.test.js
test/server/Server.test.js

refactor tests
Move `checkHostHeader` tests to e2e.
None
No

test: add e2e tests for `checkHostHeader` method

---

examples/setup-middlewares/README.md
examples/setup-middlewares/app.js
examples/setup-middlewares/webpack.config.js
lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/e2e/__snapshots__/headers.test.js.snap.webpack4
test/e2e/__snapshots__/headers.test.js.snap.webpack5
test/e2e/__snapshots__/setup-middlewares.test.js.snap.webpack4
test/e2e/__snapshots__/setup-middlewares.test.js.snap.webpack5
test/e2e/headers.test.js
test/e2e/on-after-setup-middleware.test.js
test/e2e/on-before-setup-middleware.test.js
test/e2e/setup-middlewares.test.js
test/ports-map.js
test/validate-options.test.js

Yes.
```js
setupMiddleware: (arrayOfMiddlewares, devServer) => {
arrayOfMiddlewares.push('something');
return arrayOfMiddlewares;
}
```
**TODO:** 
None
No

feat: add `setupMiddlewares` option

---

test/e2e/__snapshots__/api.test.js.snap.webpack4
test/e2e/__snapshots__/api.test.js.snap.webpack5
test/e2e/api.test.js
test/server/Server.test.js

refactor
add e2e test for `WEBPACK_SERVE` env variable
None
No

test: add e2e test for `WEBPACK_SERVE` env variable

---

lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5

Updates snapshots.
update description of `onAfterSetupMiddleware` and `onBeforeSetupMiddleware` options to mark them as deprecated.
None
No

fix: update description of `onAfterSetupMiddleware` and `onBeforeSetupMiddleware`

---

.eslintrc.js
client-src/clients/SockJSClient.js
client-src/index.js
client-src/overlay.js
client-src/socket.js
client-src/utils/createSocketURL.js
client-src/utils/getCurrentScriptSource.js
client-src/utils/parseURL.js
client-src/utils/reloadApp.js
client-src/utils/sendMessage.js
client-src/webpack.config.js
package-lock.json
package.json
setupTest.js
test/e2e/__snapshots__/multi-compiler.test.js.snap.webpack5
test/e2e/api.test.js

Existing tests
fixes #4128 fixes #3862
No
Format inlined, because we don't need complex logic from `url` logic, `parse` dropped, because we need reach `else` due we because we are throwing exception if `currentScript` not found, tested for IE11, IE10 should work too

fix: drop `url` package

---

lib/Server.js

fix:Compatible with onAfterSetupMiddleware

---

lib/Server.js

Remove redundant IF statements

 Remove redundant IF statements

---

lib/Server.js
types/lib/Server.d.ts

fix: types for the `proxy` option

---

test/e2e/hot-and-live-reload.test.js
test/fixtures/reload-config/webpack.config.js

No
migrate hot and liveReload tests on `HTMLGeneratorPlugin`.
None
No

test: migrate hot and liveReload tests on `HTMLGeneratorPlugin`.

---

lib/options.json
package-lock.json
package.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
types/lib/Server.d.ts

…`
Updated snapshots.
use CLI specific description for `--open-app-name` and `--web-socket-server`.
Mark these deprecations only for CLI flags.
None
No

fix: use CLI specific description for `--open-app-name` and `--web-socket-server`

---

README.md
bin/cli-flags.js
lib/options.json
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5

updated snapshots.
update description for `--no-client-reconnect`.
None.
No

fix: update description for `--no-client-reconnect`

---

README.md
bin/cli-flags.js
lib/options.json
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
types/bin/cli-flags.d.ts
types/lib/Server.d.ts

Updated snapshots.
update description for `--no-client`.
No
No

fix: update description for `--no-client`

---

README.md
bin/cli-flags.js
lib/options.json
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
types/lib/Server.d.ts

update description for `--no-history-api-fallback`.
None
No

fix: update description for `--no-history-api-fallback`

---

bin/cli-flags.js
lib/options.json
types/bin/cli-flags.d.ts
types/lib/Server.d.ts

Already Present.
`negatedDescription` field makes sense only for type `boolean`.
None
No

fix: update schema to have `negatedDescription` only for type `boolean`

---

README.md
bin/cli-flags.js
lib/options.json
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
types/bin/cli-flags.d.ts
types/lib/Server.d.ts

Updated snaps.
Updated descriptions for `--no-client-overlay`, `--no-client-overlay-errors`, `--no-client-overlay-warnings`.
None
No

fix: update negated descriptions for more options

---

README.md

This explains how to fix a pretty common issue with the `devServer` types definition when webpack config is written in TypeScript (`'devServer' does not exist in type 'Configuration'`).

Add a note about TypeScript usage

---

client-src/index.js
client-src/modules/strip-ansi/index.js
client-src/utils/stripAnsi.js
client-src/webpack.config.js
package-lock.json
package.json
test/client/index.test.js
test/e2e/__snapshots__/multi-compiler.test.js.snap.webpack5

No new feature or bugs.
Simplify the build and tests and reduce dependencies.
Copying the `strip-ansi` source (which is one RegEx and one function testing a string against that) 
1. gets rid of `strip-ansi@7` and `ansi-regex` in production
2. gets rid of the the webpack config to precompile the `ansi-regex` package
3. removes the need to mock `strip-ansi` in the tests
The [original strip-ansi  source](https://github.com/chalk/strip-ansi/blob/main/index.js)

chore: embed strip-ansi dependency

---

client-src/utils/createSocketURL.js
client-src/utils/parseURL.js
test/e2e/range-header.test.js

This PR contains a:
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
None

chore: replace deprecated String.prototype.substr()

---

examples/util.js

chore: migrate script for examples on `setupMiddlewares` option

---

package-lock.json
package.json
test/e2e/__snapshots__/multi-compiler.test.js.snap.webpack5

N/A
fixes #4365 
N/A
fixes #4365

chore: update webpack

---

client-src/socket.js
test/client/socket-helper.test.js

~No new tests are added as I believe this is a simple change and no additional functionality is added, it just exposes a bit more of the private parts.~
Added a simple test for `null` value before init, and a "valid" client instance after init.
Fixes #4261
Fixes #4324
I chose the simplest way to expose the initialized client, so consumers can just import the file and use it - but I'm also ok with setting it to some globals (on `globalThis`/`window`) if you think that's better (I'm unsure if mutable exports are implemented properly when compiled?).

feat: export initialized socket client

---

lib/Server.js
lib/getPort.js
package-lock.json
package.json
test/e2e/api.test.js
test/server/get-port.test.js
types/lib/Server.d.ts
types/lib/getPort.d.ts

Fix #4383 
- Get rid of security warnings related to async dependencies
- Drop lodash from prod.
- The implementation is based mostly on the get-port package, but searches for ports incrementing by 1 like portfinder and I;ve added TypeScript annotations.
I've added new unit tests for the custom port finder implementation.
Remove dependency on vulnerable package async, also remove dependency on lodash.
There should be no breaking changes.
I am in doubt whether to go with this or the get-port package as in https://github.com/ludofischer/webpack-dev-server/tree/switch-port-finder
The code is a bit complex because it needs to take into account differences across operating systems, so it might be useful to rely on the expertise of the `get-port` maintainters. On the other hand there are more …

chore: replace portfinder with custom implementation

---

lib/Server.js
lib/getPort.js
test/server/get-port.test.js
types/lib/Server.d.ts
types/lib/getPort.d.ts

Yes, but it is hard to test for non-localhost hosts.
The server should check if the port is available on the host specified by the user.

fix: use the host in options to check if port is available

---

.github/workflows/nodejs.yml

I accidently pushed the last commit directly to master instead of another branch for adding node v18 on CI.
I am reverting it since the job seems to be taking longer than usual https://github.com/webpack/webpack-dev-server/runs/6144123429?check_suite_focus=true
None
No

revert: add node v18

---

package-lock.json
package.json
types/lib/Server.d.ts

chore: update deps and types

---

lib/Server.js
package-lock.json

Existing
Allow to setup https://github.com/nfriedly/express-rate-limit package (and other) to prevent a denial of service attack, We don't setup rate limits by default, because we are a development server and this is not applicable for us, but you can setup rate limit middleware using https://webpack.js.org/configuration/dev-server/#devserversetupmiddlewares
No
No

fix: security problem with sockjs

---

client-src/utils/log.js

Already present.
Fix #4543
`Object.keys` is compatible with IE9,10, and 11 - https://caniuse.com/?search=object.keys
No
No

fix: compatibility with old browsers

---

lib/Server.js

Prior to this change the internal options middleware always responded to such requests. This is because the middleware was registered too early and was not being used as a fallback. With this change we register this middleware as the last middleware to ensure that this is only used as a fallback when OPTIONS requests are not handled.
Closes #4551

fix: auto reply to OPTIONS requests only when unhandled

---

client-src/overlay.js
client-src/overlay/styles.js
test/e2e/__snapshots__/multi-compiler.test.js.snap.webpack5
test/e2e/__snapshots__/overlay.test.js.snap.webpack4
test/e2e/__snapshots__/overlay.test.js.snap.webpack5

Tweak the styles for overlay.
This is to partially resolves #3689

refactor: tweak style for overlay

---

bin/webpack-dev-server.js

No.
Porting changes from https://github.com/webpack/webpack-cli/pull/3411
Reference https://github.com/webpack/webpack-cli/issues/3355
No.
No.

fix: respect `NODE_PATH` env variable

---

lib/Server.js
types/lib/Server.d.ts

No need, existing tests
fixes https://github.com/webpack/webpack/issues/16091
No
No

fix: compatibility with `experiments.buildHttp`

---

lib/servers/SockJSServer.js

To test it we should disable websocket supporting in headless chrome (but it is impossible), as an alternative solution we can allow to set all options for sockjs server, but sockjs is old and only for old IE and Opera, I don't think many developers support it now and we should spend time on it, really, so I tested it manually and all works fine, in the next major release we will remove sockjs
fixes https://github.com/webpack/webpack-dev-server/issues/4348
No
Should we document it?

feat: allow to set  the `sockjs_url` option (only `sockjs`)

---

client-src/overlay.js
examples/client/overlay/app.js
examples/client/overlay/webpack.config.js
lib/Server.js
package-lock.json
package.json
test/e2e/__snapshots__/overlay.test.js.snap.webpack5
test/e2e/overlay.test.js
test/helpers/run-browser.js

This PR make webpack-dev-server open editor when user clicks on the error message on overlay.
Part of #3689.
- New endpoint `"/webpack-dev-server/open-editor"` is added on the dev server which the client would calls using `fetch`.
- Right now I assume `moduleIdentifier` from the `stats.errors` is the file name, but I not sure if that assumption is correct.
- Use [`launch-editor`](https://github.com/yyx990803/launch-editor) to open editor (it is based on `react-dev-utils` of Create React App, and is being used by Vite as well).
- For webpack 4 the logic does not work because there is no `moduleIdentifier`, but I assume that is not a dealbreaker.

feat: open editor when clicking error on overlay

---

client-src/index.js
test/client/__snapshots__/index.test.js.snap.webpack5
test/client/index.test.js

No.
Remove the deprecated `content-changed` method.
BREAKING CHANGE: the `content-changed` method was removed in favor of the `static-changed` method.
No

refactor!: remove the `content-changed` method from onSocketMessage

---

lib/Server.js
lib/options.json
test/cli/__snapshots__/basic.test.js.snap.webpack5
test/cli/webSocketServer-option.test.js
types/lib/Server.d.ts

Added test case for `--no-web-socket-server`.
Remove the deprecated `--web-socket-server` option.
BREAKING CHANGE: the `--web-socket-server <value>` cli option was removed in favor of the `--web-socket-server-type <value>` cli option
NO

refactor!: remove the `--web-socket-server` cli option

---

lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack5
test/server/proxy-option.test.js
test/validate-options.test.js
types/lib/Server.d.ts

Yes, updated tests to use `Array` syntax only.
Resolve TODO. 
BREAKING CHANGE: the proxy option schema now only accepts an array

refactor!: allow only Array for the proxy option

---

lib/Server.js
test/e2e/api.test.js
types/lib/Server.d.ts

Updated existing tests.
Resolve TODO.
`process.env` should be[ string values](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a6b57ed5f511b6d1c842b6acb4961c966d4afb00/types/node/process.d.ts#L112).
BREAKING_CHANGE: `WEBPACK_SERVE` value was changed from a boolean `true` to a string value `'true'`.
No.

fix: set `WEBPACK_SERVE` to string value `'true'`

---

bin/cli-flags.js
client-src/index.js
client-src/overlay.js
examples/client/overlay/webpack.config.js
lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/cli/__snapshots__/basic.test.js.snap.webpack4
test/cli/__snapshots__/basic.test.js.snap.webpack5
types/bin/cli-flags.d.ts
types/lib/Server.d.ts

Reported in #4771
fixes https://github.com/webpack/webpack-dev-server/issues/4774
fixes #4771
- Added `client.overlay.runtimeErrors` options - default to `true`.

fix: add client.overlay.runtimeErrors options

---

package.json

No, not easy to test in this repo
fixes #4776 
No

fix: make webpack optional peer dependency

---

lib/Server.js
test/server/open-option.test.js

No, but updated an old test case
`0.0.0.0` is not a good address to visit. Some developers working on Windows cannot open `0.0.0.0` in browser. 
Before this fix:
After this fix, it will open `http://localhost:8080` directly.

Fix host ip all

---

lib/Server.js
types/lib/Server.d.ts

fix(perf): reduced initial start time

---

lib/Server.js
test/server/proxy-option.test.js
types/lib/Server.d.ts

Yes.
deprecate the `bypass` option in favor of `context` and `router` options

refactor: deprecate `bypass` option in proxy

---

bin/webpack-dev-server.js

No
Same as https://github.com/webpack/webpack/pull/17088
None
No

feat: allow CLI to be ESM

---

client-src/index.js
client-src/overlay.js
client-src/overlay/state-machine.js
examples/client/overlay/app.js
examples/client/overlay/error-button.js
examples/client/overlay/webpack.config.js
lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack4
test/__snapshots__/validate-options.test.js.snap.webpack5
test/e2e/__snapshots__/overlay.test.js.snap.webpack4
test/e2e/__snapshots__/overlay.test.js.snap.webpack5
test/e2e/overlay.test.js
types/lib/Server.d.ts

- Allow filtering of overlay message
- Fix misleading overlay title when catching runtime error
Resolves
- #4777

feat: allow filter overlay message with function

---

lib/Server.js
test/server/open-option.test.js

[test/server/open-option.test.js](https://github.com/webpack/webpack-dev-server/compare/master...chousheng:webpack-dev-server:fix-ipv6-unspecified-addr-open-browser?expand=1#diff-9b579ac0614b984311440c72f67e512825ea9e553424a2360fb7503556d15625) is modified.
This PR resolves #4855. See #4855 for more details.
N/A
Below are the screencasts showing the fix on Windows and GitHub Codespaces.
Windows:
| Before fix     | After fix      |
| -------------- | -------------- |
| <video src="https://github.com/webpack/webpack-dev-server/assets/38355699/57d2fa7f-744b-47aa-b274-553351c27833"> | <video src="https://github.com/webpack/webpack-dev-server/assets/38355699/12cf49f9-03a9-49c2-b347-b0b40f271b97"> |
GitHub Codespaces:
| Before fix     | After fix      |
| -------------- | -------------- |
| …

fix: replace :: with localhost before openBrowser()

---

DOCUMENTATION-v4.md

No.
Porting the [current v4 documentation to GitHub](https://webpack.js.org/configuration/dev-server/), I will soon update the official docs to refer to v5 API only. Developers still using v4 can refer to this documentation on GitHub.
No
No

docs: add documentation reference for webpack-dev-server v4

---

package-lock.json
package.json
types/lib/servers/WebsocketServer.d.ts

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65501 changed the types for `Server`. This is making the new builds for Angular application crash. Hence bumping the `@types/ws` package to reflect those changes in this package. 
fixes https://github.com/webpack/webpack-dev-server/pull/4894

chore(deps): bump up @types/ws package

---

test/e2e/web-socket-communication.test.js

test: refactor web socket communication tests to cleanup properly

---

test/helpers/html-generator-plugin.js

refactor: remove webpack v4 code

---

lib/Server.js
test/__snapshots__/normalize-options.test.js.snap.webpack5
test/normalize-options.test.js

Yes.
Resolve TODO.
- Check if 'serveIndex' property is defined in 'optionsForStatic'
- If 'serveIndex' is a boolean and true, use default 'serveIndex'
-  If 'serveIndex' is an object, merge its properties with default 'serveIndex'
-  If 'serveIndex' is neither a boolean true nor an object, use it as-is
Yes, updated defaults.
No.

feat: improve `static.serveIndex` defaults

---

package-lock.json

ci: fix audit

---

lib/Server.js
test/server/proxy-option.test.js

yes, test cases added.
when pass a function to proxy config. every time firing `handler` function, a new proxyServer were set, and events on old proxyServer has not been cleared.
no

fix: clean 'close' event listeners on socket server after generating new proxy config.

---

lib/Server.js
test/server/proxy-option.test.js

No need, just deprecation
For better migration
No
No

refactor: improve migration

---

lib/Server.js
types/lib/Server.d.ts

No need
fixes https://github.com/webpack/webpack-dev-server/issues/5054
No
No

fix: types

---

lib/servers/WebsocketServer.js

No
Backport https://github.com/webpack/webpack-dev-server/pull/5038 to v4
Fix https://github.com/webpack/webpack-dev-server/issues/5018
No
Need to do a patch release for v4

fix: improve error handling for WebsocketServer

---

examples/general/config-array/webpack.config.js

Resolve issue in examples/general/config-array where absence of 'mode' property in second configuration object caused an error.
Fixes #5085
Not required
I am new to Open Source and was testing the examples when I found that one of the examples (fixed in this PR) is not running and giving an error. I already have created an issue (#5085) for this PR.

fix: add 'mode' property in second array object

---

lib/Server.js
types/lib/Server.d.ts

Just types
fixes https://github.com/webpack/webpack-dev-server/issues/5098
No
No

fix(types): proxy

---

package-lock.json
package.json

This is not a bug or a feature and does not need tests.
This pull request solves the vulnerability in Express that was recently discovered in all versions 4.19.1 and below. It has been fixed in version 4.19.2. The vulnerability is [CVE-2024-29041](https://nvd.nist.gov/vuln/detail/CVE-2024-29041).
This is preventing application security software such as Veracode from passing security checks for any applications that utilize webpack-dev-server. 
No Breaking changes that I am aware of.
Thank you very much!

chore: upgrading express from version 4.17.3 to version 4.19.2 due to vulnerability

---

lib/Server.js
lib/options.json
test/__snapshots__/validate-options.test.js.snap.webpack5
test/e2e/__snapshots__/app.test.js.snap.webpack5
test/e2e/app.test.js
test/fixtures/watch-files-config/webpack.config.js
types/lib/Server.d.ts

Yes
Allow to use `http2` with `connect`, `express` still doesn't support http2
No
No

feat: http2 support for `connect` compatibility application

---

client-src/progress.js
lib/Server.js
test/e2e/__snapshots__/target.test.js.snap.webpack5
test/e2e/target.test.js
test/fixtures/client-config/webpack.config.js
test/fixtures/worker-config/index.js
test/fixtures/worker-config/webpack.config.js
test/fixtures/worker-config/worker.js

Bugfix using a new ai
Resolve TODO
No
No

fix: check the `platform` property to determinate the target

---

lib/Server.js
test/cli/host-option.test.js
test/e2e/host.test.js
types/lib/Server.d.ts

bugfix
output ipv6 in console
No
No

fix: ipv6 output

---

.cspell.json
.gitignore
lib/Server.js
package-lock.json
package.json
test/e2e/__snapshots__/target.test.js.snap.webpack5
test/e2e/target.test.js
test/fixtures/worker-config-dev-server-false/index.js
test/fixtures/worker-config-dev-server-false/webpack.config.js
test/fixtures/worker-config-dev-server-false/worker.js

bugfix, ref - https://github.com/webpack/webpack-dev-middleware/pull/1921
https://github.com/webpack/webpack-dev-middleware/pull/1921
No
No

fix: support `devServer: false`

---

lib/Server.js
test/e2e/__snapshots__/client.test.js.snap.webpack5
test/e2e/client.test.js
test/fixtures/custom-client/CustomClientEntry.js
test/fixtures/custom-client/CustomClientHotEntry.js
types/lib/Server.d.ts

A test case was added in `test/e2e/client.test.js` to test that the override can take effect correctly.
Use methods to get client entries, so that users can introduce custom client entries instead by overriding these methods.
No breaking changes

refactor: use methods to get client entries

---

client-src/overlay.js
test/client/clients/ReactErrorBoundary.test.js

Yes
fixes https://github.com/webpack/webpack-dev-server/issues/5397
https://github.com/user-attachments/assets/6b65e221-dc97-4694-ba5c-eaa195913f26

fix: prevent overlay for errors caught by React error boundaries

---

lib/Server.js
test/cli/host-option.test.js

Take the first network found instead of the last one that may be the docker bridge. This restores the same behavior as 5.0.4, this fixes a regression introduced in 5.1.0 where the default-gateway dependency was dropped.
I tried to include a test and run it with
`npm run test:only test/cli/hot-option.test.js`
but I can't make it run on my machine, it's just blocking at
RUNS  test/cli/hot-option.test.js
no idea why.
I also have lots of failing tests and other files blocking like this when I'm testing on my machine.
Hopefully the CI may execute the test, finger crossed.
On version 5.0.4 with `--host local-ip` on Ubuntu, it returned
`https://192.168.1.15:8080`
On 5.1.0 and 5.2.0 it returns
`https://172.17.0.1:8080` that is the docker bridge, not so useful.
The new code introduced in #5255 was …

fix: take the first network found instead of the last one

---

examples/.assets/style.css
test/e2e/api.test.js

The test file api.test.js is unstable when "PORT" access isn't available, which results in the test suite failing.

test:  improve port handling stability in api.test.js

---

client-src/index.js

When `client.overlay` is set to `false` the resource query string will be contain `overlay=false` ([relevant code](https://github.com/webpack/webpack-dev-server/blob/1e6c003efaadb41189087f784d3be09e43a4bbea/lib/Server.js#L764-L778)). This PR fixes the `enabledFeatures` logic to handle cases when `overlay=false`
No
Fixes misleading console logs
No

fix: "Overlay enabled" false positive

---

client-src/index.js
lib/Server.js

no
simplify for loops to for...of in Server.js
no
no

refactor: simplify for loops to for...of in Server.js

---

lib/Server.js

no
- Replace if-then-else flow by a single return statement
- Use 'String#startsWith' method instead
no
no

refactor: use 'String#startsWith' & replace if-then-else

---

lib/Server.js
test/e2e/cross-origin-request.test.js
types/lib/Server.d.ts

Yes
https://github.com/webpack/webpack-dev-server/issues/5446#issuecomment-2932009087
No
fixes https://github.com/webpack/webpack-dev-server/issues/5446

fix: respect the `allowedHosts` option for cross-origin header check

---

client-src/progress.js

No, this is only a CSS addition to the progress indicator setting `pointer-events: none;` this prevents the element from sitting on top of the DOM and blocking users from being able to click on that region of their screen.
With the progress indicator enabled, the `HTMLElement` persists in the DOM and is overlaying a large portion preventing users from clicking that region even if the element is invisible.
N/A

fix: progress indicator

---

package-lock.json
package.json

N/A - This is a dependency update to fix a security vulnerability.
This PR addresses a critical security vulnerability **CVE-2024-45296** in the `path-to-regexp` dependency, which is a transitive dependency of Express.
**Vulnerability Details:**
- **CVE ID**: CVE-2024-45296
- **GHSA ID**: GHSA-9wv6-86v2-598j
- **Severity**: High (CVSS 7.7)
- **Impact**: ReDoS (Regular Expression Denial of Service) vulnerability
The vulnerability affects `path-to-regexp` versions < 0.1.10, which can generate backtracking regular expressions that consume excessive CPU cycles, potentially leading to DoS attacks.
**Changes Made:**
- Updated `express` from 4.17.3 to 4.21.2
- Updated `@types/express` from 4.17.13 to 4.17.21
- This update includes the patched version of `path-to-regexp` (0.1.12) which resolves …

chore(deps): update express and related types to their latest compatible versions
