webpack/webpack-dev-server

- lib/Server.js
> support sslPaths option for custom certificates

- package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
> Fixed invalid package.json

- lib/Server.js
I needed some more customization in the proxy configuration, so I hacked in an option to run an arbitrary function on the proxy instance.
If you like the idea, but not the approach/patch, let me know. I'll happily adjust it.
> Allow arbitrary function to configure proxy.

- bin/webpack-dev-server.js
> Allow inline mode to be set inside the config file

- client/page.jade
This attribute allows the application in the iframe to use the fullscreen API.
> Allow iframe to use browser fullscreen API

- package.json
See chimurai/http-proxy-middleware#44
> Bump http proxy middleware for websocket crash

- client/index.js
These changes are required to support hot module replacement when the bundle is run inside a web worker: https://github.com/webpack/webpack/pull/1521
> Allow hot module replacement in "webworker" targets

- bin/webpack-dev-server.js
- There is open issue #365 for this earlier this year, with appropriate PR, but conflicts are preventing it from merge
Closes #365
> FIX console.log spacing

- client/index.js
dependent pull request https://github.com/webpack/webpack-dev-server/pull/384
> fix hostname resolving on newConnection

- bin/webpack-dev-server.js
> use contentBase from webpack config - fixes #597

- lib/Server.js
See #612 
If this PR contains a breaking change, please describe the following... 
* Impact:
* Migration path for existing applications: 
* Github Issue(s) this is regarding:
> ported fix for #612 to 1.x

- package.json
Dependency update
No
**Summary**
Allow webpack 2 rc without peer dep warning
No
> Allow webpack 2 rc

- examples/webworker/README.md
- examples/webworker/index.html
- examples/webworker/web.js
- examples/webworker/webpack.config.js
- examples/webworker/worker.js
For issue https://github.com/webpack/webpack-dev-server/issues/745
> Added example "webworker"

- client/webpack.config.js
- examples/modus-inline/webpack.config.js
- examples/webpack-config-array/webpack.config.js
refactoring
they are examples :)
**Summary**
This PR is to satisfy the last todo https://github.com/webpack/webpack/issues/3195 hopefully. If I've missed any requirements let me know. 
Seems like a simple fix. Tests pass.
> update examples to reflect web pack 2.2.0

- examples/watch-content-base/README.md
fix typo and add `--open` for `examples/watch-content-base/README.md`
update  `examples/watch-content-base/README.md`
**Summary**
> fix typo and add `--open`

- package.json
Updating http-proxy-middleware to it's newest version - [solves many issues](https://github.com/chimurai/http-proxy-middleware/blob/master/CHANGELOG.md)
> Update `http-proxy-middleware` to 0.17.4

- examples/https/README.md
Small typo fix
Updated `examples/https/README.md`
**Summary**
This PR fixes a small typo
No
> Fix typo in https docs

- bin/webpack-dev-server.js
bugfix
No
**Summary**
#972 Bug with new openPage option
No
> Set undefined openPage to empty string when open option is true

- client/index.js
Bugfix for #1042 
No need
**Summary**
#1042 
Negatory
None
> fixes #1042: overlay doesn't clear if errors are fixed but warnings remain

- client/index.js
Bugfix of https://github.com/webpack/webpack-dev-server/issues/1049
No
**Summary**
This is a proposed fix of the https://github.com/webpack/webpack-dev-server/issues/1049
Instead of just assuming that the module ./log is loaded there is a check to see if it actually is.
It should not!
> Proposed fix for ./log module not found

- lib/polyfills.js
Changed the way of adding Array.includes polyfill for node.js <6.
No need to.
**Summary**
This is a fix for [#1133](https://github.com/webpack/webpack-dev-server/issues/1133).
No
> Changed property descriptor for Array.includes polyfill

- package-lock.json
- package.json
Security
**Summary**
Related CVE:  - CVE: https://nvd.nist.gov/vuln/detail/CVE-2017-17461
No
> fix(package): Increase minimum `marked` version for ReDos vuln

- .github/CODEOWNERS
> chore(.github/CODEOWNERS): add code owners

- README.md
> docs(readme): remove obsolete maintenance note

- lib/optionsSchema.json
- test/Validation.test.js
No
Allow the output filename to be a function.
eg:
```
// webpack.config.js
entry: {
vendors: './vendors.js',
bundle: './bundle.js',
bundlepreview: './bundle.preview.js',
},
output: {
filename: (data) => data.chunk.name === "bundlepreview" ? '[name].js' : '[name].[chunkhash].js',
path: buildPath
},
```
None
Closes #1408
> fix(schema): allow the `output` filename to be a `{Function}`

- package-lock.json
- package.json
> chore(package): add `release` script (`scripts`)

- package-lock.json
- package.json
> chore(package): update `webpack-log` v1.1.2...v2.0.0 (`dependencies`)

- package-lock.json
- package.json
> chore(package): update `webpack-dev-middleware` v3.1.3...v3.2.0 (`dependencies`)

- package-lock.json
- package.json
- test/cli.test.js
> chore(package): update `yargs` v11.0.0...12.0.1 (`dependencies`) 

- package-lock.json
- package.json
Its dependencies dedupe with the ones pulled in from `yargs` (i.e. `find-up` and its dependencies).
> chore(package): update `import-local` v1.0.0...2.0.0 (`dependencies`)

- package-lock.json
- package.json
https://snyk.io/vuln/npm:mem:20180117
- None
> fix(package): `yargs` security vulnerability (`dependencies`)

- package-lock.json
- package.json
> chore(package): update `webpack-dev-middleware` v3.2.0...3.3.0 (`dependencies`)

- README.md
> docs(README): add cli flags

- examples/cli/compression/README.md
> Modify a sample url in compression's README.md

- package-lock.json
- package.json
This is a *dependencies update* :)
No
> chore(deps): update webpack and webpack-cli

- .babelrc
- package-lock.json
- package.json
> update Babel to version7

- .travis.yml
- appveyor.yml
Improve CI:
- More cache
- Remove duplicate build for node@11
- Avoid stages (improve parallels build for speedup)
- Avoid build branch in PR (speedup build)
- Use `npm ci` (speedup build)
No
No
> ci: small improve

- .github/CODEOWNERS
I add you (@hiroppy) to codeowners, michael-ciniawsky is inactive for a long time
No
No
> chore: add hiroppy to codeowners

- .travis.yml
> ci: fix typo

- jest.config.json
- lib/utils/createConfig.js
- test/CreateConfig.test.js
- test/Entry.test.js
- test/__snapshots__/CreateConfig.test.js.snap
- test/cli.test.js
- test/fixtures/entry-as-function/foo.js
- test/fixtures/entry-as-function/webpack.config.js
- test/fixtures/schema/webpack.config.simple.js
Refactor
No
Add comments for `v4`
> Test refactor and more

- lib/utils/createConfig.js
I was wrong all works fine (run `node bin/webpack-dev-server.js` and do  `console.log(argv.contentBase)`)
No
We can't test this right now, due architecture problem, we should write tests for this latest, so it was tested manually
> refactor: remove invalid todo

- examples/util.js
fixes #1428
no
Use `path.resolve` for windows.
I hope this change will work on windows as well.
no
> fix(example/util): use path.resolve

- jest.config.js
- jest.config.json
- package.json
> chore(jest): rename jest.config.json to jest.config.js

- test/Server.test.js
Add test for https://github.com/webpack/webpack-dev-server/issues/1557
> test(Server): add test for stats.warningsFilter

- examples/.assets/layout.html
- examples/api/middleware/server.js
- examples/general/config-array/webpack.config.js
- examples/general/config-promise/app.js
- examples/util.js
no
Delete bundle.js from index.html.
Delete before process from api/middleware/server.js.
Update webpack.config.js to v4 in general/config-array/webpack.config.js.
Check if result.output is existed in util.js.
no
We have to investigate `examples/api/` because they have below errors.
```sh
Uncaught SyntaxError: The URL 'http:/sockjs-node' is invalid
at new SockJS (sockjs.js:678)
at initSocket (socket.js:9)
at Object.eval (client:227)
at eval (client:273)
at Object.../../../client/index.js?http: (bundle.js:97)
at __webpack_require__ (bundle.js:20)
at eval (client:1)
at Object.0 (bundle.js:396)
at __webpack_require__ (bundle.js:20)
at bundle.js:84
```
I want to do this in another PR because this may change the core code.
> chore(examples): fix examples

- .eslintrc
- client-src/default/index.js
- client-src/live/index.js
- [ｘ] This is a **code refactor**
no
add curly rule
no
> style: add curly rule to eslint

- test/Headers.test.js
- test/Routes.test.js
- test/Util.test.js
No required
Move `header` option tests to own file, it is not route test
No
No
> refactor: tests

- test/cli.test.js
> test(cli): add --color test

- README.md
Adds image shield for:
- Downloads/month
- Contributors
Updates the `Table of Contents`
> docs(readme): adds couple img shields and updates TOC

- lib/options.json
- test/options/__snapshots__/options.test.js.snap
- test/options/options.test.js
I want to avoid forgetting to add an `errorMessage` when we add a property.
I added snapshots because #1819 has a big refactoring of options.json but I don' think they are not necessary. Maybe, I'll delete them after merging of #1819.
We should add documents about `sockPort`, `injectClient` and `injectHot`.
> add options test

- README.md
no need
Update test badge
No
Forget update badge :disappointed:
> docs: update test badge

- test/Routes.test.js
- test/__snapshots__/Routes.test.js.snap
- test/fixtures/directory-index.txt
- test/fixtures/magic-html.txt
nope
To make diff easy to understand and update easily.
nope
> test(Routes): migrate to snapshots

- azure-pipelines.yml
- commitlint.config.js
- package-lock.json
- package.json
no required
- npm audit
- commit message linting to ensure all commits are valid and we can use safely use `npm run release`
No
No
> ci: npm audit and lint commit message

- package.json
no need
We accidentally include `webpack.config.js` and `jest.config.js` in dist
No
No
> fix: do not include config files in dist

- lib/Server.js
> refactor: listen method

- .eslintignore
- .gitignore
- .prettierignore
- CONTRIBUTING.md
- husky.config.js
- lint-staged.config.js
- package-lock.json
- package.json
no required
Refactor eslint and prettier
No
No
> chore: refactor lint and prettier commands

- lib/Server.js
- package-lock.json
- package.json
no need
update express and remove workaround for wasm
No
No
> chore(deps): update express to 4.17 version

- renovate.json
no
ref: https://github.com/webpack/webpack-dev-server/pull/1893#issuecomment-493275063
no
> chore(renovate): ignore peerDependencies

- package.json
No
Make quotes in `package.json` windows-compatible
https://github.com/webpack/webpack-dev-server/issues/1905
None
fixes https://github.com/webpack/webpack-dev-server/issues/1905
> fix(package.json): make quotes windows compatible

- lib/Server.js
- test/Server.test.js
yes
fixes #1533 
fixes #1532
No
No
> feat(server): add WEBPACK_DEV_SERVER env variable

- package.json
- test/Proxy.test.js
yes
fixes #1440
No
Looks we already fix this problem, just add tests.
> test: proxy supports http methods

- bin/webpack-dev-server.js
- lib/utils/defaultPort.js
- lib/utils/findPort.js
- lib/utils/processOptions.js
- lib/utils/setupExitSignals.js
not required
Just refactor
No
No
> refactor(cli): code

- lib/utils/addEntries.js
- test/Entry.test.js
yes
https://github.com/webpack/webpack-dev-server/issues/1912#issuecomment-496881536
No
It is regression
> fix: add client code for `electron-renderer` target

- .eslintignore
- .prettierignore
- client-src/default/index.js
- client-src/default/utils/log.js
- client-src/default/utils/reloadApp.js
- test/client/default/utils/__snapshots__/log.test.js.snap
- test/client/default/utils/createSocketUrl.test.js
- test/client/default/utils/log.test.js
- test/client/default/utils/reloadApp.test.js
refactoring
refactoring client code
no
> refactor(client): create log module into utils

- client-src/default/index.js
- test/client/default/__snapshots__/index.test.js.snap
- test/client/default/index.test.js
- test/client/default/utils/reloadApp.test.js
yep
Absolutely necessary these😁
no
> test(client): add tests for default/index.js

- .gitignore
- package-lock.json
- package.json
No. This PR is not a bug or new feature.
nyc dependency seems unused since #1650
Nothing
Nothing
> chore(deps): delete nyc dependency

- lib/utils/runOpen.js
- package-lock.json
- package.json
- test/Server.test.js
no
opn was renamed to open.
no
> chore(deps): introduce open and remove opn

- test/options.test.js
`options.test.js` had some incorrect logic.
None
> fix(test): fix options.test.js

- lib/utils/createLogger.js
- lib/utils/runOpen.js
- lib/utils/tryParseInt.js
- test/server/utils/__snapshots__/findPort.test.js.snap
- test/server/utils/createLogger.test.js
- test/server/utils/defaultPort.test.js
- test/server/utils/defaultTo.test.js
- test/server/utils/findPort.test.js
- test/server/utils/getSocketServerImplementation.test.js
- test/server/utils/runOpen.test.js
- test/server/utils/tryParseInt.test.js
it is tests
more tests
No
Also some fixes in utils
> test: more

- client-src/default/overlay.js
- examples/cli/overlay/app.js
- test/client/__snapshots__/overlay.test.js.snap
- test/client/overlay.test.js
> refactor(client): overlay

- test/e2e/ProvidePlugin.test.js
- test/ports-map.js
modify only
use a port variable
no
> test(provide-plugin): use port variable

- package-lock.json
- package.json
no
related https://github.com/webpack/webpack-dev-server/pull/1995
no
> chore(deps): update dependency p-retry to v4

- lib/servers/WebsocketServer.js
- test/ports-map.js
- test/server/servers/WebsocketServer.test.js
- test/server/servers/__snapshots__/WebsocketServer.test.js.snap
Yes, but this cannot be tested in e2e without a native WebSockets client implementation.
Add `WebsocketServer` implementation, trying to mirror the features of `SockJSServer`.
Should I keep the `this.server.log.error(err.message);` line? I will add a test for it if I keep it, I am just trying to mirror the `SockJSServer` implementation.
> feat(server): WebsocketServer implementation and tests

- test/fixtures/multi-compiler-2-config/foo.js
- test/fixtures/multi-compiler-2-config/webpack.config.js
- test/server/utils/__snapshots__/updateCompiler.test.js.snap
- test/server/utils/updateCompiler.test.js
Yes
Tests for `updateCompiler`
> test(server): add updateCompiler tests

- .github/ISSUE_TEMPLATE.md
NA
As this project is client-side heavy too. A proper details are required for browser too when resolving an issue ! So along with other options, added browser too
No
NA
> chore(template): added browser option in issue template and contribution guide refactoring

- client-src/default/utils/createSocketUrl.js
- lib/Server.js
NA
https://dzone.com/articles/code-smells-if-statements
To improve the readablilty of the code, extracted most of the complex or huge if conditions. 
Tried to cover as much as possible, as of now
NO
NA
> chore: extract complex if condition to improve readability 

- examples/run-example.js
> chore(example): accept arguments via run-script

- package-lock.json
- package.json
no
run `audit fix`.
```
>= 4.17.12
├─┬ @commitlint/cli@8.0.0
│ ├─┬ @commitlint/lint@8.0.0
│ │ ├─┬ @commitlint/parse@8.0.0
│ │ │ ├─┬ conventional-commits-parser@2.1.7
│ │ │ │ └── lodash@4.17.14  deduped
│ │ │ └── lodash@4.17.14  deduped
│ │ ├─┬ @commitlint/rules@8.0.0
│ │ │ └─┬ @commitlint/ensure@8.0.0
│ │ │   └── lodash@4.17.11 
│ │ └── lodash@4.17.11 
│ ├─┬ @commitlint/load@8.0.0
│ │ ├─┬ @commitlint/resolve-extends@8.0.0
│ │ │ └── lodash@4.17.11 
│ │ └── lodash@4.17.11 
│ └── lodash@4.17.11 
```
These PRs have merged but they haven't published new version yet, so we cannot fix.(because they lock lodash's version)
https://github.com/conventional-changelog/commitlint/commit/4cb979df81328684467fd0dad130440ce725831d
https://github.com/conventional-changelog/commitlint/pull/724
no
> chore(deps): update package-lock.json

- lib/utils/routes.js
- test/server/utils/__snapshots__/routes.test.js.snap
- test/server/utils/routes.test.js
> refactor(routes): refactor utils/routes.js

- lib/utils/runBonjour.js
- test/server/utils/ runBonjour.test.js
- test/server/utils/__snapshots__/ runBonjour.test.js.snap
- test/server/utils/__snapshots__/colors.test.js.snap
- test/server/utils/__snapshots__/createConfig.test.js.snap
- test/server/utils/__snapshots__/findPort.test.js.snap
- test/server/utils/colors.test.js
- test/server/utils/createCertificate.test.js
- test/server/utils/createConfig.test.js
- test/server/utils/createDomain.test.js
- test/server/utils/findPort.test.js
- test/server/utils/getSocketClientPath.test.js
yes
Increase test coverage.
no
> test(utils): increase coverage

- .babelrc
- babel.config.js
no
use `api.cache`.
If you want to add other some feature, I'll add to .babelrc.js.
no
> chore(babel): use api.cache

- package-lock.json
- package.json
- test/cli/cli.test.js
- test/server/profile-option.test.js
> chore(deps): update webpack to 4.39.0

- .gitignore
- client-src/clients/SockJSClient.js
- client-src/clients/WebsocketClient.js
- test/e2e/ClientOptions.test.js
- test/e2e/Progress.test.js
- test/fixtures/reload-config-2/foo.js
- test/fixtures/reload-config-2/webpack.config.js
Yes
- There was some problematic logic in `ClientOptions.test.js`
- `Client.test.js` and `Progress.test.js` could potentially write to the same `main.css`, so I split their tests to use two different configs
None
> test(e2e): More e2e test improvements

- lib/Server.js
> fix: minor typo

- .github/CODEOWNERS
N/A
Joining the Codeowners list now that GSoC is almost over :tada: 
None
> Added my nickname to codeowners list

- package-lock.json
- package.json
see https://github.com/webpack/webpack-dev-server/pull/2252#issuecomment-531808344
no
Prevent to update by renovate.
no
> chore(deps): delete ^ from http-proxy-middleware

- lib/Server.js
- lib/options.json
- lib/utils/addEntries.js
- lib/utils/createConfig.js
- test/e2e/ClientOptions.test.js
- test/options.test.js
- test/server/sockPath-option.test.js
- test/server/transportMode-option.test.js
- test/server/utils/__snapshots__/createConfig.test.js.snap
Reverts webpack/webpack-dev-server#2047
> fix(server): revert "union sock options"

- renovate.json
no
for https://github.com/webpack/webpack-dev-server/pull/2252
> chore(renovate): ignore http-proxy-middleware updates

- azure-pipelines.yml
- package.json
> chore: drop remove node8

- .eslintrc
- client-src/.eslintrc
- examples/.eslintrc
- test/.eslintrc
no
Delete unnecessary eslintrc.
no
> chore(eslint): use overrides option

- package-lock.json
- package.json
no
see the title
I think the tests are flaky when we use Node13(mac) so I would like to check about it.(maybe because of jest-worker)
closes: https://github.com/webpack/webpack-dev-server/pull/2363
> chore(deps): update execa to v4

- lib/Server.js
- lib/options.json
- package-lock.json
- package.json
- test/__snapshots__/validate-options.test.js.snap
- test/validate-options.test.js
No need
We don't need that option
Yes
No
> Refactor remove the setup option

- bin/options.js
- lib/options.json
- lib/utils/createConfig.js
- lib/utils/createLogger.js
- test/__snapshots__/validate-options.test.js.snap
- test/fixtures/schema/webpack.config.no-dev-stats.js
- test/server/utils/__snapshots__/createConfig.test.js.snap
- test/server/utils/createConfig.test.js
- test/server/utils/createLogger.test.js
- test/validate-options.test.js
Just remove unnecessary
Here two motivation:
1. We have `logLevel` option
2. We should migrate on built-in webpack logger
Yes
No
> Refactor remove the no info option

- lib/Server.js
> Refactor remove workaround for old node

- lib/Server.js
> feat: add serveIndex icons

- package-lock.json
- package.json
> fix: #2515 - jquery 3.4.1 has known vulnerabilities: severity: medium

- azure-pipelines.yml
> ci: add node@14

- client-src/default/webpack.config.js
- package-lock.json
- package.json
no
closes: https://github.com/webpack/webpack-dev-server/issues/1286
no
> fix(client): remove exclude option from client's webpack.config.js

- CONTRIBUTING.md
> chore: modify CONTRIBUTING.md

- test/client/index.test.js
no
Remove my comment by this fixing
no
> test(client): do mock window.location.reload and assign

- client-src/clients/WebsocketClient.js
- client-src/default/utils/getCurrentScriptSource.js
- test/client/utils/__snapshots__/getCurrentScriptSource.test.js.snap
- test/e2e/TransportMode.test.js
- test/e2e/__snapshots__/TransportMode.test.js.snap
N/A
Testing stability. What we need to look at in client logs needs to be adjusted due to recent logger updates.
[WDS] is switched to [webpack-dev-server] in 1 case
> test(client): work on test instability

- bin/options.js
- client-src/clients/BaseClient.js
- client-src/clients/SockJSClient.js
- client-src/clients/WebsocketClient.js
- client-src/default/index.js
- lib/Server.js
- lib/servers/SockJSServer.js
- lib/utils/addEntries.js
- lib/utils/createConfig.js
- lib/utils/createDomain.js
- lib/utils/updateCompiler.js
- test/Validation.test.js
- test/client/index.test.js
- test/helpers/test-server.js
- test/server/historyApiFallback-option.test.js
No need
Remove unused comments + move comments on own line instead using on whole file
No
No
> Refactor eslint comments

- package-lock.json
- package.json
- test/helpers/run-browser.js
N/A
This removes `puppeteer:protocol:RECV` spam in CI
It seems the problem was solved here: https://github.com/puppeteer/puppeteer/issues/6147
N/A
> chore(e2e): upgrade puppeteer and disable puppeteer debug logs for tests

- examples/util.js
"before" feature is deprecated.
> chore(examples): fix util.js

- .prettierrc.js
no
just deleting unnecessary options
> chore(prettier): delete default options

- lib/Server.js
- lib/servers/SockJSServer.js
- lib/servers/WebsocketServer.js
- test/client/clients/SockJSClient.test.js
- test/client/clients/WebsocketClient.test.js
- test/server/Server.test.js
- test/server/host-option.test.js
- test/server/port-option.test.js
- test/server/servers/SockJSServer.test.js
- test/server/servers/WebsocketServer.test.js
- test/server/setupExitSignals-option.test.js
- test/server/transportMode-option.test.js
- test/server/utils/createDomain.test.js
Existing
rename to `server`, because it is server
Yes, if somebody touch `listeningApp`
No
> refactor: server access property name

- client-src/clients/SockJSClient.js
- client-src/clients/WebsocketClient.js
- lib/servers/SockJSServer.js
- lib/servers/WebsocketServer.js
- package-lock.json
- package.json
- test/fixtures/custom-client/CustomSockJSClient.js
> chore(deps): update prettier

- lib/Server.js
No tests so far
Cannot run dev server because of exception
No breaking change I think
> fix: changed this.options.info to this.logger.info

- package-lock.json
> chore(deps): update deps for audit

- bin/cli-flags.js
- test/cli/cli.test.js
No need, it is for `webpack serve` (tests on webpack-cli side)
part of https://github.com/webpack/webpack-cli/issues/2018
No
Need backport to webpack-dev-server@4
> Fix cli args for serve

- bin/cli-flags.js
- lib/Server.js
- lib/utils/normalizeOptions.js
- test/server/utils/__snapshots__/normalizeOptions.test.js.snap
No need, tests in webpack-cli
Avoid `defaultValue`, no need it here
No
No
> fix: default cli arguments for `webpack serve`

- client-src/default/index.js
> webpack-dev-server v4 -window is not defined #2970

- test/cli/__snapshots__/cli.test.js.snap
- test/cli/cli.test.js
fix CI.
Broken CI for all PRs
None
No
> chore: fix CI

- .github/workflows/nodejs.yml
Rsstore node modules cache.
None
> chore: restore npm cache

- bin/cli-flags.js
No
redundant delcarations. `webpack-cli` do not use them.
None
No
> refactor: remove redundant group declaration

- test/cli/cli.test.js
already present
fix snapshot issue
None
> test: fix RegExp

- client-src/default/index.js
> fix: show detailed error in overlay

- client-src/default/index.js
> refactor: fix CI lint

- test/cli/cli.test.js
Enabled test.
Enable test case for `--hot-only`
None
No
> test: enable --hot-only test case

- package-lock.json
- package.json
- setupTest.js
- test/cli/cli.test.js
- test/e2e/DevServer.test.js
WIP
update `webpack-dev-middleware`
None
Fixes #3010
> chore: update webpack-dev-middleware

- test/cli/cli.test.js
- test/fixtures/cli/webpack.config.js
Refactor tests.
No need for separate test cases of `--hot` and `--no-hot` for `webpack 4` and `webpack-5`
> test: refactor cli test

- package.json
Now use `npm run lint:fix` to fix lint issues.
None
No
> chore: add script to fix lint

- test/e2e/DevServer.test.js
- test/fixtures/dev-server/empty-entry.js
yes.
Added a test case for #2876 
None
No
> test: add empty entry case

- renovate.json
NO
Avoid updating node engine.
None
https://docs.renovatebot.com/configuration-options/#constraints
> chore: force constraint and ignore node for renovate-bot

- test/server/utils/DevServerPlugin.test.js
No
Refactor, remove unnecessary code.
No
No
> refactor: remove stale code

- lib/Server.js
- test/server/open-option.test.js
- test/server/utils/runOpen.test.js
Yes.
Fixes https://github.com/webpack/webpack-dev-server/issues/2993
None
No
> fix: allow to open browser with --open-page

- CODE_OF_CONDUCT.md
> docs: fix typo

- bin/cli-flags.js
No
Add some more negative flags.
None
No
> feat: add more negative flags

- .github/ISSUE_TEMPLATE.md
No
link to SO's guide for reproduction in the issue template.
https://stackoverflow.com/help/minimal-reproducible-example
None
No
> chore: link to SO's guide for reproduction in issue template

- README.md
no
Update cli options in docs.
None
No
> docs: update cli options

- examples/cli/open-page-multiple/README.md
- examples/cli/open-page/README.md
No
Update docs. No need to pass `--open` explicitly with `--open-page`
No
No
> docs: update --open-page example usage

- lib/Server.js
- package-lock.json
- package.json
- test/cli/__snapshots__/cli.test.js.snap
- test/cli/cli.test.js
- test/e2e/DevServer.test.js
- test/helpers/test-bin.js
- test/server/open-option.test.js
Will add late
finish https://github.com/webpack/webpack-dev-server/issues/2943
No
output information for IPv4 and IPv6 + less deps, because `internal-ip` uses `ipaddr.js`
> feat: improve output for IPv4 and IPv6

- bin/cli-flags.js
NA
Migrates the flags to new format
Shouldn't have
- Do we need duplicate desc for all configs?
> fix: migrate flags to new configs format

- bin/cli-flags.js
- lib/options.json
- lib/utils/setupExitSignals.js
- test/__snapshots__/Validation.test.js.snap
- test/cli/cli.test.js
- test/server/setupExitSignals-option.test.js
- test/server/utils/setupExitSignals.test.js
remove `stdin` in favor of `--watch-options-stdin` from `webpack-cli`
`stdin` option was removed.
No
> refactor: remove `stdin` option

- README.md
No
`--hot-only` was removed.
None
No
> docs: remove `--hot-only`

- test/cli/cli.test.js
Yes enabled test for `--hot=only`
update webpack-cli to latest.
None
No
>  test: enable test case for `--hot=only`

- bin/cli-flags.js
No
Avoid additional negative flags.
No
> refactor: cli flags

- lib/Server.js
NA
- ipv6 will never be resolved
no
https://github.com/webpack/webpack-dev-server/pull/3112#discussion_r603466075
> fix: hostname resolving

- README.md
- bin/cli-flags.js
> docs: open option

- README.md
- bin/cli-flags.js
- test/cli/cli.test.js
Yes
Add `--client-overlay` cli option.
None
No
> feat: add `--client-overlay` flag

- examples/cli/host-and-port/README.md
No
Update docs for `host` options
None
No
> docs: update `--host` documentation

- test/cli/cli.test.js
Yes
More tests for cli
None
No
> test: cover more cases for cli tests

- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
Updates snapshots.
Output more useful information on errors.
None
No
> fix: output description for invalid `client` options

- README.md
> docs: update `webpack-dev-server` usage

- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/validate-options.test.js
Yes
Output a more detailed description for nested properties.
None
No
> fix: output description on errors for nested properties

- examples/cli/open-target-multiple/README.md
- examples/cli/open-target/README.md
No
update docs, https://github.com/webpack/webpack.js.org/pull/4828#discussion_r609638341
None
No
> docs: add more examples for `--open-target`

- CONTRIBUTING.md
No
Update docs, add guidelines for commit messages.
> docs: add commit message guidelines

- examples/cli/progress/README.md
- examples/cli/progress/webpack.config.js
> docs: fix `--client-progress` example

- examples/util.js
- lib/Server.js
- lib/utils/getCertificate.js
- lib/utils/routes.js
- test/e2e/Client.test.js
- test/e2e/Progress.test.js
- test/server/https-option.test.js
- test/server/liveReload-option.test.js
- test/server/static-directory-option.test.js
- test/server/watchFiles-option.test.js
- test/validate-options.test.js
No
No need to use a dependency just for using `fs.existsSync`. 
None
No
> refactor: make use of `graceful-fs`

- examples/cli/overlay/README.md
- examples/cli/overlay/app.js
- examples/cli/overlay/webpack.config.js
No
Add an example showing usage of `overlay` feature.
> docs: add example for overlay

- test/server/bonjour-option.test.js
Yes
Case when `devserver.https = true` and `devServer.bonjour.type = 'http'`
None
No
> test: add more case for bonjour option

- lib/Server.js
- test/cli/__snapshots__/cli.test.js.snap.webpack4
- test/cli/__snapshots__/cli.test.js.snap.webpack5
- test/cli/cli.test.js
> fix: bonjour information log

- lib/Server.js
- lib/utils/DevServerPlugin.js
- test/e2e/ClientOptions.test.js
- test/server/__snapshots__/Server.test.js.snap.webpack4
- test/server/__snapshots__/Server.test.js.snap.webpack5
- test/server/utils/findPort.test.js
bugfix/refactor
https://github.com/webpack/webpack-cli/pull/2624
No
Need test
> fix: user server port for websocket connection by default

- README.md
- bin/cli-flags.js
- test/cli/__snapshots__/cli.test.js.snap.webpack4
- test/cli/__snapshots__/cli.test.js.snap.webpack5
No
Part of Roadmap.
Maybe, it was added in beta.
No
> refactor: remove `--setup-exit-signals`

- examples/cli/watch-static/README.md
- examples/cli/watch-static/assets/index.html
> docs: update `static` example

- package-lock.json
N/A
- Update lock file as a follow up to #3211
- Fixes security vulnerabilities.
Nothing
N/A
> build: update lock file

- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/validate-options.test.js
Yes
Add descriptions. Output more information on errors.
None
No
> fix: add descriptions for https options

- README.md
- test/cli/__snapshots__/cli.test.js.snap.webpack4
> docs: update usage

- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
Updated snapshots
Add link for bonjour options.
None
No
> fix: add link for `bonjour` options

- lib/Server.js
> chore: fix lint warning

- .husky/commit-msg
https://typicode.github.io/husky/#/?id=husky_git_params-ie-commitlint-
None
No
> fix: update husky config

- lib/servers/WebsocketServer.js
- test/server/proxy-option.test.js
NA
rename `wsServer` to `webSocketServer`
None
No
> refactor: rename `wsServer` to `webSocketServer`

- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/validate-options.test.js
> fix: description of `client.path` and `client.port`

- test/server/host-option.test.js
> test: add more cases for `host` option

- lib/Server.js
- package-lock.json
- package.json
> refactor: use public API

- test/cli/cli.test.js
> test: fix stdin test

- README.md
> docs: remove `--firewall`

- test/e2e/DevServer.test.js
> test: fix entry descriptor test

- package.json
NA
We don't have `ssl` folder anymore.
No
No
> chore: update `files` in package.json

- bin/webpack-dev-server.js
tested manually
fix npx usage
No
No
> fix: npx usage

- lib/options.json
- package-lock.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/cli/__snapshots__/cli.test.js.snap.webpack5
Already Present.
Move `properties` to `definitions`.
No
No
> refactor: schema

- lib/utils/findCacheDir.js
- lib/utils/getCertificate.js
- package-lock.json
- package.json
existing
use own implementation to prevent sec issues
no
> fix: use own cache dir resolve implementation

- bin/cli-flags.js
- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/cli/__snapshots__/cli.test.js.snap.webpack4
- test/cli/__snapshots__/cli.test.js.snap.webpack5
- test/validate-options.test.js
yes
Better description, remove unnecessary `require`and `minItems` and `minLength`, because it is valid to use `[]` and `''` in maybe cases, order of options + some implements
Should be no
No
> Refactor schema

- .github/workflows/nodejs.yml
No
use `npm audit --production` on CI
None
No
> chore: check audit for production

- test/cli/__snapshots__/cli.test.js.snap.webpack4
- test/cli/__snapshots__/cli.test.js.snap.webpack5
- test/cli/cli.test.js
- test/e2e/DevServer.test.js
- test/helpers/test-bin.js
Existing
Migrate to `async-await`
None
No
> test: refactor cli tests

- examples/cli/web-socket-url-cli/README.md
- examples/cli/web-socket-url/README.md
> docs: update `client.webSocketURL` examples

- .gitignore
> chore: ignore yarn-error.log

- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/validate-options.test.js
Yes
don't allow empty array for `allowedHosts`
No
No
> fix: don't allow empty array for `allowedHosts` option

- test/server/Server.test.js
- test/server/client-option.test.js
- test/server/hot-option.test.js
- test/server/http2-option.test.js
- test/server/onAfterSetupMiddleware-option.test.js
- test/server/onBeforeSetupMiddleware-option.test.js
- test/server/utils/DevServerPlugin.test.js
- test/server/utils/routes.test.js
> refactor: migrate tests on async await

- lib/utils/normalizeOptions.js
existing
refactor as per schema
no
> refactor: normalizer

- README.md
> docs: update cli-flags

- lib/utils/DevServerPlugin.js
- test/e2e/__snapshots__/target.test.js.snap.webpack4
- test/e2e/__snapshots__/target.test.js.snap.webpack5
- test/e2e/target.test.js
- test/ports-map.js
only tests here
Test target
No
added `electron-preload` target for webpack v4, because it is web target
> Test target

- examples/cli/https/README.md
> docs: add `--https-request-cert`

- lib/servers/WebsocketServer.js
- package-lock.json
- package.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
fix #3519
I found it as breaking change, not fix
No
No
> Chore deps update ws

- client-src/modules/strip-ansi/index.js
- package-lock.json
- package.json
- test/cli/basic.test.js
- test/client/index.test.js
- test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack4
- test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack5
- test/e2e/hot-and-live-reload.test.js
- test/helpers/test-bin.js
Yes
update `strip-ansi` + test stabilization
No
Found one problem, we neeed to allow set `webSocketServer: false`, I will send a PR
> Chore update strip ansi

- migration-v4.md
NA
add migration guide for users.
No
fixes #2935
> docs: create migration guide for v4

- migration-v4.md
> docs: update migration guide

- lib/Server.js
- lib/utils/normalizeOptions.js
NA
inline `getCompilerConfigArray` util with `Server`
NO
No
> refactor: inline `getCompilerConfigArray` util with `Server`

- lib/Server.js
existing
we don't use it
potentially yes, but it should be not used directly
No
> refactor: remove unused method

- lib/Server.js
- package-lock.json
- package.json
> chore: migrate to colorette

- lib/Server.js
- test/e2e/web-socket-communication.test.js
- test/server/__snapshots__/Server.test.js.snap.webpack4
- test/server/__snapshots__/Server.test.js.snap.webpack5
existing
normalize some options + fix order + small improvements 
No
No
> Refactor code

- lib/Server.js
- lib/servers/SockJSServer.js
- test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack4
- test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack5
- test/e2e/allowed-hosts.test.js
- test/ports-map.js
- test/server/Server.test.js
- test/server/allowedHosts-option.test.js
Yes
#3556
No
WIP on more tests
> Issue 3556

- .github/workflows/nodejs.yml
> chore: update commitlint github action in CI

- migration-v4.md
n/a
Reducing friction when updating to WDS4.
n/a
See #3587
> docs: improve migration docs on `injectClient`, `injectHot`

- migration-v4.md
No
update migration guide
none
no
> docs: add Node.js API update in migration guide

- test/cli/basic.test.js
- test/e2e/__snapshots__/host-and-port.test.js.snap.webpack4
- test/e2e/__snapshots__/host-and-port.test.js.snap.webpack5
- test/e2e/host-and-port.test.js
- test/e2e/hot-and-live-reload.test.js
- test/helpers/test-bin.js
it is tests
we need stability our tests
No
No
> test: stability

- client-src/overlay.js
existing
use ecma modules everywhere
No
no
> refactor: use ECMA modules in overlay

- .github/ISSUE_TEMPLATE.md
NO
Many times developers do not write about the version of packages they are using and we have to ask them manually. Adding it to the issue template will save the developer's time.
None
No
> docs: ask `version` information in issue template

- client-src/utils/createSocketURL.js
- test/client/utils/createSocketURL.test.js
yes
Possible fix https://github.com/webpack/webpack-dev-server/issues/3674, anyway we should respect protocol for manual setup
No
No
> fix: respect protocol from browser for manual setup

- test/cli/__snapshots__/bonjour-option.test.js.snap.webpack4
- test/cli/__snapshots__/bonjour-option.test.js.snap.webpack5
- test/cli/__snapshots__/http2-option.test.js.snap.webpack4
- test/cli/__snapshots__/http2-option.test.js.snap.webpack5
- test/cli/__snapshots__/https-option.test.js.snap.webpack4
- test/cli/__snapshots__/https-option.test.js.snap.webpack5
- test/helpers/test-bin.js
- test/server/setupExitSignals-option.test.js
test stability
test stability
No
No
> test: fix stability

- examples/web-socket-url/README.md
> docs: update `web-socket-url` example

- lib/Server.js
- test/server/proxy-option.test.js
> Issue 3687

- migration-v4.md
> fix: fix  docs

- migration-v4.md
> docs: fix more migration guide

- examples/on-listening/README.md
- examples/on-listening/app.js
- examples/on-listening/webpack.config.js
No
add `onListening` example
no
no
> docs: add `onListening` example

- migration-v4.md
> docs: fix a typo

- test/e2e/__snapshots__/host-and-port.test.js.snap.webpack4
- test/e2e/__snapshots__/host-and-port.test.js.snap.webpack5
- test/e2e/host-and-port.test.js
tests
fix test for `0.0.0.0`
No
No
> test: fix todo

- client-src/index.js
- test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack4
- test/e2e/__snapshots__/hot-and-live-reload.test.js.snap.webpack5
- test/e2e/hot-and-live-reload.test.js
Yes
Allow to enable hot and liveReload using query params for client
No
fixes #3694
> Issue 3694

- examples/on-after-setup-middleware/README.md
- examples/on-after-setup-middleware/app.js
- examples/on-after-setup-middleware/webpack.config.js
No
add `onAfterSetupMiddleware` example
None
No
> docs: add `onAfterSetupMiddleware` example

- examples/on-listening/README.md
> docs: fix typo in `onListening` example

- examples/on-before-setup-middleware/README.md
- examples/on-before-setup-middleware/app.js
- examples/on-before-setup-middleware/webpack.config.js
No
add `onBeforeSetupMiddleware` example.
None
No
> docs: add `onBeforeSetupMiddleware` example

- examples/client/logging/README.md
- examples/client/logging/app.js
- examples/client/logging/webpack.config.js
No
add example for `client.logging`.
None
No
> docs: add `client.logging` example

- migration-v4.md
> docs: add note about static files being watched by default

- migration-v4.md
No
Refers https://github.com/webpack/webpack.js.org/issues/5344
None
No
> docs: update migration guide for multiple `static` values

- examples/magic-html/README.md
- examples/magic-html/app.js
- examples/magic-html/webpack.config.js
add `magicHtml` examples
None
No
> docs: add `magicHtml` examples

- examples/history-api-fallback/README.md
- examples/history-api-fallback/webpack.config.js
improve `historyApiFallback` example.
No
No
> docs: improve `historyApiFallback` example

- examples/history-api-fallback/README.md
No
fix https://github.com/webpack/webpack-dev-server/pull/3759#discussion_r698028663
None
No
> docs: use more specific text in `historyApiFallback` example

- examples/default/webpack.config.js
- examples/general/config-array/webpack.config.js
- test/fixtures/historyapifallback-3-config/webpack.config.js
- test/fixtures/historyapifallback-config/webpack.config.js
- test/fixtures/mime-types-config/webpack.config.js
- test/fixtures/multi-public-path-config/webpack.config.js
No
remove deprecated `file-loader` and `url-loader` in favor of asset modules.
None
No
> chore: use asset modules

- test/e2e/http2.test.js
No
use the corresponding port for `http2` test
None
No
> test: use the corresponding port for `http2` test

- lib/Server.js
No
refactor code for consistency. `options` is already destructured above.
None
No
> refactor: code for consistency

- test/ports-map.js
- test/server/mimeTypes-option.test.js
No
fix typo, `mine-types` -> `mime-types`.
None
No
> chore: fix typo

- examples/compression/README.md
No
It is `main.js` instead of `bundle.js`.
none
no
> docs: fix typo in `compression` example

- examples/dev-middleware/README.md
- examples/dev-middleware/app.js
- examples/dev-middleware/webpack.config.js
No
add `devMiddleware` option example.
None.
No
> docs: add `devMiddleware` example

- test/helpers/test-server.js
No
use latest API methods
none
no
> refactor: use latest API methods

- .github/workflows/nodejs.yml
NA
16.x CI fails due to v8 bug
no
https://github.com/webpack/webpack/commit/a7e5f3a73b76fa8a50250768cdab3e0dca36dec1
> chore: fix nodejs due to v8 bug

- package-lock.json
- package.json
- test/e2e/range-header.test.js
- test/ports-map.js
yes
update `webpack-dev-middleware` and add test for `Range` header
No
No
> test: `Range` header

- test/e2e/__snapshots__/api.test.js.snap.webpack4
- test/e2e/__snapshots__/api.test.js.snap.webpack5
- test/e2e/api.test.js
yes
test to rerun dev server multiple times without closing compiler
No
No
> test: rerun dev server

- test/cli/__snapshots__/https-option.test.js.snap.webpack4
- test/cli/__snapshots__/https-option.test.js.snap.webpack5
- test/cli/https-option.test.js
> test: add more cases for https cli options

- .github/workflows/nodejs.yml
NA
Previous bug seems fixed
no
> ci: update node 16 

- examples/bonjour/boolean/README.md
- examples/bonjour/boolean/app.js
- examples/bonjour/boolean/webpack.config.js
- examples/bonjour/object/README.md
- examples/bonjour/object/app.js
- examples/bonjour/object/webpack.config.js
No
improve `bonjour` example.
None
No
> docs: improve `bonjour` example

- examples/bonjour/app.js
> chore: remove stale file

- examples/api/start/README.md
- examples/api/start/app.js
- examples/api/start/server.js
- examples/api/start/webpack.config.js
No
add `server.start()` example.
None
No
> docs: add `start` example

- examples/api/start-callback/README.md
- examples/api/start-callback/app.js
- examples/api/start-callback/server.js
- examples/api/start-callback/webpack.config.js
No
add `startCallback` method example.
None
No
> docs: add `startCallback` example

- examples/api/stop/README.md
- examples/api/stop/app.js
- examples/api/stop/server.js
- examples/api/stop/webpack.config.js
No
add `stop` example.
None
No
> docs: add `stop` example

- examples/compression/webpack.config.js
No
explicitly mention `compress: true` in the example config.
none
No
> docs: update webpack configuration for `compression` example

- lib/Server.js
- package-lock.json
- package.json
> chore(deps): update

- examples/client/overlay/README.md
- examples/client/overlay/webpack.config.js
- examples/client/progress/README.md
- examples/client/progress/webpack.config.js
update `overlay` and `progress` examples, add commands to disable these options via CLI.
None
No
> docs: update `overlay` and `progress` examples

- .github/ISSUE_TEMPLATE/BUG.md
- .github/ISSUE_TEMPLATE/DOCS.md
- .github/ISSUE_TEMPLATE/FEATURE.md
- .github/ISSUE_TEMPLATE/MODIFICATION.md
- .github/ISSUE_TEMPLATE/SUPPORT.md
No
Add issue templates like other repositories.
None
No
> docs: add issue templates

- examples/https/boolean/webpack.config.js
- examples/https/object/README.md
No
update `https` example
None
No
> docs: update `https` example

- test/e2e/client.test.js
refactor test
Fix https://github.com/webpack/webpack-dev-server/issues/3964
None
No
> ci: fix puppeteer flakiness

- lib/Server.js
No
remove an eslint-disable comment.
None
No
> chore: remove `eslint-disable` comment

- README.md
- bin/cli-flags.js
- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/cli/__snapshots__/basic.test.js.snap.webpack4
- test/cli/__snapshots__/basic.test.js.snap.webpack5
Updated snapshots.
update descriptions of `http2` and `https` option to mention about their deprecation.
None
No
> fix: update descriptions of `http2` and `https` option 

- lib/Server.js
No
remove redundant `eslint-disable` comments.
None
No
> chore: remove redundant `eslint-disable` comments

- README.md
> docs: fix `--https` option alignment

- package-lock.json
- package.json
No
update `schema-utils` to v4.
None
No
> chore: update `schema-utils`

- package-lock.json
- package.json
- test/e2e/hot-and-live-reload.test.js
No need
Remove unused deps
No
No
> chore(deps): remove unused

- client-src/socket.js
Without this param passed, the client will only reconnect once.
> Fix reconnect tries

- .github/workflows/nodejs.yml
No
Sse node 16 for lint job.
None
No
> ci: use node 16 for lint job

- test/e2e/static-directory.test.js
No
use the latest API method `stopCallback` instead of `close`.
None
No
> refactor: use the latest API method

- CONTRIBUTING.md
No
Use direct link to sign CLA instead of github repo link.
None
No
> docs: update CLA link

- .eslintrc.js
- client-src/socket.js
- examples/general/proxy-hot-reload/webpack.config.js
- lib/Server.js
- lib/servers/SockJSServer.js
- lib/servers/WebsocketServer.js
- test/e2e/entry.test.js
- test/e2e/overlay.test.js
- test/e2e/static-directory.test.js
- test/fixtures/custom-client/CustomSockJSClient.js
- test/fixtures/historyapifallback-2-config/foo.js
- test/fixtures/historyapifallback-3-config/foo.js
- test/fixtures/historyapifallback-config/foo.js
No
enable `reportUnusedDisableDirectives` for eslint.
None
No
> chore: enable `reportUnusedDisableDirectives` for eslint

- lint-staged.config.js
None
update `lint-staged` config to run prettier for all file and use eslint cache.
None
No
> chore: update `lint-staged` config

- test/__snapshots__/validate-options.test.js.snap.webpack4
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/validate-options.test.js
Yes
add validation test for `server.cacert` option.
None
No
> test: add validation test case for `server.cacert` option

- test/e2e/https.test.js
No
clear mock after test.
None
No
> test: clear mock after usage

- README.md
- bin/cli-flags.js
- test/cli/__snapshots__/basic.test.js.snap.webpack4
Updated existing snapshots.
Sort cli-flags alphabetically.
None
No
>  fix: sort cli flags in help output 

- CONTRIBUTING.md
In the contribution guide, replace `prepublish` with `build` because the `prepublish` script does not exist.
> docs: fix testing instructions

- package-lock.json
- package.json
No need
fixes https://github.com/webpack/webpack-dev-server/issues/4167
No
No
> chore(deps): update `selfsigned`

- test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack4
- test/e2e/__snapshots__/allowed-hosts.test.js.snap.webpack5
- test/e2e/allowed-hosts.test.js
NA
enable skipped `allowedHosts` test case.
None
No
> test: enable skipped `allowedHosts` test case

- examples/api/internal-ip-sync/README.md
- examples/api/internal-ip-sync/app.js
- examples/api/internal-ip/README.md
- examples/api/internal-ip/app.js
No
add examples for `internalIP` and `internalIPSync`.
None
No
> docs: add examples for `internalIP` and `internalIPSync`

- test/e2e/on-listening.test.js
NA
fix `onListening` test cases. Tests were using `onAfterSetupMiddleware option` instead.
None
No
> test: fix `onListening` test cases

- package-lock.json
- package.json
No
udpate dependencies.
None
No
> chore: udpate dependencies

- scripts/extend-webpack-types.js
No
use `graceful-fs` for consistency like everywhere else in codebase.
No
No
> chore: use `graceful-fs`

- test/e2e/logging.test.js
No
migrate logging test on `HTMLGeneratorPlugin`.
None
No
> test: migrate logging test on `HTMLGeneratorPlugin`

- test/e2e/allowed-hosts.test.js
- test/e2e/api.test.js
No
Migrate `allowedHosts` and `api` tests on `HTMLGeneratorPlugin`.
None
No
> test: migrate `allowedHosts` and `api` tests on `HTMLGeneratorPlugin`

- test/e2e/server-and-client-transport.test.js
- test/fixtures/provide-plugin-custom/webpack.config.js
- test/fixtures/provide-plugin-default/webpack.config.js
- test/fixtures/provide-plugin-sockjs-config/webpack.config.js
- test/fixtures/provide-plugin-ws-config/webpack.config.js
No
migrate  `client.transport` tests on `HTMLGeneratorPlugin`.
No
No
> test: migrate  `client.transport` tests on `HTMLGeneratorPlugin`

- .github/workflows/nodejs.yml
No
Update workflow. Only one job for webpack-4.
No
No
> ci: update workflow strategy

- .github/workflows/nodejs.yml
- test/e2e/server.test.js
> ci: fix for windows

- package-lock.json
- package.json
add `@types/express` as it is peer dependency for `http-proxy-middleware`.
None
No
> fix: add `@types/express`

- test/e2e/stats.test.js
Refactor tests.
migrate stats test on `HTMLGeneratorPlugin`.
None
No
> test: migrate stats test on `HTMLGeneratorPlugin`

- .github/ISSUE_TEMPLATE/BUG.md
> docs: fix typo in bug report template

- README.md
No
add `yarn` and `pnpm` installation.
No
No
> docs: add `yarn` and `pnpm` installation

- package-lock.json
> ci: fix audit

- test/server/open-option.test.js
Yes
add case for `open` with `server` option.
None
No
> test: add case for `open` with `server` option

- lib/Server.js
- package-lock.json
- package.json
- test/e2e/bonjour.test.js
- types/lib/Server.d.ts
WIP on tests.
Fix #4263 
None
No
> refactor: use `bonjour-service`

- .github/workflows/nodejs.yml
- package.json
- scripts/check-types.js
NO
Fix https://github.com/webpack/webpack-dev-server/issues/4279
NO
NO
> Ci check types

- test/e2e/__snapshots__/web-socket-server-url.test.js.snap.webpack4
- test/e2e/__snapshots__/web-socket-server-url.test.js.snap.webpack5
- test/e2e/web-socket-server-url.test.js
> test: add cases for `webSocketURL` with `server` option

- lib/Server.js
- types/lib/Server.d.ts
> fix: types

- client-src/utils/createSocketURL.js
> fix: ie11 runtime

- .github/workflows/nodejs.yml
No
Update `checkout`, `setup-node`, and `codecov` actions to v3
No
No
> ci: update `checkout`, `setup-node`, and `codecov` actions

- package-lock.json
- package.json
This change should be covered by the `lint-types` npm script.
Fix #4467 with Yarn PnP and Typescript.
> fix: add `@types/serve-static` to dependencies

- README.md
New Note format.
> **Note**
>
> _For more information on above options explore this [link](https://webpack.js.org/configuration/dev-server/)._
No
No
> docs: improve note with latest format

- examples/open-target-multiple/webpack.config.js
- examples/open-target/webpack.config.js
No new test. Old tests are fixed.
Before
After
> test: fix examples for open target not working

- .github/workflows/nodejs.yml
- test/e2e/host.test.js
Add node v18 on CI
Fix https://github.com/webpack/webpack-dev-server/pull/4491
No
No
> ci: add node v18

- .github/workflows/nodejs.yml
- test/e2e/host.test.js
> ci: add node v19

- test/e2e/port.test.js
Fix CI. Error message changes with Node v19.
None
No
> ci: fix port option E2E test for node v19

- .github/workflows/nodejs.yml
- babel.config.js
- package.json
Already present.
Drop Nodejs v12. Prepare for next version.
minimum supported Nodejs version is 14.15.0
No
> build: minimum supported Nodejs version is 14.15.0

- .github/workflows/nodejs.yml
No.
CI is failing because it can't find the firefox browser.
No.
No.
> ci: setup firefox for tests

- lib/Server.js
- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack5
- test/cli/__snapshots__/basic.test.js.snap.webpack5
- test/cli/__snapshots__/server-option.test.js.snap.webpack5
- test/cli/server-option.test.js
- test/e2e/__snapshots__/server.test.js.snap.webpack5
- test/e2e/server.test.js
- test/validate-options.test.js
- types/lib/Server.d.ts
Remove the deprecated option `server.options.cacert`
BREAKING CHANGE: the `server.options.cacert` option was removed in favor of  the `server.options.ca` option
No
> refactor!: remove the deprecated option `server.options.cacert`

- package-lock.json
- package.json
No.
Update webpack-dev-middleware to v6.
No
No
> chore: update webpack-dev-middleware to v6

- .github/workflows/nodejs.yml
Use the [Node.js LTS version syntax](https://github.com/actions/setup-node#supported-version-syntax) so we don't have to manually update the node version in the future.
None
No
> ci: use LTS node version in workflows

- lib/Server.js
- types/lib/Server.d.ts
fixes https://github.com/webpack/webpack-dev-server/pull/4796/
> chore: fix types

- lib/Server.js
- test/e2e/__snapshots__/api.test.js.snap.webpack5
- test/e2e/api.test.js
- types/lib/Server.d.ts
Removed deprecated tests.
Resolve TODO and the remove old API.
BREAKING CHANGE: The deprecated constructor API has been removed. Please use `options` as the first argument and `compiler` as the second argument.
CLI is compatible
https://github.com/webpack/webpack-cli/blob/a67dee4facb926c3a041266632e294084542a268/packages/serve/src/index.ts#L229
> refactor!: remove the deprecated constructor API

- package-lock.json
- package.json
- test/e2e/__snapshots__/multi-compiler.test.js.snap.webpack5
No
Fix https://github.com/webpack/webpack-dev-server/pull/4833
Finish webpack upgrade.
No
No
> chore: update webpack to v5.81.0

- lib/Server.js
- types/lib/Server.d.ts
No.
Resolve TODO and show warning.
No
No
> fix: show warning using custom hostname and port with sockjs

- test/e2e/allowed-hosts.test.js
> test: refactor allowed hosts test to cleanup properly

- migration-v5.md
> docs: add migration guide for v5.0.0

- test/e2e/client-reconnect.test.js
No
As discussed in #4847
No
No
> test: refactor client's reconnect tests to cleanup properly

- test/e2e/api.test.js
As discussed in https://github.com/webpack/webpack-dev-server/pull/4847
No
No
> test: refactor API E2E tests to cleanup properly

- test/e2e/host.test.js
> test: refactor host tests to cleanup properly

- test/e2e/entry.test.js
No
As discussed in #4847
No
No
> test: refactor entry tests to cleanup properly

- test/e2e/port.test.js
> test: refactor port tests to cleanup properly

- test/e2e/lazy-compilation.test.js
- test/e2e/logging.test.js
> test: refactor lazy compilation and logging tests to cleanup properly

- test/e2e/ipc.test.js
> test: refactor ipc tests to cleanup properly

- test/e2e/progress.test.js
> test: refactor progress tests to cleanup properly

- test/e2e/overlay.test.js
> test: refactor overlay tests to cleanup properly

- test/e2e/stats.test.js
> test: refactor stats tests to cleanup properly

- test/e2e/target.test.js
> test: refactor target tests to cleanup properly

- test/normalize-options.test.js
> test: refactor normalize options tests to cleanup properly

- test/e2e/web-socket-server.test.js
> test: refactor web socket server tests to cleanup properly

- test/e2e/server-and-client-transport.test.js
> test: refactor server & client transport tests to cleanup properly

- test/e2e/multi-compiler.test.js
> test: refactor multi-compiler tests to cleanup properly

- test/e2e/web-socket-server-url.test.js
> test: refactor webSocketServerURL tests to cleanup properly

- test/e2e/overlay.test.js
> test: fix flaky overlay E2E tests

- examples/default/webpack.config.js
- examples/general/config-array/webpack.config.js
- package-lock.json
- package.json
- test/fixtures/historyapifallback-3-config/webpack.config.js
- test/fixtures/historyapifallback-config/webpack.config.js
- test/fixtures/mime-types-config/webpack.config.js
- test/fixtures/multi-public-path-config/webpack.config.js
> refactor: remove `file-loader` and `url-loader` deps

- package-lock.json
- package.json
No
Pin webpack version to v5.87.0
Rleated #4966 
None
No
> chore: pin webpack version to v5.87.0

- lib/Server.js
- test/__snapshots__/normalize-options.test.js.snap.webpack5
- test/normalize-options.test.js
Resolve TODO
add cases for staticOptions normalization
NONE
NONE
> test: add cases for `staticOptions` normalization

- .github/workflows/nodejs.yml
No
update commitlint-github-action to v5
No
No
> ci: update commitlint-github-action to v5

- README.md
> docs: update CLI options in README

- lib/servers/WebsocketServer.js
Fix https://github.com/webpack/webpack-dev-server/issues/5018
> fix: improve error handling for WebsocketServer

- migration-v5.md
No need
fixes https://github.com/webpack/webpack-dev-server/issues/5088
No
No
> docs: fix migration guide

- package-lock.json
- package.json
No need, they exist in webpack-dev-middleware
avoid security problem
No
No
> fix(security): bump webpack-dev-middleware

- package-lock.json
- package.json
> Bump webpack dev middleware

- .github/workflows/nodejs.yml
> ci: add Node v22

- lib/options.json
- test/__snapshots__/validate-options.test.js.snap.webpack5
- types/lib/Server.d.ts
Yes updated snaps.
Fix description & url
No
No
> fix: update `app` option description & link in schema

- README.md
> docs: update GitHub markdown note syntax in README.md

- .cspell.json
- .husky/commit-msg
- .husky/pre-commit
- package-lock.json
- package.json
No
https://github.com/typicode/husky/releases/tag/v9.1.1
No
No
> chore: update husky hooks

- package-lock.json
No
Fix nmp audit on master
No
No
> ci: fix npm audit

- package-lock.json
- package.json
- types/lib/Server.d.ts
> chore(deps): types

- package-lock.json
- package.json
> chore: fix security

- .github/workflows/dependency-review.yml
NA
Update dependency-review-action to v4
NA
No
> ci: update dependency-review-action

- lib/Server.js
No need
https://github.com/webpack/webpack-dev-server/pull/5267#discussion_r2021090232
No
No
> fix: remove unnecessary header `X_TEST`

- package-lock.json
- package.json
See GHSA-9gqv-wp59-fq42 (CVE-2025-32997) and GHSA-4www-5p9h-95mh (CVE-2025-32996)
No breaking change, the update is a Semver patch version bump only.
> chore: update http-proxy-middleware to ^2.0.9
